# Generated by Django 4.2.30 on 2026-06-19 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Mon tableau de bord', max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_default', models.BooleanField(default=True, verbose_name='Par défaut')),
                ('layout_type', models.CharField(choices=[('grid', 'Grille'), ('compact', 'Compact'), ('large_cards', 'Grandes cartes'), ('two_columns', 'Deux colonnes'), ('three_columns', 'Trois colonnes'), ('role_based', 'Par rôle')], default='grid', max_length=20, verbose_name='Disposition')),
                ('theme', models.CharField(choices=[('orion_luxury', 'Orion Luxe'), ('light', 'Clair'), ('dark', 'Sombre'), ('btp', 'BTP'), ('commerce', 'Commerce'), ('ecommerce', 'E-commerce'), ('minimal', 'Minimaliste')], default='orion_luxury', max_length=20, verbose_name='Thème')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_profiles', to='core.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil dashboard',
                'verbose_name_plural': 'Profils dashboard',
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('code', models.CharField(max_length=60, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('module_code', models.CharField(blank=True, max_length=30, verbose_name='Module')),
                ('widget_type', models.CharField(choices=[('shortcut', 'Raccourcis'), ('list', 'Liste'), ('kpi', 'KPI'), ('chart', 'Graphique'), ('calendar', 'Calendrier'), ('task', 'Tâches'), ('notification', 'Notifications'), ('message', 'Messages'), ('document', 'Documents'), ('workflow', 'Workflow'), ('project', 'Projet'), ('finance', 'Finance'), ('support', 'Support')], default='list', max_length=20, verbose_name='Type')),
                ('icon', models.CharField(default='bi-grid', max_length=60, verbose_name='Icône Bootstrap')),
                ('color', models.CharField(default='#C6A15B', max_length=7, verbose_name='Couleur')),
                ('template_name', models.CharField(max_length=200, verbose_name='Template')),
                ('default_width', models.PositiveSmallIntegerField(default=6, verbose_name='Largeur par défaut (col)')),
                ('default_height', models.PositiveSmallIntegerField(default=4, verbose_name='Hauteur par défaut')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('requires_permission', models.BooleanField(default=False, verbose_name='Requiert permission')),
                ('permission_code', models.CharField(blank=True, max_length=60, verbose_name='Code permission')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre catalogue')),
            ],
            options={
                'verbose_name': 'Widget catalogue',
                'verbose_name_plural': 'Widgets catalogue',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserDashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Titre personnalisé')),
                ('position_x', models.PositiveSmallIntegerField(default=0, verbose_name='Position X')),
                ('position_y', models.PositiveSmallIntegerField(default=0, verbose_name='Position Y')),
                ('width', models.PositiveSmallIntegerField(default=6, verbose_name='Largeur (col)')),
                ('height', models.PositiveSmallIntegerField(default=4, verbose_name='Hauteur')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='Paramètres')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dashboard_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_widgets', to='dashboard.dashboardprofile')),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.dashboardwidget')),
            ],
            options={
                'verbose_name': 'Widget utilisateur',
                'verbose_name_plural': 'Widgets utilisateur',
                'ordering': ['position_y', 'position_x'],
            },
        ),
        migrations.CreateModel(
            name='DashboardShortcut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80, verbose_name='Libellé')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Description')),
                ('icon', models.CharField(default='bi-star', max_length=60, verbose_name='Icône Bootstrap')),
                ('color', models.CharField(default='#C6A15B', max_length=7, verbose_name='Couleur')),
                ('target_type', models.CharField(choices=[('url', 'URL directe'), ('module', 'Module ERP'), ('create_action', 'Action de création'), ('object_list', "Liste d'objets"), ('object_detail', 'Détail objet'), ('external_link', 'Lien externe')], default='url', max_length=20, verbose_name='Type cible')),
                ('target_url', models.CharField(blank=True, max_length=500, verbose_name='URL cible')),
                ('url_name', models.CharField(blank=True, max_length=100, verbose_name='Nom URL Django')),
                ('module_code', models.CharField(blank=True, max_length=30, verbose_name='Module')),
                ('action_code', models.CharField(blank=True, max_length=60, verbose_name='Action')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Favori')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_shortcuts', to='core.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_shortcuts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Raccourci',
                'verbose_name_plural': 'Raccourcis',
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='DashboardRequestBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('quote', 'Devis à traiter'), ('customer_request', 'Demande client'), ('leave', 'Demande de congé'), ('expense', 'Note de frais'), ('purchase_validation', 'Validation achat'), ('invoice_validation', 'Validation facture'), ('btp_request', 'Demande chantier'), ('sav', 'Demande SAV'), ('document_request', 'Demande document'), ('amendment', "Demande d'avenant"), ('reservation', 'Réserve client'), ('support_ticket', 'Ticket support')], max_length=30, verbose_name='Type')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('new', 'Nouvelle'), ('waiting', 'En attente'), ('in_progress', 'En cours'), ('to_validate', 'À valider'), ('validated', 'Validée'), ('refused', 'Refusée'), ('done', 'Terminée'), ('archived', 'Archivée')], default='new', max_length=20, verbose_name='Statut')),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('normal', 'Normale'), ('high', 'Haute'), ('urgent', 'Urgente')], default='normal', max_length=10, verbose_name='Priorité')),
                ('related_module', models.CharField(blank=True, max_length=30, verbose_name='Module lié')),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID objet')),
                ('target_url', models.CharField(blank=True, max_length=500, verbose_name='URL')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Échéance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_request_boxes', to='core.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_request_boxes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande dashboard',
                'verbose_name_plural': 'Demandes dashboard',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DashboardUserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_welcome_message', models.BooleanField(default=True, verbose_name='Message de bienvenue')),
                ('show_kpi_cards', models.BooleanField(default=True, verbose_name='Afficher les KPI')),
                ('show_notifications', models.BooleanField(default=True, verbose_name='Afficher les notifications')),
                ('show_sidebar_shortcuts', models.BooleanField(default=True, verbose_name='Raccourcis dans la sidebar')),
                ('default_period', models.CharField(choices=[('today', "Aujourd'hui"), ('week', 'Cette semaine'), ('month', 'Ce mois'), ('quarter', 'Ce trimestre'), ('year', 'Cette année')], default='week', max_length=10, verbose_name='Période par défaut')),
                ('compact_mode', models.BooleanField(default=False, verbose_name='Mode compact')),
                ('auto_refresh', models.BooleanField(default=False, verbose_name='Actualisation automatique')),
                ('refresh_interval', models.PositiveIntegerField(choices=[(0, 'Désactivée'), (60, '1 minute'), (300, '5 minutes'), (600, '10 minutes'), (1800, '30 minutes')], default=0, verbose_name='Intervalle (secondes)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_user_prefs', to='core.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Préférences dashboard',
                'verbose_name_plural': 'Préférences dashboard',
                'unique_together': {('company', 'user')},
            },
        ),
    ]
