# Generated by Django 4.2.30 on 2026-06-19 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardwidget',
            name='widget_type',
            field=models.CharField(choices=[('shortcut', 'Raccourcis'), ('list', 'Liste'), ('kpi', 'KPI'), ('chart', 'Graphique'), ('calendar', 'Calendrier'), ('task', 'Tâches'), ('notification', 'Notifications'), ('message', 'Messages'), ('document', 'Documents'), ('workflow', 'Workflow'), ('project', 'Projet'), ('finance', 'Finance'), ('support', 'Support'), ('alert', 'Alerte'), ('agenda', 'Agenda'), ('progress', 'Progression'), ('photo', 'Photos'), ('pipeline', 'Pipeline'), ('summary', 'Résumé'), ('note', 'Notes'), ('action', 'Actions rapides'), ('goal', 'Objectifs'), ('hr', 'RH')], default='list', max_length=20, verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='DashboardPersonalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Titre')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('color', models.CharField(choices=[('#FEF3C7', 'Jaune'), ('#DCFCE7', 'Vert'), ('#DBEAFE', 'Bleu'), ('#FCE7F3', 'Rose'), ('#F3F4F6', 'Gris'), ('#FEE2E2', 'Rouge')], default='#FEF3C7', max_length=7, verbose_name='Couleur')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Épinglée')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_notes', to='core.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Note personnelle',
                'verbose_name_plural': 'Notes personnelles',
                'ordering': ['-is_pinned', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DashboardGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Objectif')),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valeur cible')),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valeur actuelle')),
                ('unit', models.CharField(default='', max_length=30, verbose_name='Unité')),
                ('period', models.CharField(choices=[('day', 'Jour'), ('week', 'Semaine'), ('month', 'Mois'), ('quarter', 'Trimestre'), ('year', 'Année')], default='month', max_length=10, verbose_name='Période')),
                ('status', models.CharField(choices=[('active', 'En cours'), ('achieved', 'Atteint'), ('failed', 'Non atteint'), ('paused', 'Suspendu')], default='active', max_length=10, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_goals', to='core.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Objectif personnel',
                'verbose_name_plural': 'Objectifs personnels',
                'ordering': ['-created_at'],
            },
        ),
    ]
