# Generated by Django 4.2.16 on 2026-06-18 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=30, verbose_name='Numéro')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyée'), ('partial', 'Partiellement payée'), ('paid', 'Payée'), ('overdue', 'En retard'), ('cancelled', 'Annulée')], default='draft', max_length=20, verbose_name='Statut')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name='Date émission')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Date échéance')),
                ('subject', models.CharField(blank=True, max_length=300, verbose_name='Objet')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('payment_terms', models.PositiveIntegerField(default=30, verbose_name='Délai paiement (j)')),
                ('total_ht', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total HT')),
                ('total_tva', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total TVA')),
                ('total_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total TTC')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant payé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='crm.customer')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=30, verbose_name='Numéro')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyé'), ('accepted', 'Accepté'), ('refused', 'Refusé'), ('expired', 'Expiré'), ('cancelled', 'Annulé')], default='draft', max_length=20, verbose_name='Statut')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('validity_date', models.DateField(blank=True, null=True, verbose_name='Validité')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Livraison prévue')),
                ('subject', models.CharField(blank=True, max_length=300, verbose_name='Objet')),
                ('notes', models.TextField(blank=True, verbose_name='Notes client')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('payment_terms', models.PositiveIntegerField(default=30, verbose_name='Délai paiement (j)')),
                ('discount_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Remise globale %')),
                ('total_ht', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total HT')),
                ('total_tva', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total TVA')),
                ('total_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total TTC')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='core.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quotes', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='crm.customer')),
                ('salesperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Devis',
                'verbose_name_plural': 'Devis',
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=30, verbose_name='Numéro')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('confirmed', 'Confirmée'), ('in_preparation', 'En préparation'), ('shipped', 'Expédiée'), ('delivered', 'Livrée'), ('invoiced', 'Facturée'), ('cancelled', 'Annulée')], default='draft', max_length=20, verbose_name='Statut')),
                ('order_date', models.DateField(default=django.utils.timezone.now, verbose_name='Date commande')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Date livraison')),
                ('delivery_address', models.TextField(blank=True, verbose_name='Adresse livraison')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('total_ht', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total HT')),
                ('total_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total TTC')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_orders', to='core.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='crm.customer')),
                ('quote', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='sales.quote')),
                ('salesperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commande client',
                'verbose_name_plural': 'Commandes clients',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='QuoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_type', models.CharField(choices=[('product', 'Produit'), ('service', 'Service'), ('subtotal', 'Sous-total'), ('text', 'Texte')], default='product', max_length=10, verbose_name='Type')),
                ('description', models.TextField(verbose_name='Description')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Référence')),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='Quantité')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='Unité')),
                ('unit_price', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='PU HT')),
                ('discount_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Remise %')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=20, max_digits=5, verbose_name='TVA %')),
                ('total_ht', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total HT')),
                ('total_tva', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total TVA')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.quote')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Référence')),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='Quantité')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='Unité')),
                ('unit_price', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='PU HT')),
                ('discount_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Remise %')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=20, max_digits=5, verbose_name='TVA %')),
                ('total_ht', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total HT')),
                ('total_tva', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total TVA')),
                ('order', models.PositiveIntegerField(default=0)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.invoice')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='sales.salesorder'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='sales.quote'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='salesperson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
