# Generated by Django 4.2.30 on 2026-06-22 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='invoice',
            name='sales_inv_co_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='sales_inv_co_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='sales_inv_co_due_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='sales_inv_customer_idx',
        ),
        migrations.RemoveIndex(
            model_name='quote',
            name='sales_qte_co_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='quote',
            name='sales_qte_co_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='salesorder',
            name='sales_ord_co_status_idx',
        ),
    ]
