# Generated by Django 4.2.30 on 2026-06-26 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_notification_related_names'),
        ('crm', '0004_remove_customer_crm_cust_co_date_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeautyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_key', models.CharField(default='lunea', max_length=40)),
                ('skin_type', models.CharField(choices=[('normal', 'Normale'), ('dry', 'Sèche'), ('oily', 'Grasse'), ('combination', 'Mixte'), ('sensitive', 'Sensible'), ('unknown', 'Non renseigné')], default='unknown', max_length=30)),
                ('hair_type', models.CharField(choices=[('straight', 'Lisse'), ('wavy', 'Ondulé'), ('curly', 'Bouclé'), ('coily', 'Crépu'), ('fine', 'Fin'), ('thick', 'Épais'), ('unknown', 'Non renseigné')], default='unknown', max_length=30)),
                ('allergies', models.JSONField(blank=True, default=list)),
                ('intolerances', models.JSONField(blank=True, default=list)),
                ('preferred_brands', models.JSONField(blank=True, default=list)),
                ('preferred_ingredients', models.JSONField(blank=True, default=list)),
                ('avoided_ingredients', models.JSONField(blank=True, default=list)),
                ('skin_concerns', models.JSONField(blank=True, default=list)),
                ('hair_concerns', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('last_appointment_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lunea_beauty_profiles', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lunea_profiles', to=settings.AUTH_USER_MODEL)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lunea_beauty_profile', to='crm.customer')),
            ],
            options={
                'verbose_name': 'Profil beauté Lunea',
                'verbose_name_plural': 'Profils beauté Lunea',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='BeautyRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('product', 'Produit'), ('routine', 'Routine'), ('treatment', 'Soin'), ('appointment', 'Rendez-vous'), ('tip', 'Conseil')], default='product', max_length=40)),
                ('product_name', models.CharField(max_length=180)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('reason', models.TextField()),
                ('score', models.FloatField(default=0.8)),
                ('is_applied', models.BooleanField(default=False)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lunea_recommendations', to='core.company')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='lunea_beauty_profile.beautyprofile')),
            ],
            options={
                'verbose_name': 'Recommandation beauté',
                'verbose_name_plural': 'Recommandations beauté',
                'ordering': ['-score', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='beautyprofile',
            index=models.Index(fields=['company', 'brand_key'], name='lunea_beaut_company_0a051b_idx'),
        ),
    ]
