# Generated by Django 4.2.16 on 2026-06-18 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('superadmin', 'Super Administrateur'), ('admin', 'Administrateur'), ('manager', 'Responsable'), ('accountant', 'Comptable'), ('salesperson', 'Commercial'), ('purchaser', 'Acheteur'), ('warehouse', 'Magasinier'), ('hr_manager', 'Responsable RH'), ('technician', 'Technicien'), ('user', 'Utilisateur'), ('readonly', 'Lecture seule')], default='user', max_length=20, verbose_name='Rôle')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('mobile', models.CharField(blank=True, max_length=20, verbose_name='Mobile')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar')),
                ('bio', models.TextField(blank=True, verbose_name='Bio')),
                ('job_title', models.CharField(blank=True, max_length=100, verbose_name='Poste')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Département')),
                ('language', models.CharField(default='fr', max_length=5, verbose_name='Langue')),
                ('timezone', models.CharField(default='Europe/Paris', max_length=50, verbose_name='Fuseau horaire')),
                ('date_format', models.CharField(default='%d/%m/%Y', max_length=20, verbose_name='Format date')),
                ('items_per_page', models.PositiveIntegerField(default=25, verbose_name='Éléments par page')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Notifications email')),
                ('browser_notifications', models.BooleanField(default=False, verbose_name='Notifications navigateur')),
                ('two_factor_enabled', models.BooleanField(default=False, verbose_name='2FA activé')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dernière IP')),
                ('failed_login_attempts', models.PositiveIntegerField(default=0, verbose_name='Tentatives échouées')),
                ('locked_until', models.DateTimeField(blank=True, null=True, verbose_name="Verrouillé jusqu'au")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('companies', models.ManyToManyField(blank=True, related_name='users', to='core.company', verbose_name='Entreprises')),
                ('current_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_users', to='core.company', verbose_name='Entreprise courante')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200, verbose_name='Action')),
                ('url', models.CharField(blank=True, max_length=500, verbose_name='URL')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activité utilisateur',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('crm', 'CRM'), ('sales', 'Ventes'), ('accounting', 'Comptabilité'), ('purchases', 'Achats'), ('inventory', 'Stocks'), ('documents', 'Documents'), ('hr', 'RH'), ('payroll', 'Paie'), ('support', 'Support'), ('btp', 'BTP'), ('ecommerce', 'E-commerce'), ('commerce', 'Commerce'), ('production', 'Production'), ('audio', 'Audio/AV'), ('websites', 'Sites web'), ('bi', 'Reporting'), ('admin', 'Administration')], max_length=20, verbose_name='Module')),
                ('can_read', models.BooleanField(default=True, verbose_name='Lecture')),
                ('can_create', models.BooleanField(default=False, verbose_name='Création')),
                ('can_update', models.BooleanField(default=False, verbose_name='Modification')),
                ('can_delete', models.BooleanField(default=False, verbose_name='Suppression')),
                ('can_export', models.BooleanField(default=False, verbose_name='Export')),
                ('can_validate', models.BooleanField(default=False, verbose_name='Validation')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_permissions', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'Permission module',
                'verbose_name_plural': 'Permissions modules',
                'unique_together': {('user_profile', 'company', 'module')},
            },
        ),
    ]
