# Generated by Django 4.2.30 on 2026-06-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='compact_mode',
            field=models.BooleanField(default=False, verbose_name='Mode compact'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='theme',
            field=models.CharField(choices=[('light', 'Clair'), ('dark', 'Sombre'), ('system', 'Système')], default='light', max_length=10, verbose_name='Thème'),
        ),
    ]
