# Generated by Django 4.2.30 on 2026-06-23 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_notification_related_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration_type', models.CharField(choices=[('stripe', 'Stripe Paiements'), ('paypal', 'PayPal'), ('google_calendar', 'Google Calendar'), ('microsoft_365', 'Microsoft 365'), ('slack', 'Slack'), ('sendgrid', 'SendGrid'), ('twilio', 'Twilio SMS'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('quickbooks', 'QuickBooks'), ('dolibarr', 'Dolibarr'), ('custom', 'Personnalisé')], max_length=80)),
                ('name', models.CharField(max_length=180)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('sync_interval_minutes', models.PositiveIntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_configs', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_integrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuration intégration',
                'verbose_name_plural': 'Configurations intégrations',
                'ordering': ['-created_at'],
                'unique_together': {('company', 'integration_type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='IntegrationSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('success', 'Succès'), ('partial', 'Partiel'), ('failed', 'Échec')], default='pending', max_length=30)),
                ('records_synced', models.PositiveIntegerField(default=0)),
                ('records_failed', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_sync_logs', to='core.company')),
                ('integration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_logs', to='integration_center.integrationconfig')),
            ],
            options={
                'verbose_name': 'Journal synchronisation',
                'verbose_name_plural': 'Journaux synchronisation',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['company', 'integration', 'status'], name='integration_company_388086_idx')],
            },
        ),
    ]
