# Generated by Django 4.2.16 on 2026-07-17 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_notification_related_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Titre')),
                ('severity', models.CharField(choices=[('minor', 'Mineur'), ('major', 'Majeur'), ('critical', 'Critique'), ('emergency', 'Urgence')], db_index=True, max_length=20, verbose_name='Gravité')),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('investigating', 'En investigation'), ('identified', 'Identifié'), ('monitoring', 'Surveillance'), ('resolved', 'Résolu'), ('closed', 'Clôturé')], db_index=True, default='open', max_length=20, verbose_name='Statut')),
                ('description', models.TextField(verbose_name='Description')),
                ('affected_services', models.JSONField(default=list, verbose_name='Services affectés')),
                ('started_at', models.DateTimeField(verbose_name='Début')),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Détection')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Résolution')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Clôture')),
                ('root_cause', models.TextField(blank=True, verbose_name='Cause racine')),
                ('immediate_actions', models.TextField(blank=True, verbose_name='Actions immédiates')),
                ('fix_applied', models.TextField(blank=True, verbose_name='Correctif appliqué')),
                ('consequences', models.TextField(blank=True, verbose_name='Conséquences')),
                ('prevention_plan', models.TextField(blank=True, verbose_name='Plan de prévention')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affected_companies', models.ManyToManyField(blank=True, to='core.company', verbose_name='Établissements affectés')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_incidents', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('severity', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Attention'), ('error', 'Erreur'), ('critical', 'Critique')], db_index=True, max_length=20, verbose_name='Gravité')),
                ('module', models.CharField(db_index=True, max_length=100, verbose_name='Module')),
                ('environment', models.CharField(default='production', max_length=50, verbose_name='Environnement')),
                ('error_type', models.CharField(max_length=200, verbose_name='Type')),
                ('app_version', models.CharField(blank=True, max_length=50, verbose_name='Version app')),
                ('user_message', models.TextField(verbose_name='Message utilisateur')),
                ('technical_message', models.TextField(verbose_name='Message technique')),
                ('occurrence_count', models.PositiveIntegerField(default=1, verbose_name='Occurrences')),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Première occurrence')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='Dernière occurrence')),
                ('api_route', models.CharField(blank=True, max_length=500, verbose_name='Route / Action')),
                ('http_method', models.CharField(blank=True, max_length=10, verbose_name='Méthode HTTP')),
                ('response_code', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Code réponse')),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='ID corrélation')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='Navigateur / Appareil')),
                ('status', models.CharField(choices=[('new', 'Nouvelle'), ('analysed', 'Analysée'), ('confirmed', 'Confirmée'), ('in_progress', 'En cours'), ('monitoring', 'Surveillée'), ('resolved', 'Résolue'), ('ignored', 'Ignorée'), ('reopened', 'Rouverte')], db_index=True, default='new', max_length=20, verbose_name='Statut')),
                ('probable_cause', models.TextField(blank=True, verbose_name='Cause probable')),
                ('solution_applied', models.TextField(blank=True, verbose_name='Solution appliquée')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Date résolution')),
                ('ignore_reason', models.TextField(blank=True, verbose_name='Justification ignorée')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('affected_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_errors', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_errors', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_errors', to='core.company', verbose_name='Établissement')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='errors', to='system_health.systemincident', verbose_name='Incident lié')),
            ],
            options={
                'verbose_name': 'Erreur système',
                'verbose_name_plural': 'Erreurs système',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(choices=[('cpu_usage', 'CPU (%)'), ('memory_usage', 'Mémoire (%)'), ('disk_usage', 'Disque utilisé (%)'), ('disk_free_gb', 'Disque libre (Go)'), ('open_files', 'Fichiers ouverts'), ('load_average', 'Charge système'), ('network_latency_ms', 'Latence réseau (ms)'), ('app_available', 'Application disponible'), ('avg_response_ms', 'Temps réponse moyen (ms)'), ('max_response_ms', 'Temps réponse max (ms)'), ('requests_per_min', 'Requêtes/min'), ('error_rate_pct', "Taux d'erreur (%)"), ('active_sessions', 'Sessions actives'), ('slow_requests_1h', 'Requêtes lentes/h'), ('db_available', 'DB disponible'), ('db_connections', 'Connexions DB'), ('db_slow_queries_1h', 'Requêtes lentes DB/h'), ('db_size_gb', 'Taille DB (Go)'), ('db_pending_migrations', 'Migrations en attente'), ('backup_age_hours', 'Âge dernière sauvegarde (h)'), ('backup_size_mb', 'Taille dernière sauvegarde (Mo)'), ('backup_test_age_days', 'Âge dernier test restauration (j)'), ('queue_pending', 'Tâches en attente'), ('queue_failed_1h', 'Tâches échouées/h'), ('queue_workers', 'Workers actifs'), ('failed_logins_1h', 'Connexions échouées/h'), ('locked_accounts', 'Comptes verrouillés'), ('open_errors', 'Erreurs ouvertes'), ('open_incidents', 'Incidents ouverts')], db_index=True, max_length=60, verbose_name='Capteur')),
                ('value', models.FloatField(null=True, verbose_name='Valeur')),
                ('status', models.CharField(choices=[('ok', 'Sain'), ('warning', 'Attention'), ('critical', 'Critique'), ('error', 'Erreur collecte'), ('unknown', 'Inconnu')], default='unknown', max_length=20, verbose_name='Statut')),
                ('metadata', models.JSONField(default=dict, verbose_name='Métadonnées')),
                ('collected_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Collecté à')),
            ],
            options={
                'verbose_name': 'Lecture capteur',
                'ordering': ['-collected_at'],
                'indexes': [models.Index(fields=['sensor_type', '-collected_at'], name='system_heal_sensor__0c68f2_idx')],
            },
        ),
        migrations.CreateModel(
            name='RiskRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20, unique=True, verbose_name='Identifiant')),
                ('title', models.CharField(max_length=300, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('category', models.CharField(choices=[('security', 'Sécurité'), ('privacy', 'Confidentialité'), ('availability', 'Disponibilité'), ('data_integrity', 'Intégrité des données'), ('performance', 'Performance'), ('compliance', 'Conformité'), ('human_error', 'Erreur humaine'), ('business_error', 'Erreur métier'), ('external_dependency', 'Dépendance externe'), ('backup', 'Sauvegarde'), ('infrastructure', 'Infrastructure'), ('health', 'Santé'), ('finance', 'Finance'), ('business_continuity', "Continuité d'activité")], db_index=True, max_length=50, verbose_name='Catégorie')),
                ('origin', models.CharField(choices=[('audit', 'Audit'), ('incident', 'Incident'), ('manual', 'Manuel'), ('sensor', 'Capteur automatique'), ('security', 'Alerte sécurité')], default='manual', max_length=20, verbose_name='Origine')),
                ('affected_module', models.CharField(blank=True, max_length=100, verbose_name='Module concerné')),
                ('affected_data', models.TextField(blank=True, verbose_name='Données concernées')),
                ('probability', models.CharField(choices=[('1', 'Rare'), ('2', 'Peu probable'), ('3', 'Possible'), ('4', 'Probable'), ('5', 'Quasi-certain')], max_length=1, verbose_name='Probabilité')),
                ('impact', models.CharField(choices=[('1', 'Négligeable'), ('2', 'Mineur'), ('3', 'Modéré'), ('4', 'Majeur'), ('5', 'Catastrophique')], max_length=1, verbose_name='Impact')),
                ('probability_justification', models.TextField(blank=True, verbose_name='Justification probabilité')),
                ('impact_justification', models.TextField(blank=True, verbose_name='Justification impact')),
                ('detected_at', models.DateField(default=django.utils.timezone.now, verbose_name='Détecté le')),
                ('existing_measures', models.TextField(blank=True, verbose_name='Mesures existantes')),
                ('corrective_actions', models.TextField(blank=True, verbose_name='Actions correctives')),
                ('target_date', models.DateField(blank=True, null=True, verbose_name='Date cible')),
                ('status', models.CharField(choices=[('identified', 'Identifié'), ('assessed', 'Évalué'), ('treating', 'Traitement en cours'), ('monitored', 'Surveillé'), ('accepted', 'Accepté'), ('closed', 'Clôturé')], db_index=True, default='identified', max_length=20, verbose_name='État')),
                ('residual_risk', models.CharField(blank=True, choices=[('1', 'Négligeable'), ('2', 'Mineur'), ('3', 'Modéré'), ('4', 'Majeur'), ('5', 'Catastrophique')], max_length=1, verbose_name='Risque résiduel')),
                ('last_review', models.DateField(blank=True, null=True, verbose_name='Dernière réévaluation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_risks', to=settings.AUTH_USER_MODEL)),
                ('linked_incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks', to='system_health.systemincident', verbose_name='Incident lié')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_risks', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
            ],
            options={
                'verbose_name': 'Risque',
                'verbose_name_plural': 'Registre des risques',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PostIncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what_happened', models.TextField(verbose_name="Ce qui s'est passé")),
                ('why_it_happened', models.TextField(verbose_name='Pourquoi cela est arrivé')),
                ('why_not_detected_earlier', models.TextField(verbose_name='Pourquoi non détecté plus tôt')),
                ('how_fixed', models.TextField(verbose_name='Comment corrigé')),
                ('how_to_prevent', models.TextField(verbose_name='Comment prévenir la répétition')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('incident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post_report', to='system_health.systemincident')),
            ],
            options={
                'verbose_name': 'Rapport post-incident',
            },
        ),
        migrations.CreateModel(
            name='IncidentTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('detected', 'Détection'), ('update', 'Mise à jour'), ('action', 'Action prise'), ('resolved', 'Résolution'), ('closed', 'Clôture'), ('comment', 'Commentaire'), ('escalated', 'Escalade'), ('reopened', 'Réouverture')], max_length=20, verbose_name='Type')),
                ('description', models.TextField(verbose_name='Description')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='system_health.systemincident')),
            ],
            options={
                'verbose_name': 'Chronologie incident',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='HealthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view_health', models.BooleanField(default=False, verbose_name='Consulter la santé')),
                ('can_view_errors', models.BooleanField(default=False, verbose_name='Consulter les erreurs')),
                ('can_view_technical', models.BooleanField(default=False, verbose_name='Consulter données techniques')),
                ('can_view_security', models.BooleanField(default=False, verbose_name='Consulter alertes sécurité')),
                ('can_view_risks', models.BooleanField(default=False, verbose_name='Consulter les risques')),
                ('can_manage_incidents', models.BooleanField(default=False, verbose_name='Gérer les incidents')),
                ('can_edit_thresholds', models.BooleanField(default=False, verbose_name='Modifier les seuils')),
                ('can_close_alerts', models.BooleanField(default=False, verbose_name='Fermer les alertes')),
                ('can_export_reports', models.BooleanField(default=False, verbose_name='Exporter les rapports')),
                ('can_view_sensitive', models.BooleanField(default=False, verbose_name='Données sensibles')),
                ('can_administrate', models.BooleanField(default=False, verbose_name='Administrer la supervision')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_permission', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permission santé système',
                'verbose_name_plural': 'Permissions santé système',
            },
        ),
        migrations.CreateModel(
            name='HealthAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view_dashboard', 'Consultation tableau de bord'), ('view_errors', 'Consultation erreurs'), ('view_incident', 'Consultation incident'), ('view_risk', 'Consultation risque'), ('export', 'Export'), ('edit_threshold', 'Modification seuil'), ('close_alert', 'Fermeture alerte'), ('delete', 'Archivage'), ('status_change', 'Changement statut'), ('risk_edit', 'Modification risque'), ('sensitive_view', 'Accès données sensibles')], max_length=40, verbose_name='Action')),
                ('target_type', models.CharField(blank=True, max_length=50, verbose_name='Type cible')),
                ('target_id', models.CharField(blank=True, max_length=50, verbose_name='ID cible')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit santé système',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ErrorComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('error', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='system_health.systemerror')),
            ],
            options={
                'verbose_name': 'Commentaire erreur',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(max_length=60, unique=True, verbose_name='Capteur')),
                ('warning_threshold', models.FloatField(blank=True, null=True, verbose_name='Seuil attention')),
                ('critical_threshold', models.FloatField(blank=True, null=True, verbose_name='Seuil critique')),
                ('comparison', models.CharField(choices=[('gt', '>'), ('lt', '<'), ('gte', '>='), ('lte', '<=')], default='gt', max_length=5, verbose_name='Comparaison')),
                ('enabled', models.BooleanField(default=True, verbose_name='Actif')),
                ('silence_until', models.DateTimeField(blank=True, null=True, verbose_name="Silencieux jusqu'à")),
                ('notification_emails', models.JSONField(default=list, verbose_name='Emails notification')),
                ('escalation_after_min', models.PositiveIntegerField(default=30, verbose_name='Escalade après (min)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Seuil d'alerte",
                'ordering': ['sensor_type'],
            },
        ),
        migrations.AddIndex(
            model_name='systemerror',
            index=models.Index(fields=['severity', 'status'], name='system_heal_severit_c4e971_idx'),
        ),
        migrations.AddIndex(
            model_name='systemerror',
            index=models.Index(fields=['module', 'status'], name='system_heal_module_adf556_idx'),
        ),
        migrations.AddIndex(
            model_name='systemerror',
            index=models.Index(fields=['fingerprint', 'status'], name='system_heal_fingerp_896b91_idx'),
        ),
        migrations.AddIndex(
            model_name='riskregister',
            index=models.Index(fields=['category', 'status'], name='system_heal_categor_d7201d_idx'),
        ),
        migrations.AddIndex(
            model_name='healthauditlog',
            index=models.Index(fields=['user', 'action'], name='system_heal_user_id_6d6a2e_idx'),
        ),
    ]
