# Generated by Django 4.2.30 on 2026-07-18 17:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system_health', '0003_incident_enrich'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='healthsnapshot',
            new_name='system_heal_collect_ffc0b3_idx',
            old_name='system_heal_collect_idx',
        ),
        migrations.AlterField(
            model_name='systemincident',
            name='auto_created',
            field=models.BooleanField(default=False, verbose_name='Créé automatiquement'),
        ),
        migrations.AlterField(
            model_name='systemincident',
            name='probable_deployment_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID déploiement probable'),
        ),
        migrations.AlterField(
            model_name='systemincident',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Début'),
        ),
    ]
