# Generated by Django 4.2.30 on 2026-07-12 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # 0017 n'a jamais été commitée sur git (migrations orphelines locales
        # 0012-0021, voir commit ae171f5) — 0022 est la dernière migration
        # websites réellement présente en dépôt, elle suffit largement (le
        # champ website.company utilisé ici existe depuis bien avant 0012).
        ('websites', '0022_websitedomain_website_nullable'),
        ('core', '0006_notification_related_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudflareZoneConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(max_length=255, verbose_name='Zone (ex: elysiums.fr)')),
                ('zone_id', models.CharField(blank=True, max_length=255, verbose_name='Zone ID Cloudflare')),
                ('api_token_hint', models.CharField(blank=True, help_text='Ne pas stocker le token ici. Ex : token se terminant par …abcd.', max_length=80, verbose_name='Indice token API')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloudflare_zone_configs', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuration zone Cloudflare',
                'verbose_name_plural': 'Configurations zones Cloudflare',
            },
        ),
        migrations.CreateModel(
            name='DomainDiagnosticRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'En cours'), ('ok', 'OK'), ('warning', 'Avertissement'), ('error', 'Erreur'), ('repaired', 'Réparé')], default='running', max_length=40)),
                ('summary', models.TextField(blank=True)),
                ('raw_results', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_diagnostic_runs', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Diagnostic run',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DomainDiagnosticTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, verbose_name='Domaine')),
                ('brand_key', models.CharField(blank=True, help_text='siecle, lunea, login, orion…', max_length=50, verbose_name='Marque (slug)')),
                ('target_type', models.CharField(choices=[('website', 'Site web Orion'), ('login', 'Login Orion'), ('api', 'API'), ('custom', 'Personnalisé')], default='website', max_length=40, verbose_name='Type')),
                ('expected_origin_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP origine attendue')),
                ('expected_record_type', models.CharField(default='A', max_length=20, verbose_name='Type DNS')),
                ('expected_record_content', models.CharField(blank=True, max_length=255, verbose_name='Contenu DNS attendu')),
                ('expected_proxy', models.CharField(choices=[('auto', 'Automatique'), ('proxied', 'Proxy Cloudflare activé'), ('dns_only', 'DNS uniquement')], default='proxied', max_length=20, verbose_name='Proxy attendu')),
                ('expected_ssl_mode', models.CharField(default='strict', max_length=40, verbose_name='Mode SSL attendu')),
                ('expected_https_status', models.PositiveIntegerField(default=200, verbose_name='Code HTTP attendu')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('auto_repair_enabled', models.BooleanField(default=False, verbose_name='Réparation auto')),
                ('last_scan_at', models.DateTimeField(blank=True, null=True, verbose_name='Dernier scan')),
                ('last_status', models.CharField(blank=True, max_length=40, verbose_name='Dernier statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cloudflare_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targets', to='domain_diagnostics.cloudflarezoneconfig')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_diagnostic_targets', to='core.company')),
                ('website', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_targets', to='websites.website')),
            ],
            options={
                'verbose_name': 'Cible diagnostic domaine',
                'verbose_name_plural': 'Cibles diagnostic domaines',
            },
        ),
        migrations.CreateModel(
            name='DomainIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('website_link', 'Lien Website Orion'), ('dns_missing', 'DNS manquant'), ('dns_wrong_content', 'DNS incorrect'), ('cloudflare_proxy', 'Proxy Cloudflare incorrect'), ('cloudflare_ssl', 'SSL Cloudflare incorrect'), ('http_error', 'Erreur HTTP'), ('https_error', 'Erreur HTTPS'), ('redirect_error', 'Erreur redirection'), ('nginx_missing', 'Nginx manquant'), ('nginx_wrong_server_name', 'Nginx server_name incorrect'), ('brand_mismatch', 'Mauvaise marque'), ('unknown', 'Inconnu')], max_length=80)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Avertissement'), ('critical', 'Critique')], default='warning', max_length=40)),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('ignored', 'Ignoré'), ('fixed', 'Corrigé')], default='open', max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('repair_code', models.CharField(blank=True, max_length=120)),
                ('repair_payload', models.JSONField(blank=True, default=dict)),
                ('can_auto_repair', models.BooleanField(default=False)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('fixed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_issues', to='core.company')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='domain_diagnostics.domaindiagnosticrun')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='domain_diagnostics.domaindiagnostictarget')),
            ],
            options={
                'verbose_name': 'Problème domaine',
                'verbose_name_plural': 'Problèmes domaines',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='DomainRepairLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repair_code', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('success', 'Succès'), ('failed', 'Échec'), ('skipped', 'Ignoré')], max_length=40)),
                ('message', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('executed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_repair_logs', to='core.company')),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repair_logs', to='domain_diagnostics.domainissue')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repair_logs', to='domain_diagnostics.domaindiagnostictarget')),
            ],
            options={
                'verbose_name': 'Journal réparation domaine',
                'verbose_name_plural': 'Journal réparations domaines',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.AddField(
            model_name='domaindiagnosticrun',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='domain_diagnostics.domaindiagnostictarget'),
        ),
        migrations.AddIndex(
            model_name='domainissue',
            index=models.Index(fields=['company', 'status'], name='domain_diag_company_acd717_idx'),
        ),
        migrations.AddIndex(
            model_name='domainissue',
            index=models.Index(fields=['issue_type'], name='domain_diag_issue_t_cd1361_idx'),
        ),
        migrations.AddIndex(
            model_name='domainissue',
            index=models.Index(fields=['severity'], name='domain_diag_severit_1dbccd_idx'),
        ),
        migrations.AddIndex(
            model_name='domaindiagnostictarget',
            index=models.Index(fields=['company', 'domain'], name='domain_diag_company_4978a0_idx'),
        ),
        migrations.AddIndex(
            model_name='domaindiagnostictarget',
            index=models.Index(fields=['brand_key'], name='domain_diag_brand_k_14122a_idx'),
        ),
        migrations.AddIndex(
            model_name='domaindiagnostictarget',
            index=models.Index(fields=['is_active'], name='domain_diag_is_acti_671409_idx'),
        ),
        migrations.AddIndex(
            model_name='domaindiagnostictarget',
            index=models.Index(fields=['last_status'], name='domain_diag_last_st_e2db04_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='domaindiagnostictarget',
            unique_together={('company', 'domain')},
        ),
        migrations.AddIndex(
            model_name='domaindiagnosticrun',
            index=models.Index(fields=['company', 'status'], name='domain_diag_company_9ec59a_idx'),
        ),
        migrations.AddIndex(
            model_name='domaindiagnosticrun',
            index=models.Index(fields=['started_at'], name='domain_diag_started_a58d31_idx'),
        ),
        migrations.AddIndex(
            model_name='cloudflarezoneconfig',
            index=models.Index(fields=['company', 'zone_name'], name='domain_diag_company_8ab58b_idx'),
        ),
        migrations.AddIndex(
            model_name='cloudflarezoneconfig',
            index=models.Index(fields=['is_active'], name='domain_diag_is_acti_7d232c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cloudflarezoneconfig',
            unique_together={('company', 'zone_name')},
        ),
    ]
