# Generated by Django 4.2.30 on 2026-06-23 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_notification_related_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_key', models.CharField(blank=True, max_length=40)),
                ('title', models.CharField(max_length=180)),
                ('file', models.FileField(upload_to='smart_documents/')),
                ('document_type', models.CharField(choices=[('contract', 'Contrat'), ('invoice', 'Facture'), ('quote', 'Devis'), ('report', 'Rapport'), ('id_card', 'Pièce identité'), ('certificate', 'Certificat'), ('plan', 'Plan'), ('photo', 'Photo'), ('other', 'Autre')], default='other', max_length=80)),
                ('related_object_type', models.CharField(blank=True, max_length=80)),
                ('related_object_id', models.CharField(blank=True, max_length=80)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('version', models.PositiveIntegerField(default=1)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('is_signed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_documents', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_smart_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document intelligent',
                'verbose_name_plural': 'Documents intelligents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentSignatureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signer_name', models.CharField(max_length=180)),
                ('signer_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('sent', 'Envoyée'), ('signed', 'Signée'), ('declined', 'Refusée'), ('expired', 'Expirée')], default='pending', max_length=40)),
                ('token', models.CharField(blank=True, max_length=120, unique=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_requests', to='core.company')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_requests', to='smart_documents.smartdocument')),
            ],
            options={
                'verbose_name': 'Demande de signature',
                'verbose_name_plural': 'Demandes de signature',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='smartdocument',
            index=models.Index(fields=['company', 'document_type'], name='smart_docum_company_c1a90b_idx'),
        ),
        migrations.AddIndex(
            model_name='smartdocument',
            index=models.Index(fields=['company', 'related_object_type', 'related_object_id'], name='smart_docum_company_eb0f7f_idx'),
        ),
    ]
