# Generated by Django 4.2.30 on 2026-06-23 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_notification_related_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('backup_type', models.CharField(choices=[('manual', 'Manuel'), ('scheduled', 'Planifié'), ('pre_restore', 'Pré-restauration'), ('pre_migration', 'Pré-migration'), ('system', 'Système')], default='manual', max_length=20, verbose_name='Type')),
                ('scope', models.CharField(choices=[('core_database', 'Base centrale'), ('company_database', 'Base entreprise'), ('all_companies', 'Toutes les entreprises'), ('media_files', 'Fichiers médias'), ('documents', 'Documents'), ('full_system', 'Système complet')], default='company_database', max_length=30, verbose_name='Périmètre')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('success', 'Succès'), ('failed', 'Échoué'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='Chemin fichier')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='Taille (octets)')),
                ('checksum', models.CharField(blank=True, max_length=64, verbose_name='Checksum SHA-256')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Début')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin')),
                ('duration_seconds', models.FloatField(blank=True, null=True, verbose_name='Durée (s)')),
                ('error_message', models.TextField(blank=True, verbose_name='Erreur')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_jobs', to='core.company', verbose_name='Entreprise')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_jobs_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Sauvegarde',
                'verbose_name_plural': 'Sauvegardes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackupSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('scope', models.CharField(choices=[('core_database', 'Base centrale'), ('company_database', 'Base entreprise'), ('all_companies', 'Toutes les entreprises'), ('media_files', 'Fichiers médias'), ('documents', 'Documents'), ('full_system', 'Système complet')], default='company_database', max_length=30, verbose_name='Périmètre')),
                ('frequency', models.CharField(choices=[('daily', 'Quotidienne'), ('weekly', 'Hebdomadaire'), ('monthly', 'Mensuelle')], default='daily', max_length=10, verbose_name='Fréquence')),
                ('time', models.TimeField(default='02:00', verbose_name='Heure')),
                ('day_of_week', models.IntegerField(blank=True, choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], null=True, verbose_name='Jour de la semaine')),
                ('retention_days', models.PositiveIntegerField(default=30, verbose_name='Rétention (jours)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='Dernier run')),
                ('next_run_at', models.DateTimeField(blank=True, null=True, verbose_name='Prochain run')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backup_schedules', to='core.company', verbose_name='Entreprise')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_schedules_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Planification sauvegarde',
                'verbose_name_plural': 'Planifications sauvegardes',
                'ordering': ['frequency', 'time'],
            },
        ),
        migrations.CreateModel(
            name='BackupRestoreLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'En cours'), ('success', 'Succès'), ('failed', 'Échoué')], default='running', max_length=20, verbose_name='Statut')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Début')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin')),
                ('error_message', models.TextField(blank=True, verbose_name='Erreur')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('backup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restore_logs', to='backups.backupjob', verbose_name='Sauvegarde')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restore_logs', to='core.company', verbose_name='Entreprise')),
                ('restored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restore_logs', to=settings.AUTH_USER_MODEL, verbose_name='Restauré par')),
            ],
            options={
                'verbose_name': 'Log de restauration',
                'verbose_name_plural': 'Logs de restauration',
                'ordering': ['-created_at'],
            },
        ),
    ]
