# Generated by Django 4.2.30 on 2026-08-11 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupjob',
            name='backup_type',
            field=models.CharField(choices=[('manual', 'Manuel'), ('scheduled', 'Planifié'), ('pre_restore', 'Pré-restauration'), ('pre_migration', 'Pré-migration'), ('system', 'Système'), ('imported', 'Importé')], default='manual', max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='backupjob',
            name='scope',
            field=models.CharField(choices=[('core_database', 'Base centrale'), ('company_database', 'Base entreprise'), ('all_companies', 'Toutes les entreprises'), ('media_files', 'Fichiers médias'), ('documents', 'Documents'), ('full_system', 'Système complet'), ('portable_export', 'Export portable (base + médias, transfert entre instances)')], default='company_database', max_length=30, verbose_name='Périmètre'),
        ),
        migrations.AlterField(
            model_name='backupschedule',
            name='scope',
            field=models.CharField(choices=[('core_database', 'Base centrale'), ('company_database', 'Base entreprise'), ('all_companies', 'Toutes les entreprises'), ('media_files', 'Fichiers médias'), ('documents', 'Documents'), ('full_system', 'Système complet'), ('portable_export', 'Export portable (base + médias, transfert entre instances)')], default='company_database', max_length=30, verbose_name='Périmètre'),
        ),
    ]
