"""
python manage.py seed_dashboard_widgets
Crée tous les widgets du catalogue Orion ERP.
"""
from django.core.management.base import BaseCommand
from apps.dashboard.models import DashboardWidget

WIDGETS = [
    # ─── Généraux ────────────────────────────────────────────────────────────
    {
        'name': 'Raccourcis favoris', 'code': 'favorite_shortcuts',
        'description': 'Affiche les raccourcis personnalisés de l\'utilisateur.',
        'module_code': '', 'widget_type': 'shortcut',
        'icon': 'bi-lightning-charge', 'color': '#C6A15B',
        'template_name': 'dashboard/partials/widget_shortcuts.html',
        'default_width': 12, 'default_height': 2, 'order': 1,
        'requires_permission': False,
    },
    {
        'name': 'Mes demandes', 'code': 'my_requests',
        'description': 'Affiche les demandes liées à l\'utilisateur.',
        'module_code': '', 'widget_type': 'workflow',
        'icon': 'bi-inbox', 'color': '#2563EB',
        'template_name': 'dashboard/partials/widget_requests.html',
        'default_width': 6, 'default_height': 4, 'order': 2,
        'requires_permission': False,
    },
    {
        'name': 'Mes tâches', 'code': 'my_tasks',
        'description': 'Affiche les tâches assignées à l\'utilisateur.',
        'module_code': '', 'widget_type': 'task',
        'icon': 'bi-check2-square', 'color': '#10B981',
        'template_name': 'dashboard/partials/widget_tasks.html',
        'default_width': 6, 'default_height': 4, 'order': 3,
        'requires_permission': False,
    },
    {
        'name': 'Mes validations', 'code': 'my_validations',
        'description': 'Affiche les éléments en attente de validation.',
        'module_code': '', 'widget_type': 'workflow',
        'icon': 'bi-clipboard2-check', 'color': '#F59E0B',
        'template_name': 'dashboard/partials/widget_validations.html',
        'default_width': 12, 'default_height': 4, 'order': 4,
        'requires_permission': False,
    },
    {
        'name': 'Mes notifications', 'code': 'my_notifications',
        'description': 'Affiche les notifications récentes.',
        'module_code': '', 'widget_type': 'notification',
        'icon': 'bi-bell', 'color': '#7C3AED',
        'template_name': 'dashboard/partials/widget_notifications.html',
        'default_width': 6, 'default_height': 4, 'order': 5,
        'requires_permission': False,
    },
    {
        'name': 'Mes messages', 'code': 'my_messages',
        'description': 'Affiche les derniers messages client ou internes.',
        'module_code': 'support', 'widget_type': 'message',
        'icon': 'bi-chat-dots', 'color': '#0891B2',
        'template_name': 'dashboard/partials/widget_messages.html',
        'default_width': 6, 'default_height': 4, 'order': 6,
        'requires_permission': False,
    },
    {
        'name': 'Documents récents', 'code': 'recent_documents',
        'description': 'Affiche les documents récemment ajoutés ou partagés.',
        'module_code': 'documents', 'widget_type': 'document',
        'icon': 'bi-folder2-open', 'color': '#6B7280',
        'template_name': 'dashboard/partials/widget_documents.html',
        'default_width': 6, 'default_height': 4, 'order': 7,
        'requires_permission': True, 'permission_code': 'documents',
    },
    {
        'name': 'Calendrier', 'code': 'calendar_events',
        'description': 'Affiche les rendez-vous, interventions, tâches et échéances.',
        'module_code': '', 'widget_type': 'calendar',
        'icon': 'bi-calendar3', 'color': '#0891B2',
        'template_name': 'dashboard/partials/widget_calendar.html',
        'default_width': 12, 'default_height': 4, 'order': 8,
        'requires_permission': False,
    },
    # ─── BTP ─────────────────────────────────────────────────────────────────
    {
        'name': 'Chantiers en cours', 'code': 'btp_active_projects',
        'description': 'Affiche les chantiers en cours avec statut et avancement.',
        'module_code': 'btp', 'widget_type': 'project',
        'icon': 'bi-building-gear', 'color': '#F59E0B',
        'template_name': 'dashboard/partials/widget_btp.html',
        'default_width': 12, 'default_height': 5, 'order': 10,
        'requires_permission': True, 'permission_code': 'btp',
    },
    {
        'name': 'Mes chantiers', 'code': 'btp_my_projects',
        'description': 'Chantiers où l\'utilisateur est responsable ou affecté.',
        'module_code': 'btp', 'widget_type': 'project',
        'icon': 'bi-cone-striped', 'color': '#F59E0B',
        'template_name': 'dashboard/partials/widget_btp.html',
        'default_width': 8, 'default_height': 4, 'order': 11,
        'requires_permission': True, 'permission_code': 'btp',
    },
    {
        'name': 'Heures à valider', 'code': 'btp_hours_to_validate',
        'description': 'Pointages soumis en attente de validation.',
        'module_code': 'btp', 'widget_type': 'workflow',
        'icon': 'bi-clock-history', 'color': '#DC2626',
        'template_name': 'dashboard/partials/widget_btp.html',
        'default_width': 6, 'default_height': 4, 'order': 12,
        'requires_permission': True, 'permission_code': 'btp',
    },
    {
        'name': 'Réserves ouvertes', 'code': 'btp_open_reservations',
        'description': 'Réserves client ou chantier ouvertes.',
        'module_code': 'btp', 'widget_type': 'list',
        'icon': 'bi-exclamation-triangle', 'color': '#F59E0B',
        'template_name': 'dashboard/partials/widget_btp.html',
        'default_width': 6, 'default_height': 4, 'order': 13,
        'requires_permission': True, 'permission_code': 'btp',
    },
    {
        'name': 'Avenants en attente', 'code': 'btp_pending_change_requests',
        'description': 'Demandes d\'avenants à traiter.',
        'module_code': 'btp', 'widget_type': 'workflow',
        'icon': 'bi-file-earmark-plus', 'color': '#7C3AED',
        'template_name': 'dashboard/partials/widget_btp.html',
        'default_width': 6, 'default_height': 4, 'order': 14,
        'requires_permission': True, 'permission_code': 'btp',
    },
    {
        'name': 'Demandes de devis guidées', 'code': 'btp_guided_quote_requests',
        'description': 'Demandes reçues depuis le site vitrine ou portail client.',
        'module_code': 'btp', 'widget_type': 'list',
        'icon': 'bi-lightning', 'color': '#C6A15B',
        'template_name': 'dashboard/partials/widget_btp.html',
        'default_width': 6, 'default_height': 4, 'order': 15,
        'requires_permission': True, 'permission_code': 'btp',
    },
    # ─── CRM & Ventes ─────────────────────────────────────────────────────────
    {
        'name': 'Prospects à relancer', 'code': 'crm_followups',
        'description': 'Prospects avec une action de suivi à réaliser.',
        'module_code': 'crm', 'widget_type': 'list',
        'icon': 'bi-person-plus', 'color': '#0891B2',
        'template_name': 'dashboard/partials/widget_crm.html',
        'default_width': 6, 'default_height': 4, 'order': 20,
        'requires_permission': True, 'permission_code': 'crm',
    },
    {
        'name': 'Opportunités en cours', 'code': 'crm_open_opportunities',
        'description': 'Pipeline commercial en cours.',
        'module_code': 'crm', 'widget_type': 'list',
        'icon': 'bi-trophy', 'color': '#C6A15B',
        'template_name': 'dashboard/partials/widget_crm.html',
        'default_width': 6, 'default_height': 4, 'order': 21,
        'requires_permission': True, 'permission_code': 'crm',
    },
    {
        'name': 'Devis à envoyer', 'code': 'sales_quotes_to_send',
        'description': 'Devis en brouillon prêts à envoyer.',
        'module_code': 'sales', 'widget_type': 'list',
        'icon': 'bi-file-earmark-arrow-up', 'color': '#2563EB',
        'template_name': 'dashboard/partials/widget_quotes.html',
        'default_width': 6, 'default_height': 4, 'order': 22,
        'requires_permission': True, 'permission_code': 'sales',
    },
    {
        'name': 'Devis en attente réponse', 'code': 'sales_quotes_waiting_response',
        'description': 'Devis envoyés en attente de réponse client.',
        'module_code': 'sales', 'widget_type': 'list',
        'icon': 'bi-hourglass-split', 'color': '#F59E0B',
        'template_name': 'dashboard/partials/widget_quotes.html',
        'default_width': 6, 'default_height': 4, 'order': 23,
        'requires_permission': True, 'permission_code': 'sales',
    },
    {
        'name': 'Factures impayées', 'code': 'sales_unpaid_invoices',
        'description': 'Factures clients non réglées.',
        'module_code': 'sales', 'widget_type': 'finance',
        'icon': 'bi-receipt-cutoff', 'color': '#DC2626',
        'template_name': 'dashboard/partials/widget_invoices.html',
        'default_width': 6, 'default_height': 4, 'order': 24,
        'requires_permission': True, 'permission_code': 'sales',
    },
    # ─── Comptabilité ─────────────────────────────────────────────────────────
    {
        'name': 'Solde trésorerie', 'code': 'accounting_cash_balance',
        'description': 'Solde consolidé des comptes bancaires.',
        'module_code': 'accounting', 'widget_type': 'kpi',
        'icon': 'bi-bank', 'color': '#10B981',
        'template_name': 'dashboard/partials/widget_accounting.html',
        'default_width': 4, 'default_height': 2, 'order': 30,
        'requires_permission': True, 'permission_code': 'accounting',
    },
    {
        'name': 'Factures clients en retard', 'code': 'accounting_overdue_customer_invoices',
        'description': 'Factures dont la date d\'échéance est dépassée.',
        'module_code': 'accounting', 'widget_type': 'finance',
        'icon': 'bi-exclamation-octagon', 'color': '#DC2626',
        'template_name': 'dashboard/partials/widget_accounting.html',
        'default_width': 6, 'default_height': 4, 'order': 31,
        'requires_permission': True, 'permission_code': 'accounting',
    },
    {
        'name': 'Factures fournisseurs à payer', 'code': 'accounting_supplier_invoices_due',
        'description': 'Factures fournisseurs arrivant à échéance.',
        'module_code': 'accounting', 'widget_type': 'finance',
        'icon': 'bi-shop', 'color': '#7C3AED',
        'template_name': 'dashboard/partials/widget_accounting.html',
        'default_width': 6, 'default_height': 4, 'order': 32,
        'requires_permission': True, 'permission_code': 'accounting',
    },
    {
        'name': 'TVA estimée', 'code': 'accounting_vat_summary',
        'description': 'Estimation de la TVA à décaisser.',
        'module_code': 'accounting', 'widget_type': 'kpi',
        'icon': 'bi-percent', 'color': '#0D9488',
        'template_name': 'dashboard/partials/widget_accounting.html',
        'default_width': 4, 'default_height': 2, 'order': 33,
        'requires_permission': True, 'permission_code': 'accounting',
    },
    {
        'name': 'Écritures en brouillon', 'code': 'accounting_draft_entries',
        'description': 'Écritures comptables non validées.',
        'module_code': 'accounting', 'widget_type': 'list',
        'icon': 'bi-pencil-square', 'color': '#6B7280',
        'template_name': 'dashboard/partials/widget_accounting.html',
        'default_width': 6, 'default_height': 4, 'order': 34,
        'requires_permission': True, 'permission_code': 'accounting',
    },
    # ─── RH ──────────────────────────────────────────────────────────────────
    {
        'name': 'Congés à valider', 'code': 'hr_leave_requests_to_validate',
        'description': 'Demandes de congé en attente d\'approbation.',
        'module_code': 'hr', 'widget_type': 'workflow',
        'icon': 'bi-calendar-x', 'color': '#DB2777',
        'template_name': 'dashboard/partials/widget_validations.html',
        'default_width': 6, 'default_height': 4, 'order': 40,
        'requires_permission': True, 'permission_code': 'hr',
    },
    {
        'name': 'Notes de frais à valider', 'code': 'hr_expenses_to_validate',
        'description': 'Notes de frais soumises pour validation.',
        'module_code': 'hr', 'widget_type': 'workflow',
        'icon': 'bi-receipt', 'color': '#0891B2',
        'template_name': 'dashboard/partials/widget_validations.html',
        'default_width': 6, 'default_height': 4, 'order': 41,
        'requires_permission': True, 'permission_code': 'hr',
    },
    {
        'name': 'Documents salariés expirant bientôt', 'code': 'hr_expiring_documents',
        'description': 'Documents RH dont la validité expire dans 30 jours.',
        'module_code': 'hr', 'widget_type': 'list',
        'icon': 'bi-file-earmark-exclamation', 'color': '#F59E0B',
        'template_name': 'dashboard/partials/widget_documents.html',
        'default_width': 6, 'default_height': 4, 'order': 42,
        'requires_permission': True, 'permission_code': 'hr',
    },
    {
        'name': 'Mes documents privés', 'code': 'hr_my_private_documents',
        'description': 'Documents RH personnels visibles par le salarié.',
        'module_code': 'hr', 'widget_type': 'document',
        'icon': 'bi-person-vcard', 'color': '#6B7280',
        'template_name': 'dashboard/partials/widget_documents.html',
        'default_width': 6, 'default_height': 4, 'order': 43,
        'requires_permission': False,
    },
    # ─── E-commerce ───────────────────────────────────────────────────────────
    {
        'name': 'Commandes web à préparer', 'code': 'ecommerce_orders_to_prepare',
        'description': 'Commandes en ligne confirmées à traiter.',
        'module_code': 'ecommerce', 'widget_type': 'list',
        'icon': 'bi-bag-check', 'color': '#7C3AED',
        'template_name': 'dashboard/partials/widget_ecommerce.html',
        'default_width': 6, 'default_height': 4, 'order': 50,
        'requires_permission': True, 'permission_code': 'ecommerce',
    },
    {
        'name': 'Produits en rupture', 'code': 'inventory_low_stock_products',
        'description': 'Produits dont le stock est insuffisant.',
        'module_code': 'inventory', 'widget_type': 'list',
        'icon': 'bi-boxes', 'color': '#DC2626',
        'template_name': 'dashboard/partials/widget_ecommerce.html',
        'default_width': 6, 'default_height': 4, 'order': 51,
        'requires_permission': True, 'permission_code': 'inventory',
    },
    {
        'name': 'Retours clients', 'code': 'ecommerce_returns_pending',
        'description': 'Demandes de retour en attente de traitement.',
        'module_code': 'ecommerce', 'widget_type': 'list',
        'icon': 'bi-arrow-return-left', 'color': '#F59E0B',
        'template_name': 'dashboard/partials/widget_ecommerce.html',
        'default_width': 6, 'default_height': 4, 'order': 52,
        'requires_permission': True, 'permission_code': 'ecommerce',
    },
    {
        'name': 'CA boutique du jour', 'code': 'commerce_daily_sales',
        'description': 'Chiffre d\'affaires et transactions du jour.',
        'module_code': 'commerce', 'widget_type': 'kpi',
        'icon': 'bi-cash-register', 'color': '#10B981',
        'template_name': 'dashboard/partials/widget_ecommerce.html',
        'default_width': 4, 'default_height': 2, 'order': 53,
        'requires_permission': True, 'permission_code': 'commerce',
    },
    {
        'name': 'Click & collect à préparer', 'code': 'commerce_click_collect_pending',
        'description': 'Commandes click & collect à préparer.',
        'module_code': 'commerce', 'widget_type': 'list',
        'icon': 'bi-shop-window', 'color': '#0891B2',
        'template_name': 'dashboard/partials/widget_ecommerce.html',
        'default_width': 6, 'default_height': 4, 'order': 54,
        'requires_permission': True, 'permission_code': 'commerce',
    },
    # ─── Productivité personnelle ─────────────────────────────────────────────
    {
        'name': 'Actions rapides', 'code': 'quick_actions',
        'description': 'Boutons d\'accès rapide aux actions les plus fréquentes.',
        'module_code': '', 'widget_type': 'action',
        'icon': 'bi-lightning-charge', 'color': '#C6A15B',
        'template_name': 'dashboard/partials/widget_quick_actions.html',
        'default_width': 12, 'default_height': 2, 'order': 5,
        'requires_permission': False,
    },
    {
        'name': 'Mes favoris', 'code': 'user_favorites',
        'description': 'Raccourcis marqués comme favoris par l\'utilisateur.',
        'module_code': '', 'widget_type': 'shortcut',
        'icon': 'bi-star', 'color': '#F59E0B',
        'template_name': 'dashboard/partials/widget_user_favorites.html',
        'default_width': 6, 'default_height': 3, 'order': 6,
        'requires_permission': False,
    },
    {
        'name': 'À faire aujourd\'hui', 'code': 'today_todo',
        'description': 'Liste des actions prioritaires du jour.',
        'module_code': '', 'widget_type': 'task',
        'icon': 'bi-check2-circle', 'color': '#10B981',
        'template_name': 'dashboard/partials/widget_today_todo.html',
        'default_width': 6, 'default_height': 4, 'order': 7,
        'requires_permission': False,
    },
    {
        'name': 'Agenda semaine', 'code': 'weekly_agenda',
        'description': 'Événements et échéances des 7 prochains jours.',
        'module_code': '', 'widget_type': 'agenda',
        'icon': 'bi-calendar-week', 'color': '#0891B2',
        'template_name': 'dashboard/partials/widget_weekly_agenda.html',
        'default_width': 6, 'default_height': 4, 'order': 9,
        'requires_permission': False,
    },
    {
        'name': 'Notes personnelles', 'code': 'personal_notes',
        'description': 'Bloc-notes personnel — notes colorées et épinglées.',
        'module_code': '', 'widget_type': 'note',
        'icon': 'bi-sticky', 'color': '#FEF3C7',
        'template_name': 'dashboard/partials/widget_personal_notes.html',
        'default_width': 6, 'default_height': 4, 'order': 9,
        'requires_permission': False,
    },
    # ─── Alertes et priorités ─────────────────────────────────────────────────
    {
        'name': 'Alertes importantes', 'code': 'important_alerts',
        'description': 'Alertes critiques issues de tous les modules actifs.',
        'module_code': '', 'widget_type': 'alert',
        'icon': 'bi-exclamation-triangle', 'color': '#DC2626',
        'template_name': 'dashboard/partials/widget_important_alerts.html',
        'default_width': 12, 'default_height': 3, 'order': 1,
        'requires_permission': False,
    },
    {
        'name': 'Échéances à venir', 'code': 'upcoming_deadlines',
        'description': 'Devis et factures arrivant à échéance dans 14 jours.',
        'module_code': '', 'widget_type': 'alert',
        'icon': 'bi-alarm', 'color': '#F59E0B',
        'template_name': 'dashboard/partials/widget_upcoming_deadlines.html',
        'default_width': 6, 'default_height': 4, 'order': 2,
        'requires_permission': False,
    },
    {
        'name': 'Éléments en retard', 'code': 'late_items',
        'description': 'Chantiers, factures et tickets dépassant leurs délais.',
        'module_code': '', 'widget_type': 'alert',
        'icon': 'bi-clock-history', 'color': '#DC2626',
        'template_name': 'dashboard/partials/widget_late_items.html',
        'default_width': 6, 'default_height': 4, 'order': 3,
        'requires_permission': False,
    },
    # ─── BTP avancés ──────────────────────────────────────────────────────────
    {
        'name': 'Rentabilité chantiers', 'code': 'btp_project_profitability',
        'description': 'Budget vs dépenses réelles par chantier.',
        'module_code': 'btp', 'widget_type': 'finance',
        'icon': 'bi-graph-up-arrow', 'color': '#10B981',
        'template_name': 'dashboard/partials/widget_btp_project_profitability.html',
        'default_width': 8, 'default_height': 4, 'order': 16,
        'requires_permission': True, 'permission_code': 'btp',
    },
    {
        'name': 'Chantiers à risque', 'code': 'btp_risky_projects',
        'description': 'Chantiers en retard ou en dépassement budget.',
        'module_code': 'btp', 'widget_type': 'alert',
        'icon': 'bi-exclamation-diamond', 'color': '#DC2626',
        'template_name': 'dashboard/partials/widget_btp_risky_projects.html',
        'default_width': 6, 'default_height': 4, 'order': 17,
        'requires_permission': True, 'permission_code': 'btp',
    },
    {
        'name': 'Avancement chantiers', 'code': 'btp_projects_progress',
        'description': 'Barres de progression des chantiers en cours.',
        'module_code': 'btp', 'widget_type': 'progress',
        'icon': 'bi-bar-chart-steps', 'color': '#2563EB',
        'template_name': 'dashboard/partials/widget_btp_projects_progress.html',
        'default_width': 8, 'default_height': 4, 'order': 18,
        'requires_permission': True, 'permission_code': 'btp',
    },
    {
        'name': 'Demandes clients chantier', 'code': 'btp_client_requests',
        'description': 'Demandes en cours depuis le portail client ou site vitrine.',
        'module_code': 'btp', 'widget_type': 'list',
        'icon': 'bi-person-raised-hand', 'color': '#7C3AED',
        'template_name': 'dashboard/partials/widget_btp_client_requests.html',
        'default_width': 6, 'default_height': 4, 'order': 19,
        'requires_permission': True, 'permission_code': 'btp',
    },
    {
        'name': 'Photos de chantier récentes', 'code': 'btp_recent_site_photos',
        'description': 'Dernières photos ajoutées sur les chantiers actifs.',
        'module_code': 'btp', 'widget_type': 'photo',
        'icon': 'bi-camera', 'color': '#6B7280',
        'template_name': 'dashboard/partials/widget_btp_recent_site_photos.html',
        'default_width': 8, 'default_height': 3, 'order': 19,
        'requires_permission': True, 'permission_code': 'btp',
    },
    {
        'name': 'État du matériel', 'code': 'btp_equipment_status',
        'description': 'Disponibilité et état du matériel BTP.',
        'module_code': 'btp', 'widget_type': 'list',
        'icon': 'bi-tools', 'color': '#6B7280',
        'template_name': 'dashboard/partials/widget_btp_equipment_status.html',
        'default_width': 6, 'default_height': 4, 'order': 19,
        'requires_permission': True, 'permission_code': 'btp',
    },
    # ─── CRM / Ventes avancés ────────────────────────────────────────────────
    {
        'name': 'Pipeline commercial', 'code': 'crm_sales_pipeline',
        'description': 'Kanban visuel du pipeline de vente par étape.',
        'module_code': 'crm', 'widget_type': 'pipeline',
        'icon': 'bi-funnel', 'color': '#7C3AED',
        'template_name': 'dashboard/partials/widget_crm_sales_pipeline.html',
        'default_width': 12, 'default_height': 3, 'order': 22,
        'requires_permission': True, 'permission_code': 'crm',
    },
    {
        'name': 'Suivis prioritaires CRM', 'code': 'crm_priority_followups',
        'description': 'Prospects dont l\'action de suivi est en retard.',
        'module_code': 'crm', 'widget_type': 'list',
        'icon': 'bi-person-exclamation', 'color': '#DC2626',
        'template_name': 'dashboard/partials/widget_crm_priority_followups.html',
        'default_width': 6, 'default_height': 4, 'order': 23,
        'requires_permission': True, 'permission_code': 'crm',
    },
    {
        'name': 'Devis expirant bientôt', 'code': 'sales_quotes_expiring_soon',
        'description': 'Devis envoyés dont la validité expire dans 7 jours.',
        'module_code': 'sales', 'widget_type': 'alert',
        'icon': 'bi-file-earmark-exclamation', 'color': '#F59E0B',
        'template_name': 'dashboard/partials/widget_sales_quotes_expiring_soon.html',
        'default_width': 6, 'default_height': 4, 'order': 25,
        'requires_permission': True, 'permission_code': 'sales',
    },
    {
        'name': 'Top clients', 'code': 'crm_top_customers',
        'description': 'Meilleurs clients par CA annuel.',
        'module_code': 'crm', 'widget_type': 'list',
        'icon': 'bi-award', 'color': '#C6A15B',
        'template_name': 'dashboard/partials/widget_crm_top_customers.html',
        'default_width': 6, 'default_height': 4, 'order': 26,
        'requires_permission': True, 'permission_code': 'crm',
    },
    # ─── Comptabilité / Trésorerie avancés ───────────────────────────────────
    {
        'name': 'Soldes bancaires', 'code': 'accounting_bank_balances',
        'description': 'Solde de chaque compte bancaire en temps réel.',
        'module_code': 'accounting', 'widget_type': 'finance',
        'icon': 'bi-bank2', 'color': '#10B981',
        'template_name': 'dashboard/partials/widget_accounting_bank_balances.html',
        'default_width': 6, 'default_height': 3, 'order': 35,
        'requires_permission': True, 'permission_code': 'accounting',
    },
    {
        'name': 'Prévision trésorerie 30j', 'code': 'accounting_cashflow_forecast',
        'description': 'Encaissements et décaissements prévisionnels à 30 jours.',
        'module_code': 'accounting', 'widget_type': 'chart',
        'icon': 'bi-graph-up', 'color': '#2563EB',
        'template_name': 'dashboard/partials/widget_accounting_cashflow_forecast.html',
        'default_width': 8, 'default_height': 4, 'order': 36,
        'requires_permission': True, 'permission_code': 'accounting',
    },
    {
        'name': 'Relances factures', 'code': 'accounting_invoice_reminders',
        'description': 'Factures en retard nécessitant une relance client.',
        'module_code': 'accounting', 'widget_type': 'list',
        'icon': 'bi-send-exclamation', 'color': '#DC2626',
        'template_name': 'dashboard/partials/widget_accounting_invoice_reminders.html',
        'default_width': 6, 'default_height': 4, 'order': 37,
        'requires_permission': True, 'permission_code': 'accounting',
    },
    {
        'name': 'Frais à rembourser', 'code': 'accounting_expenses_to_reimburse',
        'description': 'Notes de frais approuvées non encore remboursées.',
        'module_code': 'accounting', 'widget_type': 'list',
        'icon': 'bi-wallet2', 'color': '#7C3AED',
        'template_name': 'dashboard/partials/widget_accounting_expenses_to_reimburse.html',
        'default_width': 6, 'default_height': 4, 'order': 38,
        'requires_permission': True, 'permission_code': 'accounting',
    },
    {
        'name': 'TVA à déclarer', 'code': 'accounting_vat_to_declare',
        'description': 'TVA collectée et déductible du mois en cours.',
        'module_code': 'accounting', 'widget_type': 'kpi',
        'icon': 'bi-percent', 'color': '#0D9488',
        'template_name': 'dashboard/partials/widget_accounting_vat_to_declare.html',
        'default_width': 4, 'default_height': 2, 'order': 39,
        'requires_permission': True, 'permission_code': 'accounting',
    },
    # ─── Documents avancés ────────────────────────────────────────────────────
    {
        'name': 'Documents à signer', 'code': 'documents_to_sign',
        'description': 'Documents en attente de signature électronique.',
        'module_code': 'documents', 'widget_type': 'workflow',
        'icon': 'bi-pen', 'color': '#7C3AED',
        'template_name': 'dashboard/partials/widget_documents_to_sign.html',
        'default_width': 6, 'default_height': 4, 'order': 44,
        'requires_permission': True, 'permission_code': 'documents',
    },
    {
        'name': 'Documents expirant bientôt', 'code': 'documents_expiring_soon',
        'description': 'Documents (habilitations, certifications) expirant dans 60 jours.',
        'module_code': 'documents', 'widget_type': 'alert',
        'icon': 'bi-file-earmark-x', 'color': '#F59E0B',
        'template_name': 'dashboard/partials/widget_documents_expiring_soon.html',
        'default_width': 6, 'default_height': 4, 'order': 45,
        'requires_permission': True, 'permission_code': 'documents',
    },
    {
        'name': 'Documents partagés récemment', 'code': 'documents_recently_shared',
        'description': 'Derniers documents ajoutés ou partagés.',
        'module_code': 'documents', 'widget_type': 'document',
        'icon': 'bi-folder-symlink', 'color': '#0891B2',
        'template_name': 'dashboard/partials/widget_documents_recently_shared.html',
        'default_width': 6, 'default_height': 4, 'order': 46,
        'requires_permission': True, 'permission_code': 'documents',
    },
    # ─── RH avancés ───────────────────────────────────────────────────────────
    {
        'name': 'Absences du jour', 'code': 'hr_today_absences',
        'description': 'Employés absents aujourd\'hui (congés, RTT…).',
        'module_code': 'hr', 'widget_type': 'hr',
        'icon': 'bi-person-slash', 'color': '#DB2777',
        'template_name': 'dashboard/partials/widget_hr_today_absences.html',
        'default_width': 6, 'default_height': 3, 'order': 44,
        'requires_permission': True, 'permission_code': 'hr',
    },
    {
        'name': 'Dates RH importantes', 'code': 'hr_important_dates',
        'description': 'Fins de période d\'essai, anniversaires et jalons RH.',
        'module_code': 'hr', 'widget_type': 'hr',
        'icon': 'bi-calendar-heart', 'color': '#DB2777',
        'template_name': 'dashboard/partials/widget_hr_important_dates.html',
        'default_width': 6, 'default_height': 4, 'order': 45,
        'requires_permission': True, 'permission_code': 'hr',
    },
    {
        'name': 'Mes heures', 'code': 'hr_my_hours',
        'description': 'Heures déclarées cette semaine et pointages en attente.',
        'module_code': 'hr', 'widget_type': 'kpi',
        'icon': 'bi-stopwatch', 'color': '#0891B2',
        'template_name': 'dashboard/partials/widget_hr_my_hours.html',
        'default_width': 4, 'default_height': 2, 'order': 46,
        'requires_permission': False,
    },
    # ─── Support et portail ───────────────────────────────────────────────────
    {
        'name': 'Tickets urgents', 'code': 'support_urgent_tickets',
        'description': 'Tickets support haute priorité en attente de réponse.',
        'module_code': 'support', 'widget_type': 'support',
        'icon': 'bi-headset', 'color': '#DC2626',
        'template_name': 'dashboard/partials/widget_support_urgent_tickets.html',
        'default_width': 6, 'default_height': 4, 'order': 60,
        'requires_permission': True, 'permission_code': 'support',
    },
    {
        'name': 'Messages clients non lus', 'code': 'client_unread_messages',
        'description': 'Messages reçus depuis le portail client non encore lus.',
        'module_code': 'portails', 'widget_type': 'message',
        'icon': 'bi-chat-left-dots', 'color': '#2563EB',
        'template_name': 'dashboard/partials/widget_client_unread_messages.html',
        'default_width': 6, 'default_height': 4, 'order': 61,
        'requires_permission': True, 'permission_code': 'portails',
    },
    {
        'name': 'Activité portail client', 'code': 'client_portal_activity',
        'description': 'Dernières actions sur le portail client.',
        'module_code': 'portails', 'widget_type': 'list',
        'icon': 'bi-globe2', 'color': '#0891B2',
        'template_name': 'dashboard/partials/widget_client_portal_activity.html',
        'default_width': 6, 'default_height': 4, 'order': 62,
        'requires_permission': True, 'permission_code': 'portails',
    },
    # ─── Sites web ────────────────────────────────────────────────────────────
    {
        'name': 'Leads site web', 'code': 'website_leads',
        'description': 'Formulaires de contact non traités sur le site vitrine.',
        'module_code': 'websites', 'widget_type': 'list',
        'icon': 'bi-person-lines-fill', 'color': '#10B981',
        'template_name': 'dashboard/partials/widget_website_leads.html',
        'default_width': 6, 'default_height': 4, 'order': 70,
        'requires_permission': True, 'permission_code': 'websites',
    },
    {
        'name': 'Pages à publier', 'code': 'website_pages_to_publish',
        'description': 'Pages web en brouillon à valider et publier.',
        'module_code': 'websites', 'widget_type': 'list',
        'icon': 'bi-file-earmark-richtext', 'color': '#7C3AED',
        'template_name': 'dashboard/partials/widget_website_pages_to_publish.html',
        'default_width': 6, 'default_height': 4, 'order': 71,
        'requires_permission': True, 'permission_code': 'websites',
    },
    {
        'name': 'Stats site web', 'code': 'website_basic_stats',
        'description': 'Statistiques de base du site vitrine (leads, pages…).',
        'module_code': 'websites', 'widget_type': 'kpi',
        'icon': 'bi-bar-chart', 'color': '#0891B2',
        'template_name': 'dashboard/partials/widget_website_basic_stats.html',
        'default_width': 4, 'default_height': 2, 'order': 72,
        'requires_permission': True, 'permission_code': 'websites',
    },
    # ─── E-commerce et commerce avancés ──────────────────────────────────────
    {
        'name': 'Commandes urgentes e-commerce', 'code': 'ecommerce_urgent_orders',
        'description': 'Commandes confirmées à préparer en priorité.',
        'module_code': 'ecommerce', 'widget_type': 'list',
        'icon': 'bi-bag-heart', 'color': '#DC2626',
        'template_name': 'dashboard/partials/widget_ecommerce_urgent_orders.html',
        'default_width': 6, 'default_height': 4, 'order': 55,
        'requires_permission': True, 'permission_code': 'ecommerce',
    },
    {
        'name': 'Paniers abandonnés', 'code': 'ecommerce_abandoned_carts',
        'description': 'Visiteurs ayant ajouté des produits sans finaliser.',
        'module_code': 'ecommerce', 'widget_type': 'list',
        'icon': 'bi-cart-x', 'color': '#F59E0B',
        'template_name': 'dashboard/partials/widget_ecommerce_abandoned_carts.html',
        'default_width': 6, 'default_height': 4, 'order': 56,
        'requires_permission': True, 'permission_code': 'ecommerce',
    },
    {
        'name': 'Produits à réapprovisionner', 'code': 'inventory_products_to_reorder',
        'description': 'Produits dont le stock est sous le seuil minimum.',
        'module_code': 'inventory', 'widget_type': 'list',
        'icon': 'bi-boxes', 'color': '#F59E0B',
        'template_name': 'dashboard/partials/widget_inventory_products_to_reorder.html',
        'default_width': 6, 'default_height': 4, 'order': 57,
        'requires_permission': True, 'permission_code': 'inventory',
    },
    {
        'name': 'Ventes omnicanal', 'code': 'commerce_omnichannel_sales',
        'description': 'CA par canal : POS, web, B2B.',
        'module_code': 'commerce', 'widget_type': 'chart',
        'icon': 'bi-diagram-3', 'color': '#10B981',
        'template_name': 'dashboard/partials/widget_commerce_omnichannel_sales.html',
        'default_width': 6, 'default_height': 3, 'order': 58,
        'requires_permission': True, 'permission_code': 'commerce',
    },
    # ─── LUNEA — E-commerce Maquillage ───────────────────────────────────────
    {
        'name': 'LUNEA — Nouvelles commandes', 'code': 'lunea_new_orders',
        'description': 'Commandes LUNEA reçues aujourd\'hui.',
        'module_code': 'lunea', 'widget_type': 'list',
        'icon': 'bi-bag-heart', 'color': '#C4936A',
        'template_name': 'dashboard/partials/widget_lunea.html',
        'default_width': 6, 'default_height': 4, 'order': 80,
        'requires_permission': True, 'permission_code': 'lunea',
    },
    {
        'name': 'LUNEA — Commandes à préparer', 'code': 'lunea_orders_to_prepare',
        'description': 'Commandes LUNEA payées en attente de préparation.',
        'module_code': 'lunea', 'widget_type': 'list',
        'icon': 'bi-box-seam', 'color': '#DC2626',
        'template_name': 'dashboard/partials/widget_lunea.html',
        'default_width': 6, 'default_height': 4, 'order': 81,
        'requires_permission': True, 'permission_code': 'lunea',
    },
    {
        'name': 'LUNEA — Stock teintes faible', 'code': 'lunea_low_shade_stock',
        'description': 'Teintes avec un stock inférieur au seuil minimum.',
        'module_code': 'lunea', 'widget_type': 'list',
        'icon': 'bi-palette', 'color': '#F59E0B',
        'template_name': 'dashboard/partials/widget_lunea.html',
        'default_width': 6, 'default_height': 4, 'order': 82,
        'requires_permission': True, 'permission_code': 'lunea',
    },
    {
        'name': 'LUNEA — Meilleures ventes', 'code': 'lunea_best_sellers',
        'description': 'Produits best-sellers LUNEA.',
        'module_code': 'lunea', 'widget_type': 'list',
        'icon': 'bi-star-fill', 'color': '#C4936A',
        'template_name': 'dashboard/partials/widget_lunea.html',
        'default_width': 6, 'default_height': 4, 'order': 83,
        'requires_permission': True, 'permission_code': 'lunea',
    },
    {
        'name': 'LUNEA — Avis à modérer', 'code': 'lunea_pending_reviews',
        'description': 'Avis clients LUNEA en attente de modération.',
        'module_code': 'lunea', 'widget_type': 'workflow',
        'icon': 'bi-chat-square-text', 'color': '#7C3AED',
        'template_name': 'dashboard/partials/widget_lunea.html',
        'default_width': 6, 'default_height': 4, 'order': 84,
        'requires_permission': True, 'permission_code': 'lunea',
    },
    {
        'name': 'LUNEA — CA du jour', 'code': 'lunea_revenue_today',
        'description': 'Chiffre d\'affaires LUNEA réalisé aujourd\'hui.',
        'module_code': 'lunea', 'widget_type': 'kpi',
        'icon': 'bi-cash-stack', 'color': '#10B981',
        'template_name': 'dashboard/partials/widget_lunea.html',
        'default_width': 4, 'default_height': 2, 'order': 85,
        'requires_permission': True, 'permission_code': 'lunea',
    },
    {
        'name': 'LUNEA — Alertes stock teintes', 'code': 'lunea_shade_alerts',
        'description': 'Alertes de réapprovisionnement de teintes LUNEA.',
        'module_code': 'lunea', 'widget_type': 'alert',
        'icon': 'bi-exclamation-diamond', 'color': '#DC2626',
        'template_name': 'dashboard/partials/widget_lunea.html',
        'default_width': 6, 'default_height': 3, 'order': 86,
        'requires_permission': True, 'permission_code': 'lunea',
    },
    {
        'name': 'LUNEA — Cartes-cadeaux actives', 'code': 'lunea_gift_cards_active',
        'description': 'Solde total des cartes-cadeaux LUNEA actives.',
        'module_code': 'lunea', 'widget_type': 'kpi',
        'icon': 'bi-gift', 'color': '#C4936A',
        'template_name': 'dashboard/partials/widget_lunea.html',
        'default_width': 4, 'default_height': 2, 'order': 87,
        'requires_permission': True, 'permission_code': 'lunea',
    },
    {
        'name': 'LUNEA — Points fidélité émis', 'code': 'lunea_loyalty_points_issued',
        'description': 'Points fidélité LUNEA émis aujourd\'hui.',
        'module_code': 'lunea', 'widget_type': 'kpi',
        'icon': 'bi-gem', 'color': '#7C3AED',
        'template_name': 'dashboard/partials/widget_lunea.html',
        'default_width': 4, 'default_height': 2, 'order': 88,
        'requires_permission': True, 'permission_code': 'lunea',
    },
    {
        'name': 'LUNEA — Abonnées newsletter', 'code': 'lunea_newsletter_subscribers',
        'description': 'Nombre total d\'abonnées à la newsletter LUNEA.',
        'module_code': 'lunea', 'widget_type': 'kpi',
        'icon': 'bi-envelope-heart', 'color': '#C4936A',
        'template_name': 'dashboard/partials/widget_lunea.html',
        'default_width': 4, 'default_height': 2, 'order': 89,
        'requires_permission': True, 'permission_code': 'lunea',
    },
    {
        'name': 'LUNEA — Renouvellements abonnements', 'code': 'lunea_subscription_renewals',
        'description': 'Abonnements beauté LUNEA à renouveler dans les 7 jours.',
        'module_code': 'lunea', 'widget_type': 'list',
        'icon': 'bi-arrow-repeat', 'color': '#0891B2',
        'template_name': 'dashboard/partials/widget_lunea.html',
        'default_width': 6, 'default_height': 3, 'order': 90,
        'requires_permission': True, 'permission_code': 'lunea',
    },
    {
        'name': 'LUNEA — Paniers abandonnés', 'code': 'lunea_abandoned_carts',
        'description': 'Paniers LUNEA abandonnés à relancer.',
        'module_code': 'lunea', 'widget_type': 'kpi',
        'icon': 'bi-cart-x', 'color': '#F59E0B',
        'template_name': 'dashboard/partials/widget_lunea.html',
        'default_width': 4, 'default_height': 2, 'order': 91,
        'requires_permission': True, 'permission_code': 'lunea',
    },
    {
        'name': 'LUNEA — Taux de conversion', 'code': 'lunea_conversion_rate',
        'description': 'Taux de conversion de la boutique LUNEA.',
        'module_code': 'lunea', 'widget_type': 'kpi',
        'icon': 'bi-graph-up-arrow', 'color': '#10B981',
        'template_name': 'dashboard/partials/widget_lunea.html',
        'default_width': 4, 'default_height': 2, 'order': 92,
        'requires_permission': True, 'permission_code': 'lunea',
    },
    {
        'name': 'LUNEA — Quiz beauté complétés', 'code': 'lunea_beauty_quiz_completions',
        'description': 'Quiz beauté complétés cette semaine.',
        'module_code': 'lunea', 'widget_type': 'kpi',
        'icon': 'bi-question-circle', 'color': '#C4936A',
        'template_name': 'dashboard/partials/widget_lunea.html',
        'default_width': 4, 'default_height': 2, 'order': 93,
        'requires_permission': True, 'permission_code': 'lunea',
    },
    {
        'name': 'LUNEA — Échantillons envoyés', 'code': 'lunea_samples_sent',
        'description': 'Échantillons LUNEA envoyés cette semaine.',
        'module_code': 'lunea', 'widget_type': 'kpi',
        'icon': 'bi-droplet', 'color': '#C4936A',
        'template_name': 'dashboard/partials/widget_lunea.html',
        'default_width': 4, 'default_height': 2, 'order': 94,
        'requires_permission': True, 'permission_code': 'lunea',
    },
    # ─── Backups ──────────────────────────────────────────────────────────────
    {
        'name': 'Dernière sauvegarde', 'code': 'backups_last_status',
        'description': 'Statut de la dernière sauvegarde système.',
        'module_code': 'backups', 'widget_type': 'status',
        'icon': 'bi-cloud-check', 'color': '#10B981',
        'template_name': 'dashboard/partials/widget_backups.html',
        'default_width': 6, 'default_height': 2, 'order': 100,
        'requires_permission': True, 'permission_code': 'backups',
    },
    {
        'name': 'Sauvegardes en attente', 'code': 'backups_pending',
        'description': 'Sauvegardes planifiées en attente d\'exécution.',
        'module_code': 'backups', 'widget_type': 'kpi',
        'icon': 'bi-clock', 'color': '#F59E0B',
        'template_name': 'dashboard/partials/widget_backups.html',
        'default_width': 4, 'default_height': 2, 'order': 101,
        'requires_permission': True, 'permission_code': 'backups',
    },
    {
        'name': 'Sauvegardes échouées', 'code': 'backups_failed',
        'description': 'Sauvegardes en échec à résoudre.',
        'module_code': 'backups', 'widget_type': 'alert',
        'icon': 'bi-cloud-slash', 'color': '#DC2626',
        'template_name': 'dashboard/partials/widget_backups.html',
        'default_width': 6, 'default_height': 3, 'order': 102,
        'requires_permission': True, 'permission_code': 'backups',
    },
    {
        'name': 'Espace stockage sauvegardes', 'code': 'backups_size_used',
        'description': 'Espace disque utilisé par les sauvegardes.',
        'module_code': 'backups', 'widget_type': 'kpi',
        'icon': 'bi-hdd', 'color': '#6B7280',
        'template_name': 'dashboard/partials/widget_backups.html',
        'default_width': 4, 'default_height': 2, 'order': 103,
        'requires_permission': True, 'permission_code': 'backups',
    },
    {
        'name': 'Prochaine sauvegarde', 'code': 'backups_scheduled',
        'description': 'Date et heure de la prochaine sauvegarde planifiée.',
        'module_code': 'backups', 'widget_type': 'kpi',
        'icon': 'bi-calendar-check', 'color': '#0891B2',
        'template_name': 'dashboard/partials/widget_backups.html',
        'default_width': 4, 'default_height': 2, 'order': 104,
        'requires_permission': True, 'permission_code': 'backups',
    },
    {
        'name': 'Dernières restaurations', 'code': 'backups_recent_restores',
        'description': 'Restaurations récentes effectuées.',
        'module_code': 'backups', 'widget_type': 'list',
        'icon': 'bi-arrow-counterclockwise', 'color': '#7C3AED',
        'template_name': 'dashboard/partials/widget_backups.html',
        'default_width': 6, 'default_height': 3, 'order': 105,
        'requires_permission': True, 'permission_code': 'backups',
    },
    # ─── Competitor Intelligence ──────────────────────────────────────────────
    {
        'name': 'Alertes prix concurrents', 'code': 'competitor_price_alerts',
        'description': 'Changements de prix détectés chez la concurrence.',
        'module_code': 'competitor', 'widget_type': 'alert',
        'icon': 'bi-tag', 'color': '#DC2626',
        'template_name': 'dashboard/partials/widget_competitor.html',
        'default_width': 6, 'default_height': 4, 'order': 110,
        'requires_permission': True, 'permission_code': 'competitor',
    },
    {
        'name': 'Nouveaux produits concurrents', 'code': 'competitor_new_products',
        'description': 'Nouveaux produits détectés chez la concurrence.',
        'module_code': 'competitor', 'widget_type': 'list',
        'icon': 'bi-box-arrow-in-right', 'color': '#F59E0B',
        'template_name': 'dashboard/partials/widget_competitor.html',
        'default_width': 6, 'default_height': 4, 'order': 111,
        'requires_permission': True, 'permission_code': 'competitor',
    },
    {
        'name': 'Mentions sociales concurrents', 'code': 'competitor_social_mentions',
        'description': 'Mentions des concurrents sur les réseaux sociaux.',
        'module_code': 'competitor', 'widget_type': 'list',
        'icon': 'bi-megaphone', 'color': '#0891B2',
        'template_name': 'dashboard/partials/widget_competitor.html',
        'default_width': 6, 'default_height': 4, 'order': 112,
        'requires_permission': True, 'permission_code': 'competitor',
    },
    {
        'name': 'Évolution positions SEO', 'code': 'competitor_ranking_changes',
        'description': 'Changements de positionnement SEO vs concurrents.',
        'module_code': 'competitor', 'widget_type': 'chart',
        'icon': 'bi-bar-chart-line', 'color': '#10B981',
        'template_name': 'dashboard/partials/widget_competitor.html',
        'default_width': 6, 'default_height': 3, 'order': 113,
        'requires_permission': True, 'permission_code': 'competitor',
    },
    {
        'name': 'Promotions concurrents', 'code': 'competitor_promo_alerts',
        'description': 'Promotions et offres détectées chez les concurrents.',
        'module_code': 'competitor', 'widget_type': 'alert',
        'icon': 'bi-percent', 'color': '#7C3AED',
        'template_name': 'dashboard/partials/widget_competitor.html',
        'default_width': 6, 'default_height': 3, 'order': 114,
        'requires_permission': True, 'permission_code': 'competitor',
    },
    {
        'name': 'Avis concurrents', 'code': 'competitor_reviews_summary',
        'description': 'Synthèse des avis clients sur les concurrents.',
        'module_code': 'competitor', 'widget_type': 'summary',
        'icon': 'bi-star-half', 'color': '#C6A15B',
        'template_name': 'dashboard/partials/widget_competitor.html',
        'default_width': 6, 'default_height': 3, 'order': 115,
        'requires_permission': True, 'permission_code': 'competitor',
    },
    {
        'name': 'Tendances trafic concurrents', 'code': 'competitor_traffic_trends',
        'description': 'Tendances de trafic web des concurrents.',
        'module_code': 'competitor', 'widget_type': 'chart',
        'icon': 'bi-graph-up', 'color': '#0891B2',
        'template_name': 'dashboard/partials/widget_competitor.html',
        'default_width': 8, 'default_height': 3, 'order': 116,
        'requires_permission': True, 'permission_code': 'competitor',
    },
    {
        'name': 'Publicités concurrents', 'code': 'competitor_ad_intelligence',
        'description': 'Veille publicitaire sur les concurrents (Google, Meta…).',
        'module_code': 'competitor', 'widget_type': 'list',
        'icon': 'bi-display', 'color': '#2563EB',
        'template_name': 'dashboard/partials/widget_competitor.html',
        'default_width': 6, 'default_height': 4, 'order': 117,
        'requires_permission': True, 'permission_code': 'competitor',
    },
    {
        'name': 'Actualités concurrents', 'code': 'competitor_news',
        'description': 'Dernières actualités liées aux concurrents.',
        'module_code': 'competitor', 'widget_type': 'list',
        'icon': 'bi-newspaper', 'color': '#6B7280',
        'template_name': 'dashboard/partials/widget_competitor.html',
        'default_width': 6, 'default_height': 4, 'order': 118,
        'requires_permission': True, 'permission_code': 'competitor',
    },
    # ─── Cloudflare ───────────────────────────────────────────────────────────
    {
        'name': 'Zones Cloudflare', 'code': 'cloudflare_zones_status',
        'description': 'Statut des zones Cloudflare configurées.',
        'module_code': 'cloudflare', 'widget_type': 'status',
        'icon': 'bi-cloud-fill', 'color': '#F59E0B',
        'template_name': 'dashboard/partials/widget_cloudflare.html',
        'default_width': 6, 'default_height': 3, 'order': 120,
        'requires_permission': True, 'permission_code': 'cloudflare',
    },
    {
        'name': 'Événements pare-feu Cloudflare', 'code': 'cloudflare_firewall_events',
        'description': 'Événements de sécurité bloqués par Cloudflare.',
        'module_code': 'cloudflare', 'widget_type': 'alert',
        'icon': 'bi-shield-fill-exclamation', 'color': '#DC2626',
        'template_name': 'dashboard/partials/widget_cloudflare.html',
        'default_width': 6, 'default_height': 4, 'order': 121,
        'requires_permission': True, 'permission_code': 'cloudflare',
    },
    {
        'name': 'Trafic Cloudflare', 'code': 'cloudflare_traffic_stats',
        'description': 'Statistiques de trafic via Cloudflare.',
        'module_code': 'cloudflare', 'widget_type': 'kpi',
        'icon': 'bi-speedometer2', 'color': '#F59E0B',
        'template_name': 'dashboard/partials/widget_cloudflare.html',
        'default_width': 4, 'default_height': 2, 'order': 122,
        'requires_permission': True, 'permission_code': 'cloudflare',
    },
    {
        'name': 'SSL Cloudflare', 'code': 'cloudflare_ssl_status',
        'description': 'Statut des certificats SSL gérés par Cloudflare.',
        'module_code': 'cloudflare', 'widget_type': 'status',
        'icon': 'bi-lock-fill', 'color': '#10B981',
        'template_name': 'dashboard/partials/widget_cloudflare.html',
        'default_width': 6, 'default_height': 3, 'order': 123,
        'requires_permission': True, 'permission_code': 'cloudflare',
    },
    {
        'name': 'Règles de page Cloudflare', 'code': 'cloudflare_page_rules',
        'description': 'Règles de page actives sur Cloudflare.',
        'module_code': 'cloudflare', 'widget_type': 'list',
        'icon': 'bi-signpost-split', 'color': '#6B7280',
        'template_name': 'dashboard/partials/widget_cloudflare.html',
        'default_width': 6, 'default_height': 3, 'order': 124,
        'requires_permission': True, 'permission_code': 'cloudflare',
    },
    {
        'name': 'Analytics Cloudflare', 'code': 'cloudflare_analytics',
        'description': 'Résumé des analytics Cloudflare (visiteurs, pages vues).',
        'module_code': 'cloudflare', 'widget_type': 'kpi',
        'icon': 'bi-bar-chart-fill', 'color': '#0891B2',
        'template_name': 'dashboard/partials/widget_cloudflare.html',
        'default_width': 4, 'default_height': 2, 'order': 125,
        'requires_permission': True, 'permission_code': 'cloudflare',
    },
    # ─── Domaines ─────────────────────────────────────────────────────────────
    {
        'name': 'Domaines expirant bientôt', 'code': 'domains_expiring',
        'description': 'Noms de domaine à renouveler prochainement.',
        'module_code': 'domains', 'widget_type': 'alert',
        'icon': 'bi-globe', 'color': '#DC2626',
        'template_name': 'dashboard/partials/widget_domains.html',
        'default_width': 6, 'default_height': 4, 'order': 130,
        'requires_permission': True, 'permission_code': 'domains',
    },
    {
        'name': 'Santé DNS', 'code': 'domains_dns_health',
        'description': 'Vérification de la santé DNS des domaines.',
        'module_code': 'domains', 'widget_type': 'status',
        'icon': 'bi-diagram-2', 'color': '#10B981',
        'template_name': 'dashboard/partials/widget_domains.html',
        'default_width': 6, 'default_height': 3, 'order': 131,
        'requires_permission': True, 'permission_code': 'domains',
    },
    {
        'name': 'WHOIS domaines', 'code': 'domains_whois_summary',
        'description': 'Synthèse des informations WHOIS des domaines.',
        'module_code': 'domains', 'widget_type': 'list',
        'icon': 'bi-info-circle', 'color': '#6B7280',
        'template_name': 'dashboard/partials/widget_domains.html',
        'default_width': 6, 'default_height': 4, 'order': 132,
        'requires_permission': True, 'permission_code': 'domains',
    },
    {
        'name': 'Expiration SSL domaines', 'code': 'domains_ssl_expiry',
        'description': 'Certificats SSL proches de l\'expiration.',
        'module_code': 'domains', 'widget_type': 'alert',
        'icon': 'bi-shield-lock', 'color': '#F59E0B',
        'template_name': 'dashboard/partials/widget_domains.html',
        'default_width': 6, 'default_height': 3, 'order': 133,
        'requires_permission': True, 'permission_code': 'domains',
    },
    {
        'name': 'Redirections domaines', 'code': 'domains_redirect_status',
        'description': 'Statut des redirections configurées sur les domaines.',
        'module_code': 'domains', 'widget_type': 'status',
        'icon': 'bi-arrow-left-right', 'color': '#0891B2',
        'template_name': 'dashboard/partials/widget_domains.html',
        'default_width': 6, 'default_height': 3, 'order': 134,
        'requires_permission': True, 'permission_code': 'domains',
    },
    # ─── SaaS Privé ───────────────────────────────────────────────────────────
    {
        'name': 'Services SaaS — Statut', 'code': 'private_saas_services_status',
        'description': 'Statut de fonctionnement des services SaaS privés.',
        'module_code': 'private_saas', 'widget_type': 'status',
        'icon': 'bi-server', 'color': '#10B981',
        'template_name': 'dashboard/partials/widget_private_saas.html',
        'default_width': 8, 'default_height': 3, 'order': 140,
        'requires_permission': True, 'permission_code': 'private_saas',
    },
    {
        'name': 'Utilisateurs SaaS actifs', 'code': 'private_saas_users_count',
        'description': 'Nombre d\'utilisateurs actifs sur les SaaS privés.',
        'module_code': 'private_saas', 'widget_type': 'kpi',
        'icon': 'bi-people', 'color': '#2563EB',
        'template_name': 'dashboard/partials/widget_private_saas.html',
        'default_width': 4, 'default_height': 2, 'order': 141,
        'requires_permission': True, 'permission_code': 'private_saas',
    },
    {
        'name': 'Stockage SaaS utilisé', 'code': 'private_saas_storage_usage',
        'description': 'Espace de stockage utilisé par les SaaS privés.',
        'module_code': 'private_saas', 'widget_type': 'kpi',
        'icon': 'bi-hdd-stack', 'color': '#6B7280',
        'template_name': 'dashboard/partials/widget_private_saas.html',
        'default_width': 4, 'default_height': 2, 'order': 142,
        'requires_permission': True, 'permission_code': 'private_saas',
    },
    {
        'name': 'Mises à jour SaaS en attente', 'code': 'private_saas_pending_updates',
        'description': 'Mises à jour disponibles pour les SaaS privés.',
        'module_code': 'private_saas', 'widget_type': 'alert',
        'icon': 'bi-arrow-up-circle', 'color': '#F59E0B',
        'template_name': 'dashboard/partials/widget_private_saas.html',
        'default_width': 6, 'default_height': 3, 'order': 143,
        'requires_permission': True, 'permission_code': 'private_saas',
    },
    {
        'name': 'Incidents SaaS ouverts', 'code': 'private_saas_incidents',
        'description': 'Incidents ouverts sur les SaaS privés.',
        'module_code': 'private_saas', 'widget_type': 'alert',
        'icon': 'bi-bug', 'color': '#DC2626',
        'template_name': 'dashboard/partials/widget_private_saas.html',
        'default_width': 6, 'default_height': 4, 'order': 144,
        'requires_permission': True, 'permission_code': 'private_saas',
    },
    {
        'name': 'Sauvegardes SaaS', 'code': 'private_saas_backups',
        'description': 'Statut des sauvegardes des SaaS privés.',
        'module_code': 'private_saas', 'widget_type': 'status',
        'icon': 'bi-cloud-arrow-up', 'color': '#0891B2',
        'template_name': 'dashboard/partials/widget_private_saas.html',
        'default_width': 6, 'default_height': 3, 'order': 145,
        'requires_permission': True, 'permission_code': 'private_saas',
    },
    # ─── Fidélité ─────────────────────────────────────────────────────────────
    {
        'name': 'Points fidélité émis', 'code': 'loyalty_points_issued',
        'description': 'Points fidélité émis cette semaine.',
        'module_code': 'loyalty', 'widget_type': 'kpi',
        'icon': 'bi-gem', 'color': '#7C3AED',
        'template_name': 'dashboard/partials/widget_loyalty.html',
        'default_width': 4, 'default_height': 2, 'order': 150,
        'requires_permission': True, 'permission_code': 'loyalty',
    },
    {
        'name': 'Membres fidélité actifs', 'code': 'loyalty_members_active',
        'description': 'Nombre de membres actifs dans le programme de fidélité.',
        'module_code': 'loyalty', 'widget_type': 'kpi',
        'icon': 'bi-person-heart', 'color': '#C4936A',
        'template_name': 'dashboard/partials/widget_loyalty.html',
        'default_width': 4, 'default_height': 2, 'order': 151,
        'requires_permission': True, 'permission_code': 'loyalty',
    },
    {
        'name': 'Rédemptions fidélité récentes', 'code': 'loyalty_redemptions',
        'description': 'Rédemptions de points fidélité récentes.',
        'module_code': 'loyalty', 'widget_type': 'list',
        'icon': 'bi-gift', 'color': '#C4936A',
        'template_name': 'dashboard/partials/widget_loyalty.html',
        'default_width': 6, 'default_height': 4, 'order': 152,
        'requires_permission': True, 'permission_code': 'loyalty',
    },
    {
        'name': 'Répartition par palier', 'code': 'loyalty_tier_distribution',
        'description': 'Distribution des membres par palier de fidélité.',
        'module_code': 'loyalty', 'widget_type': 'chart',
        'icon': 'bi-bar-chart-steps', 'color': '#7C3AED',
        'template_name': 'dashboard/partials/widget_loyalty.html',
        'default_width': 6, 'default_height': 3, 'order': 153,
        'requires_permission': True, 'permission_code': 'loyalty',
    },
    {
        'name': 'Points fidélité expirant', 'code': 'loyalty_expiring_points',
        'description': 'Points fidélité arrivant à expiration dans les 30 jours.',
        'module_code': 'loyalty', 'widget_type': 'alert',
        'icon': 'bi-hourglass-split', 'color': '#DC2626',
        'template_name': 'dashboard/partials/widget_loyalty.html',
        'default_width': 6, 'default_height': 3, 'order': 154,
        'requires_permission': True, 'permission_code': 'loyalty',
    },
    # ─── Cartes-cadeaux ───────────────────────────────────────────────────────
    {
        'name': 'Cartes-cadeaux émises', 'code': 'gift_cards_issued',
        'description': 'Cartes-cadeaux émises ce mois-ci.',
        'module_code': 'giftcards', 'widget_type': 'kpi',
        'icon': 'bi-gift-fill', 'color': '#C4936A',
        'template_name': 'dashboard/partials/widget_giftcards.html',
        'default_width': 4, 'default_height': 2, 'order': 160,
        'requires_permission': True, 'permission_code': 'giftcards',
    },
    {
        'name': 'Cartes-cadeaux actives', 'code': 'gift_cards_active',
        'description': 'Solde total des cartes-cadeaux en circulation.',
        'module_code': 'giftcards', 'widget_type': 'kpi',
        'icon': 'bi-wallet2', 'color': '#10B981',
        'template_name': 'dashboard/partials/widget_giftcards.html',
        'default_width': 4, 'default_height': 2, 'order': 161,
        'requires_permission': True, 'permission_code': 'giftcards',
    },
    {
        'name': 'Cartes-cadeaux utilisées', 'code': 'gift_cards_redeemed',
        'description': 'Cartes-cadeaux utilisées ce mois-ci.',
        'module_code': 'giftcards', 'widget_type': 'kpi',
        'icon': 'bi-credit-card-2-back', 'color': '#2563EB',
        'template_name': 'dashboard/partials/widget_giftcards.html',
        'default_width': 4, 'default_height': 2, 'order': 162,
        'requires_permission': True, 'permission_code': 'giftcards',
    },
    {
        'name': 'Cartes-cadeaux expirant', 'code': 'gift_cards_expiring',
        'description': 'Cartes-cadeaux expirant dans les 30 prochains jours.',
        'module_code': 'giftcards', 'widget_type': 'alert',
        'icon': 'bi-alarm', 'color': '#F59E0B',
        'template_name': 'dashboard/partials/widget_giftcards.html',
        'default_width': 6, 'default_height': 3, 'order': 163,
        'requires_permission': True, 'permission_code': 'giftcards',
    },
    # ─── Intelligence Orion ───────────────────────────────────────────────────
    {
        'name': 'Suggestions Orion', 'code': 'orion_suggestions',
        'description': 'Recommandations intelligentes basées sur l\'activité en cours.',
        'module_code': '', 'widget_type': 'summary',
        'icon': 'bi-stars', 'color': '#C6A15B',
        'template_name': 'dashboard/partials/widget_orion_suggestions.html',
        'default_width': 12, 'default_height': 3, 'order': 0,
        'requires_permission': False,
    },
    {
        'name': 'Résumé journalier', 'code': 'daily_summary',
        'description': 'Vue d\'ensemble de la journée : validations, retards, tickets.',
        'module_code': '', 'widget_type': 'summary',
        'icon': 'bi-clipboard2-pulse', 'color': '#3A2A1A',
        'template_name': 'dashboard/partials/widget_daily_summary.html',
        'default_width': 12, 'default_height': 2, 'order': 0,
        'requires_permission': False,
    },
    {
        'name': 'Mes objectifs', 'code': 'personal_goals',
        'description': 'Objectifs personnels avec barre de progression.',
        'module_code': '', 'widget_type': 'goal',
        'icon': 'bi-trophy', 'color': '#C6A15B',
        'template_name': 'dashboard/partials/widget_personal_goals.html',
        'default_width': 6, 'default_height': 4, 'order': 9,
        'requires_permission': False,
    },
]


class Command(BaseCommand):
    help = 'Crée les widgets du catalogue Orion ERP.'

    def handle(self, *args, **options):
        created_count = 0
        updated_count = 0
        for w in WIDGETS:
            obj, created = DashboardWidget.objects.update_or_create(
                code=w['code'],
                defaults=w,
            )
            if created:
                created_count += 1
            else:
                updated_count += 1

        self.stdout.write(self.style.SUCCESS(
            f'{created_count} widget(s) créé(s), {updated_count} widget(s) mis à jour.'
        ))
