# Generated by Django 4.2.30 on 2026-06-23 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_notification_related_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('check_type', models.CharField(choices=[('database', 'Base de données'), ('cache', 'Cache'), ('storage', 'Stockage'), ('email', 'E-mail'), ('external_api', 'API externe'), ('queue', 'File de tâches'), ('disk_space', 'Espace disque'), ('memory', 'Mémoire'), ('cpu', 'CPU'), ('custom', 'Personnalisé')], max_length=80)),
                ('trigger_status', models.CharField(choices=[('ok', 'OK'), ('warning', 'Avertissement'), ('critical', 'Critique'), ('unknown', 'Inconnu')], default='critical', max_length=30)),
                ('notify_emails', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_alert_rules', to='core.company')),
            ],
            options={
                'verbose_name': 'Règle alerte système',
                'verbose_name_plural': 'Règles alertes système',
            },
        ),
        migrations.CreateModel(
            name='SystemObservabilityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('database', 'Base de données'), ('cache', 'Cache'), ('storage', 'Stockage'), ('email', 'E-mail'), ('external_api', 'API externe'), ('queue', 'File de tâches'), ('disk_space', 'Espace disque'), ('memory', 'Mémoire'), ('cpu', 'CPU'), ('custom', 'Personnalisé')], max_length=80)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Avertissement'), ('critical', 'Critique'), ('emergency', 'Urgence')], default='warning', max_length=30)),
                ('title', models.CharField(max_length=180)),
                ('message', models.TextField()),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_sys_alerts', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_obs_alerts', to='core.company')),
            ],
            options={
                'verbose_name': 'Alerte système',
                'verbose_name_plural': 'Alertes système',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'severity', 'is_acknowledged'], name='system_obse_company_d4dc10_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemHealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(choices=[('database', 'Base de données'), ('cache', 'Cache'), ('storage', 'Stockage'), ('email', 'E-mail'), ('external_api', 'API externe'), ('queue', 'File de tâches'), ('disk_space', 'Espace disque'), ('memory', 'Mémoire'), ('cpu', 'CPU'), ('custom', 'Personnalisé')], max_length=80)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('warning', 'Avertissement'), ('critical', 'Critique'), ('unknown', 'Inconnu')], default='unknown', max_length=30)),
                ('message', models.TextField(blank=True)),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_checks', to='core.company')),
            ],
            options={
                'verbose_name': 'Vérification santé système',
                'verbose_name_plural': 'Vérifications santé système',
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['company', 'check_type', 'checked_at'], name='system_obse_company_d28090_idx')],
            },
        ),
    ]
