# Generated by Django 4.2.30 on 2026-06-26 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_notification_related_names'),
        ('crm', '0004_remove_customer_crm_cust_co_date_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_key', models.CharField(default='siecle', max_length=40)),
                ('reference', models.CharField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=180)),
                ('category', models.CharField(choices=[('montre', 'Montre'), ('bijou', 'Bijou'), ('accessoire', 'Accessoire'), ('coffret', 'Coffret cadeau'), ('piece_unique', 'Pièce unique'), ('edition_limitee', 'Édition limitée')], max_length=40)),
                ('description', models.TextField(blank=True)),
                ('materials', models.TextField(blank=True)),
                ('price_ht', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('price_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stock_qty', models.PositiveIntegerField(default=0)),
                ('images', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('weight_grams', models.PositiveIntegerField(blank=True, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=100)),
                ('is_limited_edition', models.BooleanField(default=False)),
                ('limited_qty', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('archived', 'Archivé'), ('sold_out', 'Épuisé')], default='draft', max_length=30)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siecle_creations', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_siecle_creations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Création Siècle',
                'verbose_name_plural': 'Créations Siècle',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreationOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_key', models.CharField(default='siecle', max_length=40)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('in_production', 'En production'), ('shipped', 'Expédiée'), ('delivered', 'Livrée'), ('cancelled', 'Annulée')], default='pending', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('shipping_address', models.TextField(blank=True)),
                ('personalization', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siecle_orders', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_siecle_orders', to=settings.AUTH_USER_MODEL)),
                ('creation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='siecle_creations.creation')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='siecle_orders', to='crm.customer')),
            ],
            options={
                'verbose_name': 'Commande Siècle',
                'verbose_name_plural': 'Commandes Siècle',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='creation',
            index=models.Index(fields=['company', 'status', 'category'], name='siecle_crea_company_a12466_idx'),
        ),
        migrations.AddIndex(
            model_name='creation',
            index=models.Index(fields=['company', 'brand_key'], name='siecle_crea_company_e5657d_idx'),
        ),
    ]
