# Generated by Django 4.2.30 on 2026-06-23 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_notification_related_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('job_type', models.CharField(choices=[('full_db', 'Base de données complète'), ('incremental_db', 'BDD incrémentale'), ('media_files', 'Fichiers media'), ('config', 'Configuration'), ('full_system', 'Système complet')], max_length=40)),
                ('schedule', models.CharField(choices=[('manual', 'Manuel'), ('hourly', 'Toutes les heures'), ('daily', 'Quotidien'), ('weekly', 'Hebdomadaire'), ('monthly', 'Mensuel')], default='manual', max_length=30)),
                ('storage_target', models.CharField(choices=[('local', 'Local'), ('s3', 'Amazon S3'), ('gcs', 'Google Cloud Storage'), ('azure_blob', 'Azure Blob'), ('ftp', 'FTP/SFTP'), ('email', 'E-mail')], default='local', max_length=40)),
                ('storage_config', models.JSONField(blank=True, default=dict)),
                ('retention_days', models.PositiveIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, choices=[('pending', 'En attente'), ('running', 'En cours'), ('success', 'Succès'), ('failed', 'Échec'), ('partial', 'Partiel')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_center_jobs', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_backup_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tâche de sauvegarde',
                'verbose_name_plural': 'Tâches de sauvegarde',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackupRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('success', 'Succès'), ('failed', 'Échec'), ('partial', 'Partiel')], default='pending', max_length=30)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_runs', to='core.company')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='backup_center.backupjob')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_backup_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exécution sauvegarde',
                'verbose_name_plural': 'Exécutions sauvegarde',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['company', 'status', 'started_at'], name='backup_cent_company_9ffa9b_idx')],
            },
        ),
    ]
