# Generated by Django 4.2.16 on 2026-06-18 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BTPPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la phase')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fin')),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Budget HT')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Terminée')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BTPProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=30, verbose_name='Code chantier')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du chantier')),
                ('status', models.CharField(choices=[('study', 'Étude'), ('quoted', 'Devis envoyé'), ('won', 'Gagné'), ('in_progress', 'En cours'), ('completed', 'Terminé'), ('invoiced', 'Facturé'), ('guaranteed', 'En garantie'), ('lost', 'Perdu'), ('cancelled', 'Annulé')], default='study', max_length=20, verbose_name='Statut')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('address', models.TextField(blank=True, verbose_name='Adresse du chantier')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('zip_code', models.CharField(blank=True, max_length=10, verbose_name='CP')),
                ('site_foreman', models.CharField(blank=True, max_length=100, verbose_name='Chef de chantier')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Début prévu')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fin prévue')),
                ('actual_start_date', models.DateField(blank=True, null=True, verbose_name='Début réel')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='Fin réelle')),
                ('estimated_budget', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Budget prévu HT')),
                ('actual_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Coût réel HT')),
                ('invoiced_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant facturé HT')),
                ('retention_rate', models.DecimalField(decimal_places=2, default=5, max_digits=5, verbose_name='Retenue garantie %')),
                ('market_type', models.CharField(blank=True, max_length=100, verbose_name='Type marché')),
                ('market_number', models.CharField(blank=True, max_length=50, verbose_name='N° marché')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='btp_projects', to='core.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='btp_projects', to='crm.customer')),
                ('project_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_btp_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chantier BTP',
                'verbose_name_plural': 'Chantiers BTP',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BTPQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=30, verbose_name='Numéro')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyé'), ('accepted', 'Accepté'), ('refused', 'Refusé'), ('expired', 'Expiré')], default='draft', max_length=20, verbose_name='Statut')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('validity_date', models.DateField(blank=True, null=True, verbose_name='Validité')),
                ('subject', models.CharField(blank=True, max_length=300, verbose_name='Objet')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('total_ht', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total HT')),
                ('total_tva', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total TVA')),
                ('total_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total TTC')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='btp_quotes', to='core.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='btp_quotes', to='crm.customer')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='btp.btpproject')),
            ],
            options={
                'verbose_name': 'Devis BTP',
                'verbose_name_plural': 'Devis BTP',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='WorkLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=30, verbose_name='Code ouvrage')),
                ('name', models.CharField(max_length=300, verbose_name='Désignation')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Catégorie')),
                ('unit', models.CharField(default='m²', max_length=20, verbose_name='Unité')),
                ('unit_price', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Prix unitaire HT')),
                ('description', models.TextField(blank=True, verbose_name='Détail')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_library', to='core.company')),
            ],
            options={
                'verbose_name': 'Ouvrage BTP',
                'verbose_name_plural': 'Bibliothèque ouvrages',
                'ordering': ['code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BTPTimesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(verbose_name='Date')),
                ('hours', models.DecimalField(decimal_places=2, default=8, max_digits=5, verbose_name='Heures')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Heures sup')),
                ('task_description', models.CharField(blank=True, max_length=200, verbose_name='Tâche')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('is_validated', models.BooleanField(default=False, verbose_name='Validé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='btp_timesheets', to='core.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='btp_timesheets', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='btp.btpproject')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_timesheets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pointage',
                'verbose_name_plural': 'Pointages',
                'ordering': ['-work_date'],
            },
        ),
        migrations.CreateModel(
            name='BTPQuoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Désignation')),
                ('unit', models.CharField(default='m²', max_length=20, verbose_name='Unité')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Quantité')),
                ('unit_price', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='PU HT')),
                ('total_ht', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total HT')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=20, max_digits=5, verbose_name='TVA %')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('is_section', models.BooleanField(default=False, verbose_name='Sous-total section')),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='btp.btpphase')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='btp.btpquote')),
                ('work_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='btp.worklibrary')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='btpphase',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='btp.btpproject'),
        ),
        migrations.CreateModel(
            name='SituationOfWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=1, verbose_name='N° situation')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumise'), ('approved', 'Approuvée'), ('invoiced', 'Facturée'), ('rejected', 'Rejetée')], default='draft', max_length=20, verbose_name='Statut')),
                ('period_start', models.DateField(verbose_name='Début période')),
                ('period_end', models.DateField(verbose_name='Fin période')),
                ('cumulative_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant cumulé HT')),
                ('previous_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant précédent HT')),
                ('period_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant période HT')),
                ('retention_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Retenue garantie HT')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Validée le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='situations', to='core.company')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='situations', to='btp.btpproject')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_situations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Situation de travaux',
                'verbose_name_plural': 'Situations de travaux',
                'ordering': ['-period_end'],
                'unique_together': {('project', 'number')},
            },
        ),
    ]
