# Generated by Django 4.2.16 on 2026-06-18 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('sector', models.CharField(choices=[('btp', 'BTP / Construction'), ('ecommerce', 'E-commerce'), ('commerce', 'Commerce / Négoce'), ('production', 'Production / Industrie'), ('audio', 'Audio / Audiovisuel'), ('services', 'Services'), ('other', 'Autre')], default='other', max_length=50, verbose_name='Secteur')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='companies/logos/', verbose_name='Logo')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='companies/favicons/', verbose_name='Favicon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('zip_code', models.CharField(blank=True, max_length=10, verbose_name='Code postal')),
                ('country', models.CharField(default='France', max_length=100, verbose_name='Pays')),
                ('siret', models.CharField(blank=True, max_length=14, verbose_name='SIRET')),
                ('siren', models.CharField(blank=True, max_length=9, verbose_name='SIREN')),
                ('vat_number', models.CharField(blank=True, max_length=20, verbose_name='N° TVA intracommunautaire')),
                ('rcs', models.CharField(blank=True, max_length=100, verbose_name='RCS')),
                ('capital', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Capital social')),
                ('legal_form', models.CharField(blank=True, max_length=50, verbose_name='Forme juridique')),
                ('primary_color', models.CharField(default='#2563EB', max_length=7, verbose_name='Couleur primaire')),
                ('secondary_color', models.CharField(default='#0F172A', max_length=7, verbose_name='Couleur secondaire')),
                ('accent_color', models.CharField(default='#38BDF8', max_length=7, verbose_name='Couleur accent')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Devise')),
                ('timezone', models.CharField(default='Europe/Paris', max_length=50, verbose_name='Fuseau horaire')),
                ('date_format', models.CharField(default='%d/%m/%Y', max_length=20, verbose_name='Format date')),
                ('invoice_prefix', models.CharField(default='FAC', max_length=10, verbose_name='Préfixe facture')),
                ('quote_prefix', models.CharField(default='DEV', max_length=10, verbose_name='Préfixe devis')),
                ('order_prefix', models.CharField(default='CMD', max_length=10, verbose_name='Préfixe commande')),
                ('default_vat_rate', models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='Taux TVA défaut')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='Banque')),
                ('iban', models.CharField(blank=True, max_length=34, verbose_name='IBAN')),
                ('bic', models.CharField(blank=True, max_length=11, verbose_name='BIC / SWIFT')),
                ('website_url', models.URLField(blank=True, verbose_name='Site web')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifiée le')),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('level', models.CharField(choices=[('info', 'Information'), ('success', 'Succès'), ('warning', 'Avertissement'), ('danger', 'Alerte')], default='info', max_length=10, verbose_name='Niveau')),
                ('link', models.CharField(blank=True, max_length=300, verbose_name='Lien')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_invoice_number', models.PositiveIntegerField(default=1)),
                ('next_quote_number', models.PositiveIntegerField(default=1)),
                ('next_order_number', models.PositiveIntegerField(default=1)),
                ('payment_terms_days', models.PositiveIntegerField(default=30, verbose_name='Délai paiement (jours)')),
                ('late_payment_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Taux pénalité retard')),
                ('invoice_footer', models.TextField(blank=True, verbose_name='Pied de facture')),
                ('quote_validity_days', models.PositiveIntegerField(default=30, verbose_name='Validité devis (jours)')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='core.company')),
            ],
            options={
                'verbose_name': 'Paramètres entreprise',
                'verbose_name_plural': 'Paramètres entreprises',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('login', 'Connexion'), ('logout', 'Déconnexion'), ('view', 'Consultation'), ('export', 'Export'), ('import', 'Import'), ('validate', 'Validation'), ('reject', 'Rejet'), ('other', 'Autre')], max_length=20, verbose_name='Action')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='Modèle')),
                ('object_id', models.CharField(blank=True, max_length=50, verbose_name='ID objet')),
                ('object_repr', models.CharField(blank=True, max_length=200, verbose_name='Description objet')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.company', verbose_name='Entreprise')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Journal d'audit",
                'verbose_name_plural': "Journal d'audit",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connector_type', models.CharField(choices=[('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('prestashop', 'PrestaShop'), ('magento', 'Magento'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('alma', 'Alma'), ('klarna', 'Klarna'), ('colissimo', 'Colissimo'), ('chronopost', 'Chronopost'), ('dhl', 'DHL'), ('bank', 'Banque'), ('ocr', 'OCR Factures'), ('esign', 'Signature électronique'), ('google_analytics', 'Google Analytics'), ('meta_pixel', 'Meta Pixel'), ('other', 'Autre')], max_length=30, verbose_name='Type')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('api_url', models.URLField(blank=True, verbose_name='URL API')),
                ('api_key', models.TextField(blank=True, verbose_name='Clé API (chiffrée)')),
                ('api_secret', models.TextField(blank=True, verbose_name='Secret API (chiffré)')),
                ('extra_config', models.JSONField(blank=True, default=dict, verbose_name='Configuration supplémentaire')),
                ('is_active', models.BooleanField(default=False, verbose_name='Actif')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='Dernière sync')),
                ('sync_log', models.TextField(blank=True, verbose_name='Log de sync')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectors', to='core.company')),
            ],
            options={
                'verbose_name': 'Connecteur',
                'verbose_name_plural': 'Connecteurs',
                'unique_together': {('company', 'connector_type')},
            },
        ),
    ]
