# Generated by Django 4.2.30 on 2026-06-19 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='database_archived',
            field=models.BooleanField(default=False, verbose_name='Base archivée'),
        ),
        migrations.AddField(
            model_name='company',
            name='database_archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Base archivée le'),
        ),
        migrations.AddField(
            model_name='company',
            name='database_created',
            field=models.BooleanField(default=False, verbose_name='Base créée'),
        ),
        migrations.AddField(
            model_name='company',
            name='database_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Base créée le'),
        ),
        migrations.AddField(
            model_name='company',
            name='database_deleted',
            field=models.BooleanField(default=False, verbose_name='Base supprimée'),
        ),
        migrations.AddField(
            model_name='company',
            name='database_deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Base supprimée le'),
        ),
        migrations.AddField(
            model_name='company',
            name='database_host',
            field=models.CharField(blank=True, default='127.0.0.1', max_length=200, verbose_name='Hôte base'),
        ),
        migrations.AddField(
            model_name='company',
            name='database_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nom base de données'),
        ),
        migrations.AddField(
            model_name='company',
            name='database_password',
            field=models.CharField(blank=True, max_length=200, verbose_name='Mot de passe base'),
        ),
        migrations.AddField(
            model_name='company',
            name='database_port',
            field=models.PositiveIntegerField(default=3306, verbose_name='Port base'),
        ),
        migrations.AddField(
            model_name='company',
            name='database_user',
            field=models.CharField(blank=True, default='root', max_length=100, verbose_name='Utilisateur base'),
        ),
        migrations.AddField(
            model_name='company',
            name='legal_name',
            field=models.CharField(blank=True, max_length=300, verbose_name='Raison sociale'),
        ),
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspendue'), ('archived', 'Archivée'), ('deleting', 'En suppression'), ('deleted', 'Supprimée')], default='active', max_length=20, verbose_name='Statut'),
        ),
        migrations.CreateModel(
            name='CompanyDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database_alias', models.CharField(max_length=100, unique=True, verbose_name='Alias Django')),
                ('database_name', models.CharField(max_length=100, verbose_name='Nom base')),
                ('database_engine', models.CharField(choices=[('django.db.backends.mysql', 'MySQL / MariaDB'), ('django.db.backends.postgresql', 'PostgreSQL'), ('django.db.backends.sqlite3', 'SQLite')], default='django.db.backends.mysql', max_length=100, verbose_name='Moteur')),
                ('host', models.CharField(default='127.0.0.1', max_length=200, verbose_name='Hôte')),
                ('port', models.PositiveIntegerField(default=3306, verbose_name='Port')),
                ('user', models.CharField(default='root', max_length=100, verbose_name='Utilisateur')),
                ('password_encrypted', models.TextField(blank=True, verbose_name='Mot de passe (chiffré)')),
                ('status', models.CharField(choices=[('to_create', 'À créer'), ('created', 'Créée'), ('migration_pending', 'Migration en attente'), ('active', 'Active'), ('archived', 'Archivée'), ('error', 'Erreur'), ('deleted', 'Supprimée')], default='to_create', max_length=30, verbose_name='Statut')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('last_migration_at', models.DateTimeField(blank=True, null=True, verbose_name='Dernière migration')),
                ('last_backup_at', models.DateTimeField(blank=True, null=True, verbose_name='Dernière sauvegarde')),
                ('last_error', models.TextField(blank=True, verbose_name='Dernière erreur')),
                ('size_mb', models.FloatField(default=0, verbose_name='Taille estimée (Mo)')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_database', to='core.company')),
            ],
            options={
                'verbose_name': 'Base de données entreprise',
                'verbose_name_plural': 'Bases de données entreprises',
            },
        ),
        migrations.CreateModel(
            name='CompanyAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('viewer', 'Lecteur'), ('user', 'Utilisateur'), ('manager', 'Responsable'), ('admin', 'Administrateur'), ('owner', 'Propriétaire')], default='user', max_length=30, verbose_name='Rôle')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_default_company', models.BooleanField(default=False, verbose_name='Entreprise par défaut')),
                ('can_manage_company', models.BooleanField(default=False, verbose_name="Peut gérer l'entreprise")),
                ('can_delete_company_database', models.BooleanField(default=False, verbose_name='Peut supprimer la base')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extended_accesses', to='core.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extended_company_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Accès entreprise (étendu)',
                'verbose_name_plural': 'Accès entreprises (étendus)',
                'unique_together': {('user', 'company')},
            },
        ),
    ]
