# Generated by Django 4.2.30 on 2026-06-22 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='account',
            name='acc_acct_co_num_idx',
        ),
        migrations.RemoveIndex(
            model_name='fiscalyear',
            name='acc_fy_co_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='journalentry',
            name='acc_je_co_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='journalentry',
            name='acc_je_co_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='journalentry',
            name='acc_je_co_journal_idx',
        ),
        migrations.RemoveIndex(
            model_name='journalentryline',
            name='acc_jel_account_idx',
        ),
        migrations.RemoveIndex(
            model_name='journalentryline',
            name='acc_jel_reconcil_idx',
        ),
    ]
