# Generated by Django 4.2.30 on 2026-06-23 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_notification_related_names'),
        ('crm', '0004_remove_customer_crm_cust_co_date_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_key', models.CharField(blank=True, max_length=40)),
                ('event_type', models.CharField(choices=[('order', 'Commande'), ('quote', 'Devis'), ('invoice', 'Facture'), ('payment', 'Paiement'), ('support', 'Ticket support'), ('message', 'Message'), ('portal_login', 'Connexion portail'), ('document', 'Document'), ('note', 'Note interne'), ('alert', 'Alerte'), ('email', 'Email'), ('call', 'Appel'), ('visit', 'Visite'), ('loyalty', 'Points fidélité'), ('custom', 'Événement personnalisé')], max_length=80)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('related_object_type', models.CharField(blank=True, max_length=80)),
                ('related_object_id', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_timeline_events', to='core.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='crm.customer')),
            ],
            options={
                'verbose_name': 'Événement timeline client',
                'verbose_name_plural': 'Événements timeline clients',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'customer', 'created_at'], name='customer_36_company_b56857_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomerScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_key', models.CharField(blank=True, max_length=40)),
                ('score_type', models.CharField(choices=[('loyalty', 'Fidélité'), ('risk', 'Risque départ'), ('payment', 'Comportement paiement'), ('potential', 'Potentiel'), ('engagement', 'Engagement'), ('overall', 'Score global')], max_length=80)),
                ('score', models.DecimalField(decimal_places=2, max_digits=8)),
                ('label', models.CharField(blank=True, max_length=80)),
                ('explanation', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_scores', to='core.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='crm.customer')),
            ],
            options={
                'verbose_name': 'Score client',
                'verbose_name_plural': 'Scores clients',
                'ordering': ['-updated_at'],
                'unique_together': {('company', 'customer', 'score_type', 'brand_key')},
            },
        ),
    ]
