# Generated by Django 4.2.30 on 2026-06-26 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemUpdateRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('planned', 'Planifiée'), ('running', 'En cours'), ('success', 'Succès'), ('failed', 'Échec'), ('cancelled', 'Annulée'), ('rolled_back', 'Rollback effectué')], default='planned', max_length=40)),
                ('from_commit', models.CharField(blank=True, max_length=120)),
                ('to_commit', models.CharField(blank=True, max_length=120)),
                ('from_version', models.CharField(blank=True, max_length=80)),
                ('to_version', models.CharField(blank=True, max_length=80)),
                ('backup_reference', models.CharField(blank=True, max_length=255)),
                ('maintenance_enabled', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('result_payload', models.JSONField(blank=True, default=dict)),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemUpdateStepLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_code', models.CharField(max_length=120)),
                ('step_name', models.CharField(max_length=180)),
                ('level', models.CharField(choices=[('info', 'Info'), ('success', 'Succès'), ('warning', 'Avertissement'), ('error', 'Erreur')], default='info', max_length=40)),
                ('message', models.TextField(blank=True)),
                ('command', models.TextField(blank=True)),
                ('output', models.TextField(blank=True)),
                ('error_output', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('update_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='system_updates.systemupdaterun')),
            ],
            options={
                'ordering': ['started_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemUpdateSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_enabled', models.BooleanField(default=True)),
                ('manual_only', models.BooleanField(default=True)),
                ('git_remote', models.CharField(default='origin', max_length=120)),
                ('git_branch', models.CharField(default='main', max_length=120)),
                ('require_backup_before_update', models.BooleanField(default=True)),
                ('require_health_check_before_update', models.BooleanField(default=True)),
                ('allow_rollback', models.BooleanField(default=True)),
                ('update_backend_enabled', models.BooleanField(default=True)),
                ('update_frontend_siecle_enabled', models.BooleanField(default=True)),
                ('update_frontend_lunea_enabled', models.BooleanField(default=True)),
                ('run_migrations', models.BooleanField(default=True)),
                ('collect_static', models.BooleanField(default=True)),
                ('restart_services', models.BooleanField(default=True)),
                ('maintenance_mode_during_update', models.BooleanField(default=True)),
                ('notify_admins', models.BooleanField(default=True)),
                ('notify_email', models.EmailField(blank=True, max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paramètres mises à jour',
                'verbose_name_plural': 'Paramètres mises à jour',
            },
        ),
        migrations.CreateModel(
            name='SystemUpdateCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('checking', 'Vérification en cours'), ('up_to_date', 'À jour'), ('update_available', 'Mise à jour disponible'), ('failed', 'Échec')], default='checking', max_length=40)),
                ('current_version', models.CharField(blank=True, max_length=80)),
                ('current_commit', models.CharField(blank=True, max_length=120)),
                ('remote_version', models.CharField(blank=True, max_length=80)),
                ('remote_commit', models.CharField(blank=True, max_length=120)),
                ('commits_behind', models.PositiveIntegerField(default=0)),
                ('commits_ahead', models.PositiveIntegerField(default=0)),
                ('branch', models.CharField(blank=True, max_length=120)),
                ('changelog', models.TextField(blank=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemRollbackRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'En cours'), ('success', 'Succès'), ('failed', 'Échec')], default='running', max_length=40)),
                ('rollback_to_commit', models.CharField(max_length=120)),
                ('backup_reference', models.CharField(blank=True, max_length=255)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('result_payload', models.JSONField(blank=True, default=dict)),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('update_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rollback_runs', to='system_updates.systemupdaterun')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
