# Generated by Django 4.2.30 on 2026-08-11 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_updates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemupdatesettings',
            name='github_token_encrypted',
            field=models.TextField(blank=True, help_text="Jeton d'accès personnel GitHub (chiffré), requis si le dépôt est privé."),
        ),
    ]
