# Generated by Django 4.2.30 on 2026-08-12 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system_updates', '0002_systemupdatesettings_github_token_encrypted'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('reboot', 'Redémarrage'), ('shutdown', 'Extinction'), ('cancel', 'Annulation')], max_length=20)),
                ('status', models.CharField(choices=[('success', 'Succès'), ('failed', 'Échec')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Action serveur',
                'verbose_name_plural': 'Actions serveur',
                'ordering': ['-executed_at'],
            },
        ),
    ]
