# Generated by Django 4.2.16 on 2026-06-18 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom événement')),
                ('event_type', models.CharField(choices=[('concert', 'Concert'), ('corporate', 'Événement corporate'), ('wedding', 'Mariage'), ('conference', 'Conférence'), ('festival', 'Festival'), ('exhibition', 'Exposition'), ('show', 'Spectacle'), ('other', 'Autre')], default='other', max_length=20, verbose_name='Type')),
                ('status', models.CharField(choices=[('inquiry', 'Demande'), ('quoted', 'Devis envoyé'), ('confirmed', 'Confirmé'), ('in_progress', 'En cours'), ('completed', 'Terminé'), ('invoiced', 'Facturé'), ('cancelled', 'Annulé')], default='inquiry', max_length=20, verbose_name='Statut')),
                ('event_date', models.DateField(verbose_name='Date événement')),
                ('setup_date', models.DateField(blank=True, null=True, verbose_name='Date montage')),
                ('teardown_date', models.DateField(blank=True, null=True, verbose_name='Date démontage')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Heure début')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Heure fin')),
                ('venue', models.CharField(blank=True, max_length=300, verbose_name='Lieu')),
                ('venue_address', models.TextField(blank=True, verbose_name='Adresse lieu')),
                ('expected_attendance', models.PositiveIntegerField(blank=True, null=True, verbose_name='Jauge prévue')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('technical_notes', models.TextField(blank=True, verbose_name='Notes techniques')),
                ('estimated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant prévu HT')),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Acompte')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_events', to='core.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audio_events', to='crm.customer')),
            ],
            options={
                'verbose_name': 'Événement Audio',
                'verbose_name_plural': 'Événements Audio',
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Marque')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Modèle')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='N° série')),
                ('reference', models.CharField(blank=True, max_length=50, verbose_name='Référence interne')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='equipment/', verbose_name='Photo')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantité totale')),
                ('available_quantity', models.PositiveIntegerField(default=1, verbose_name='Quantité disponible')),
                ('rental_price_day', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix location/jour HT')),
                ('replacement_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valeur remplacement')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Date achat')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix achat')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('rented', 'En location'), ('maintenance', 'En maintenance'), ('damaged', 'Endommagé'), ('lost', 'Perdu'), ('retired', 'Retiré')], default='available', max_length=20, verbose_name='État')),
                ('last_maintenance_date', models.DateField(blank=True, null=True, verbose_name='Dernière maintenance')),
                ('next_maintenance_date', models.DateField(blank=True, null=True, verbose_name='Prochaine maintenance')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Matériel',
                'verbose_name_plural': 'Matériels',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du pack')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('rental_price_day', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix pack/jour HT')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_packs', to='core.company')),
            ],
            options={
                'verbose_name': 'Pack matériel',
            },
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('specialties', models.CharField(blank=True, max_length=300, verbose_name='Spécialités')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('day_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tarif journée HT')),
                ('is_employee', models.BooleanField(default=True, verbose_name='Salarié')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technicians', to='core.company')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Technicien',
            },
        ),
        migrations.CreateModel(
            name='PackItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.equipment')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.equipmentpack')),
            ],
        ),
        migrations.CreateModel(
            name='EventTechnicianAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=100, verbose_name='Rôle')),
                ('start_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Début')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Fin')),
                ('day_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tarif journée HT')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Confirmé')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technician_assignments', to='audio.audioevent')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_assignments', to='audio.technician')),
            ],
            options={
                'verbose_name': 'Affectation technicien',
            },
        ),
        migrations.CreateModel(
            name='EquipmentReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('start_date', models.DateField(verbose_name='Début location')),
                ('end_date', models.DateField(verbose_name='Fin location')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('checked_out', 'Sorti'), ('returned', 'Rendu'), ('cancelled', 'Annulée')], default='pending', max_length=20, verbose_name='Statut')),
                ('daily_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tarif jour HT')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant total HT')),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Caution')),
                ('deposit_returned', models.BooleanField(default=False, verbose_name='Caution rendue')),
                ('condition_out', models.TextField(blank=True, verbose_name='État départ')),
                ('condition_in', models.TextField(blank=True, verbose_name='État retour')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_in', to=settings.AUTH_USER_MODEL)),
                ('checked_out_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_out', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_reservations', to='core.company')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment_reservations', to='crm.customer')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='audio.equipment')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='audio.audioevent')),
            ],
            options={
                'verbose_name': 'Réservation matériel',
                'verbose_name_plural': 'Réservations matériel',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='equipmentpack',
            name='items',
            field=models.ManyToManyField(blank=True, through='audio.PackItem', to='audio.equipment'),
        ),
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Catégorie')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'verbose_name': 'Catégorie matériel',
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='audio.equipmentcategory'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='core.company'),
        ),
    ]
