# Generated by Django 4.2.30 on 2026-06-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_key', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=180)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=180)),
                ('message', models.TextField()),
                ('status', models.CharField(default='new', max_length=40)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('honeypot', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Message contact',
                'verbose_name_plural': 'Messages contact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WaitlistSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_key', models.CharField(choices=[('siecle', 'SIÈCLE'), ('lunea', 'LUNEA')], max_length=40)),
                ('feature_key', models.CharField(default='general', max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Abonné liste d'attente",
                'verbose_name_plural': "Abonnés liste d'attente",
                'ordering': ['-created_at'],
                'unique_together': {('brand_key', 'feature_key', 'email')},
            },
        ),
    ]
