# Generated by Django 4.2.16 on 2026-06-18 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('product', 'Produit physique'), ('service', 'Service'), ('consumable', 'Consommable'), ('digital', 'Produit numérique')], default='product', max_length=20, verbose_name='Type')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Référence')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('description_sale', models.TextField(blank=True, verbose_name='Description vente')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Image')),
                ('barcode', models.CharField(blank=True, max_length=50, verbose_name='Code-barres')),
                ('sale_price', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Prix vente HT')),
                ('purchase_price', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Prix achat HT')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=20, max_digits=5, verbose_name='TVA %')),
                ('track_inventory', models.BooleanField(default=True, verbose_name='Gérer le stock')),
                ('stock_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Stock actuel')),
                ('min_stock_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Stock minimum')),
                ('max_stock_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Stock maximum')),
                ('unit', models.CharField(default='unité', max_length=20, verbose_name='Unité')),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Poids (kg)')),
                ('supplier_reference', models.CharField(blank=True, max_length=100, verbose_name='Réf fournisseur')),
                ('lead_time_days', models.PositiveIntegerField(default=0, verbose_name='Délai approvisionnement (j)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publié sur site web')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.stocklocation')),
            ],
            options={
                'verbose_name': 'Emplacement',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('code', models.CharField(blank=True, max_length=10, verbose_name='Code')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='core.company')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrepôt',
                'verbose_name_plural': 'Entrepôts',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Entrée'), ('out', 'Sortie'), ('transfer', 'Transfert'), ('adjustment', 'Ajustement'), ('return', 'Retour'), ('loss', 'Perte')], max_length=20, verbose_name='Type')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantité')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Coût unitaire')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Référence')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('lot_number', models.CharField(blank=True, max_length=50, verbose_name='N° lot')),
                ('serial_number', models.CharField(blank=True, max_length=50, verbose_name='N° série')),
                ('movement_date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='core.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing', to='inventory.stocklocation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.product')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming', to='inventory.stocklocation')),
            ],
            options={
                'verbose_name': 'Mouvement stock',
                'verbose_name_plural': 'Mouvements stock',
                'ordering': ['-movement_date'],
            },
        ),
        migrations.AddField(
            model_name='stocklocation',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='inventory.warehouse'),
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='core.company')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='inventory.productcategory')),
            ],
            options={
                'verbose_name': 'Catégorie produit',
                'verbose_name_plural': 'Catégories produits',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.productcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.company'),
        ),
    ]
