# Generated by Django 4.2.30 on 2026-06-22 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='inv_prod_co_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='inv_prod_co_ref_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockmovement',
            name='inv_mov_co_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockmovement',
            name='inv_mov_prod_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockmovement',
            name='inv_mov_co_type_idx',
        ),
    ]
