# Generated by Django 4.2.16 on 2026-06-18 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('quote', 'Devis'), ('invoice', 'Facture'), ('purchase_order', 'Commande achat'), ('leave_request', 'Congé'), ('expense_report', 'Note de frais'), ('situation', 'Situation de travaux'), ('document', 'Document')], max_length=30)),
                ('object_id', models.PositiveIntegerField()),
                ('step_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_steps', to='core.company')),
                ('validator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_steps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Étape workflow',
            },
        ),
    ]
