# Generated by Django 4.2.30 on 2026-06-22 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customer',
            name='crm_cust_co_date_idx',
        ),
    ]
