# Generated by Django 4.2.30 on 2026-06-19 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Compétence')),
                ('level', models.CharField(choices=[('beginner', 'Débutant'), ('intermediate', 'Intermédiaire'), ('expert', 'Expert')], default='intermediate', max_length=20, verbose_name='Niveau')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='hr.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Habilitation / Certification')),
                ('reference', models.CharField(blank=True, max_length=50, verbose_name='Référence')),
                ('issued_date', models.DateField(blank=True, null=True, verbose_name='Délivrance')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiration')),
                ('issuing_body', models.CharField(blank=True, max_length=200, verbose_name='Organisme')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='hr.employee')),
            ],
            options={
                'verbose_name': 'Habilitation',
                'verbose_name_plural': 'Habilitations',
            },
        ),
    ]
