# Generated by Django 4.2.30 on 2026-06-19 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('hr', '0002_employeeskill_employeecertification'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePrivateFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(max_length=200, verbose_name='Nom du dossier')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_locked', models.BooleanField(default=False, verbose_name='Verrouillé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_folders', to='core.company')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='private_folder', to='hr.employee')),
            ],
            options={
                'verbose_name': 'Dossier privé salarié',
                'verbose_name_plural': 'Dossiers privés salariés',
            },
        ),
        migrations.CreateModel(
            name='EmployeePrivateDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('contract', 'Contrat de travail'), ('contract_amendment', 'Avenant contrat'), ('id_card', "Pièce d'identité"), ('rib', 'RIB'), ('address_proof', 'Justificatif domicile'), ('diploma', 'Diplôme'), ('certification', 'Certification'), ('electrical_habilitation', 'Habilitation électrique'), ('driving_license', 'Permis de conduire'), ('medical_visit', 'Visite médicale'), ('training_certificate', 'Attestation formation'), ('payslip', 'Bulletin de paie'), ('expense_report', 'Note de frais'), ('hr_letter', 'Courrier RH'), ('disciplinary', 'Sanction disciplinaire'), ('administrative', 'Document administratif'), ('other', 'Autre')], max_length=30, verbose_name='Type')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('file', models.FileField(upload_to='employee_private/', verbose_name='Fichier')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('confidentiality_level', models.CharField(choices=[('standard', 'Standard'), ('confidential', 'Confidentiel'), ('very_confidential', 'Très confidentiel'), ('hr_only', 'RH uniquement'), ('direction_only', 'Direction uniquement')], default='confidential', max_length=20, verbose_name='Confidentialité')),
                ('visible_to_employee', models.BooleanField(default=True, verbose_name='Visible par le salarié')),
                ('requires_signature', models.BooleanField(default=False, verbose_name='Signature requise')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='Signé le')),
                ('expires_at', models.DateField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_private_docs', to='core.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_documents', to='hr.employee')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='hr.employeeprivatefolder')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_private_docs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document privé salarié',
                'verbose_name_plural': 'Documents privés salariés',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocumentAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', 'Consultation'), ('download', 'Téléchargement'), ('upload', 'Upload'), ('edit', 'Modification'), ('delete', 'Suppression'), ('sign', 'Signature'), ('archive', 'Archivage')], max_length=15, verbose_name='Action')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='hr.employeeprivatedocument')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Journal d'accès document",
                'verbose_name_plural': "Journal d'accès documents",
                'ordering': ['-created_at'],
            },
        ),
    ]
