# Generated by Django 4.2.30 on 2026-06-26 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrionHAClusterLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_node_id', models.CharField(max_length=120)),
                ('lock_token', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Verrou cluster HA',
            },
        ),
        migrations.CreateModel(
            name='OrionHAFailoverEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('manual_failover', 'Bascule manuelle'), ('automatic_failover', 'Bascule automatique'), ('manual_failback', 'Retour manuel'), ('test', 'Test')], max_length=60)),
                ('status', models.CharField(choices=[('planned', 'Planifié'), ('running', 'En cours'), ('success', 'Succès'), ('failed', 'Échec'), ('cancelled', 'Annulé')], default='planned', max_length=40)),
                ('reason', models.TextField(blank=True)),
                ('steps', models.JSONField(blank=True, default=list)),
                ('result_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='OrionHANode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('role', models.CharField(choices=[('primary', 'Principal'), ('secondary', 'Secondaire'), ('observer', 'Observateur')], default='secondary', max_length=40)),
                ('status', models.CharField(choices=[('unknown', 'Inconnu'), ('healthy', 'Sain'), ('warning', 'Avertissement'), ('down', 'Hors ligne'), ('maintenance', 'Maintenance'), ('active', 'Actif'), ('passive', 'Passif'), ('promoting', 'Promotion en cours'), ('disabled', 'Désactivé')], default='unknown', max_length=40)),
                ('base_url', models.URLField(blank=True)),
                ('public_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('private_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=80)),
                ('priority', models.PositiveIntegerField(default=100, help_text='1 = serveur principal, 2 = secondaire prioritaire, 3 = secondaire de secours.')),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_current_active', models.BooleanField(default=False)),
                ('is_failover_target', models.BooleanField(default=False)),
                ('allow_auto_failover', models.BooleanField(default=True)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('last_health_payload', models.JSONField(blank=True, default=dict)),
                ('app_version', models.CharField(blank=True, max_length=80)),
                ('git_commit', models.CharField(blank=True, max_length=80)),
                ('database_role', models.CharField(default='unknown', max_length=40)),
                ('database_status', models.CharField(default='unknown', max_length=40)),
                ('replication_lag_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('media_sync_status', models.CharField(default='unknown', max_length=40)),
                ('media_last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrionHASettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failover_enabled', models.BooleanField(default=True)),
                ('automatic_failover_enabled', models.BooleanField(default=False, help_text='Ne pas activer avant tests complets.')),
                ('require_manual_confirmation', models.BooleanField(default=True)),
                ('failover_after_seconds', models.PositiveIntegerField(default=120)),
                ('max_allowed_replication_lag_seconds', models.PositiveIntegerField(default=10)),
                ('minimum_healthy_secondaries', models.PositiveIntegerField(default=1, help_text='Nombre minimal de serveurs secondaires disponibles.')),
                ('allow_failover_to_secondary_2', models.BooleanField(default=True, help_text='Autoriser la bascule vers le second serveur secondaire si le premier est indisponible.')),
                ('media_sync_enabled', models.BooleanField(default=True)),
                ('database_replication_check_enabled', models.BooleanField(default=True)),
                ('cloudflare_failover_enabled', models.BooleanField(default=False)),
                ('cloudflare_zone_id', models.CharField(blank=True, max_length=180)),
                ('cloudflare_dns_record_id', models.CharField(blank=True, max_length=180)),
                ('cloudflare_record_name', models.CharField(default='erp', max_length=180)),
                ('notify_admins', models.BooleanField(default=True)),
                ('notify_email', models.EmailField(blank=True, max_length=254)),
                ('split_brain_protection_enabled', models.BooleanField(default=True)),
                ('maintenance_mode_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_secondary_node', models.ForeignKey(blank=True, help_text='Serveur secondaire préféré pour la bascule.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_by_settings', to='high_availability.orionhanode')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paramètres haute disponibilité',
                'verbose_name_plural': 'Paramètres haute disponibilité',
            },
        ),
        migrations.CreateModel(
            name='OrionHAReplicationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database_status', models.CharField(default='unknown', max_length=40)),
                ('io_thread_running', models.BooleanField(default=False)),
                ('sql_thread_running', models.BooleanField(default=False)),
                ('seconds_behind_primary', models.PositiveIntegerField(blank=True, null=True)),
                ('primary_log_file', models.CharField(blank=True, max_length=180)),
                ('primary_log_position', models.CharField(blank=True, max_length=80)),
                ('checked_at', models.DateTimeField(auto_now=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='replication_status', to='high_availability.orionhanode')),
            ],
            options={
                'ordering': ['node__priority'],
            },
        ),
        migrations.AddIndex(
            model_name='orionhanode',
            index=models.Index(fields=['role', 'priority'], name='high_availa_role_f8a817_idx'),
        ),
        migrations.AddIndex(
            model_name='orionhanode',
            index=models.Index(fields=['is_current_active'], name='high_availa_is_curr_04849c_idx'),
        ),
        migrations.AddIndex(
            model_name='orionhanode',
            index=models.Index(fields=['is_failover_target'], name='high_availa_is_fail_87f4d1_idx'),
        ),
        migrations.AddIndex(
            model_name='orionhanode',
            index=models.Index(fields=['status'], name='high_availa_status_effb75_idx'),
        ),
        migrations.AddField(
            model_name='orionhafailoverevent',
            name='from_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='failover_from_events', to='high_availability.orionhanode'),
        ),
        migrations.AddField(
            model_name='orionhafailoverevent',
            name='started_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orionhafailoverevent',
            name='to_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='failover_to_events', to='high_availability.orionhanode'),
        ),
    ]
