# Generated by Django 4.2.30 on 2026-06-23 10:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_notification_related_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('website_url', models.URLField(blank=True, verbose_name='Site web')),
                ('industry', models.CharField(blank=True, max_length=100, verbose_name='Secteur')),
                ('country', models.CharField(default='France', max_length=100, verbose_name='Pays')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='competitors/logos/', verbose_name='Logo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to='core.company', verbose_name='Entreprise')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitors_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Concurrent',
                'verbose_name_plural': 'Concurrents',
                'ordering': ['name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CompetitorSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_url', models.URLField(verbose_name='URL du site')),
                ('site_type', models.CharField(choices=[('main_site', 'Site principal'), ('shop', 'Boutique'), ('product_page', 'Page produit'), ('category_page', 'Page catégorie'), ('blog', 'Blog'), ('landing_page', 'Landing page')], default='main_site', max_length=20, verbose_name='Type')),
                ('tracking_enabled', models.BooleanField(default=True, verbose_name='Suivi activé')),
                ('scan_frequency', models.CharField(choices=[('manual', 'Manuel uniquement'), ('daily', 'Quotidien'), ('weekly', 'Hebdomadaire'), ('monthly', 'Mensuel')], default='manual', max_length=10, verbose_name='Fréquence scan')),
                ('last_scan_at', models.DateTimeField(blank=True, null=True, verbose_name='Dernier scan')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif'), ('error', 'Erreur'), ('restricted', 'Accès restreint')], default='active', max_length=20, verbose_name='Statut')),
                ('robots_policy', models.CharField(choices=[('respect', 'Respecter robots.txt (recommandé)'), ('manual', 'Saisie manuelle uniquement'), ('api_only', 'API officielle uniquement')], default='respect', max_length=20, verbose_name='Politique robots')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='competitor_intelligence.competitor', verbose_name='Concurrent')),
            ],
            options={
                'verbose_name': 'Site concurrent',
                'verbose_name_plural': 'Sites concurrents',
                'ordering': ['site_url'],
            },
        ),
        migrations.CreateModel(
            name='CompetitorTrafficEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_monthly_visitors', models.BigIntegerField(blank=True, null=True, verbose_name='Visiteurs mensuels estimés')),
                ('estimated_daily_visitors', models.BigIntegerField(blank=True, null=True, verbose_name='Visiteurs journaliers estimés')),
                ('traffic_source', models.CharField(blank=True, max_length=100, verbose_name='Source trafic')),
                ('confidence_score', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Confiance (1-10)')),
                ('source_type', models.CharField(choices=[('manual', 'Saisie manuelle'), ('csv', 'Import CSV'), ('api', 'API externe autorisée'), ('analytics', 'Outil analytics autorisé'), ('internal', 'Estimation interne')], default='manual', max_length=20, verbose_name='Type de source')),
                ('measured_at', models.DateTimeField(auto_now_add=True, verbose_name='Mesuré le')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_estimates', to='core.company')),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_estimates', to='competitor_intelligence.competitor')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competitor_intelligence.competitorsite')),
            ],
            options={
                'verbose_name': 'Estimation trafic concurrent',
                'verbose_name_plural': 'Estimations trafic concurrents',
                'ordering': ['-measured_at'],
            },
        ),
        migrations.CreateModel(
            name='CompetitorProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=200, verbose_name='ID externe')),
                ('name', models.CharField(max_length=500, verbose_name='Nom produit')),
                ('brand', models.CharField(blank=True, max_length=200, verbose_name='Marque')),
                ('category', models.CharField(blank=True, max_length=200, verbose_name='Catégorie')),
                ('product_url', models.URLField(blank=True, verbose_name='URL produit')),
                ('image_url', models.URLField(blank=True, verbose_name='URL image')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Prix')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Devise')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Ancien prix')),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Remise %')),
                ('availability', models.CharField(choices=[('in_stock', 'En stock'), ('out_of_stock', 'Rupture de stock'), ('preorder', 'Précommande'), ('unknown', 'Inconnu')], default='unknown', max_length=20, verbose_name='Disponibilité')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Note')),
                ('review_count', models.IntegerField(default=0, verbose_name="Nombre d'avis")),
                ('detected_at', models.DateTimeField(auto_now_add=True, verbose_name='Détecté le')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='Vérifié le')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor_products', to='core.company', verbose_name='Notre entreprise')),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='competitor_intelligence.competitor', verbose_name='Concurrent')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competitor_intelligence.competitorsite', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Produit concurrent',
                'verbose_name_plural': 'Produits concurrents',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CompetitorPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Ancien prix')),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Remise %')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Devise')),
                ('availability', models.CharField(default='unknown', max_length=20, verbose_name='Disponibilité')),
                ('checked_at', models.DateTimeField(auto_now_add=True, verbose_name='Vérifié le')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor_price_history', to='core.company', verbose_name='Entreprise')),
                ('competitor_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='competitor_intelligence.competitorproduct', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Historique prix concurrent',
                'verbose_name_plural': 'Historiques prix concurrents',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='CompetitorComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Nom de la comparaison')),
                ('category', models.CharField(blank=True, max_length=200, verbose_name='Catégorie / segment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor_comparisons', to='core.company')),
                ('competitors', models.ManyToManyField(related_name='comparisons', to='competitor_intelligence.competitor', verbose_name='Concurrents comparés')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('our_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='own_comparisons', to='core.company', verbose_name='Notre entreprise dans la comparaison')),
            ],
            options={
                'verbose_name': 'Comparaison concurrentielle',
                'verbose_name_plural': 'Comparaisons concurrentielles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompetitorAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('price_drop', 'Baisse de prix'), ('price_increase', 'Hausse de prix'), ('new_product', 'Nouveau produit'), ('product_unavailable', 'Produit indisponible'), ('new_promotion', 'Nouvelle promotion'), ('traffic_change', 'Changement de trafic estimé'), ('new_advantage', 'Nouvel avantage détecté'), ('scan_failed', 'Scan échoué')], max_length=30, verbose_name='Type')),
                ('title', models.CharField(max_length=300, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('severity', models.CharField(choices=[('low', 'Faible'), ('medium', 'Modérée'), ('high', 'Haute'), ('critical', 'Critique')], default='medium', max_length=10, verbose_name='Sévérité')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor_alerts', to='core.company')),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='competitor_intelligence.competitor')),
            ],
            options={
                'verbose_name': 'Alerte concurrentielle',
                'verbose_name_plural': 'Alertes concurrentielles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompetitorAdvantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('advantage_type', models.CharField(choices=[('delivery', 'Livraison'), ('price', 'Prix'), ('quality', 'Qualité'), ('brand', 'Marque'), ('loyalty', 'Fidélité'), ('return_policy', 'Retours'), ('payment_options', 'Paiement'), ('product_range', 'Gamme produits'), ('customer_service', 'Service client'), ('social_proof', 'Preuve sociale'), ('seo', 'Référencement'), ('design', 'Design / UX'), ('technology', 'Technologie'), ('other', 'Autre')], default='other', max_length=30, verbose_name='Type')),
                ('score', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Impact (1-10)')),
                ('detected_manually', models.BooleanField(default=True, verbose_name='Saisi manuellement')),
                ('source_url', models.URLField(blank=True, verbose_name='Source URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor_advantages', to='core.company')),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advantages', to='competitor_intelligence.competitor')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advantages_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avantage concurrent',
                'verbose_name_plural': 'Avantages concurrents',
                'ordering': ['-score', '-created_at'],
            },
        ),
    ]
