# Generated by Django 4.2.30 on 2026-06-19 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('slug', models.SlugField(max_length=120, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='websites/store/categories/', verbose_name='Image')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='websites.storecategory')),
            ],
            options={
                'verbose_name': 'Catégorie boutique',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StoreOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=30, unique=True, verbose_name='N° commande')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('preparing', 'En préparation'), ('shipped', 'Expédiée'), ('delivered', 'Livrée'), ('cancelled', 'Annulée'), ('refunded', 'Remboursée')], default='pending', max_length=20, verbose_name='Statut')),
                ('payment_status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé'), ('failed', 'Échoué'), ('refunded', 'Remboursé'), ('partially_refunded', 'Partiellement remboursé')], default='pending', max_length=25, verbose_name='Paiement')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Nom client')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Email client')),
                ('customer_phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('billing_address', models.TextField(blank=True, verbose_name='Adresse facturation')),
                ('shipping_address', models.TextField(blank=True, verbose_name='Adresse livraison')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Sous-total')),
                ('tax_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='TVA')),
                ('shipping_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frais de port')),
                ('discount_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Remise')),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total TTC')),
                ('shipping_method', models.CharField(blank=True, max_length=100, verbose_name='Mode livraison')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='N° suivi')),
                ('carrier', models.CharField(blank=True, max_length=100, verbose_name='Transporteur')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='Mode paiement')),
                ('payment_reference', models.CharField(blank=True, max_length=200, verbose_name='Référence paiement')),
                ('erp_invoice_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID Facture ERP')),
                ('erp_shipment_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID Expédition ERP')),
                ('crm_customer_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID Client CRM')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_orders', to='core.company')),
            ],
            options={
                'verbose_name': 'Commande boutique',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('slug', models.SlugField(max_length=220, verbose_name='Slug')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='Description courte')),
                ('description', models.TextField(blank=True, verbose_name='Description complète')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix TTC')),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Ancien prix (barré)')),
                ('sku', models.CharField(blank=True, max_length=100, verbose_name='SKU')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Stock')),
                ('stock_from_erp', models.BooleanField(default=False, verbose_name='Stock depuis ERP')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('archived', 'Archivé'), ('out_of_stock', 'Rupture')], default='draft', max_length=15, verbose_name='Statut')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Mise en avant')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Poids (kg)')),
                ('meta_title', models.CharField(blank=True, max_length=70, verbose_name='Meta title')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='websites.storecategory')),
                ('erp_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='website_listings', to='inventory.product', verbose_name='Produit ERP lié')),
            ],
            options={
                'verbose_name': 'Produit boutique',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='website',
            name='country',
            field=models.CharField(default='France', max_length=100, verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='website',
            name='currency',
            field=models.CharField(default='EUR', max_length=3, verbose_name='Devise'),
        ),
        migrations.AddField(
            model_name='website',
            name='site_type',
            field=models.CharField(choices=[('showcase', 'Site vitrine'), ('ecommerce', 'Boutique en ligne'), ('catalog', 'Catalogue sans paiement'), ('landing', 'Landing page'), ('blog', 'Blog'), ('portal', 'Portail client'), ('event', 'Site événementiel'), ('btp', 'Site BTP'), ('commerce', 'Site commerce'), ('audio', 'Site audio / audiovisuel'), ('production', 'Site production / industrie')], default='showcase', max_length=20, verbose_name='Type de site'),
        ),
        migrations.AddField(
            model_name='website',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('construction', 'En construction'), ('published', 'Publié'), ('unpublished', 'Dépublié'), ('archived', 'Archivé')], default='draft', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='website',
            name='subdomain',
            field=models.CharField(blank=True, max_length=100, verbose_name='Sous-domaine'),
        ),
        migrations.AddField(
            model_name='websitetheme',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='website_themes', to='core.company'),
        ),
        migrations.CreateModel(
            name='StoreProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='websites/store/products/', verbose_name='Image')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Texte alternatif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='websites.storeproduct')),
            ],
            options={
                'verbose_name': 'Image produit',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_products', to='websites.website'),
        ),
        migrations.CreateModel(
            name='StoreOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Nom produit')),
                ('sku', models.CharField(blank=True, max_length=100, verbose_name='SKU')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix unitaire')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='websites.storeorder')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='websites.storeproduct')),
            ],
            options={
                'verbose_name': 'Ligne commande boutique',
            },
        ),
        migrations.AddField(
            model_name='storeorder',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_orders', to='websites.website'),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_categories', to='websites.website'),
        ),
        migrations.CreateModel(
            name='StoreCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=100, verbose_name='Clé session')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='Email client')),
                ('coupon_code', models.CharField(blank=True, max_length=50, verbose_name='Code promo')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Remise')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_carts', to='websites.website')),
            ],
            options={
                'verbose_name': 'Panier',
            },
        ),
        migrations.AlterUniqueTogether(
            name='storeproduct',
            unique_together={('website', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='storecategory',
            unique_together={('website', 'slug')},
        ),
        migrations.CreateModel(
            name='StoreCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix unitaire')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='websites.storecart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.storeproduct')),
            ],
            options={
                'verbose_name': 'Ligne panier',
                'unique_together': {('cart', 'product')},
            },
        ),
    ]
