# Generated by Django 4.2.30 on 2026-06-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0002_storecategory_storeorder_storeproduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='show_powered_by_orion',
            field=models.BooleanField(default=True, verbose_name='Afficher "Propulsé par Orion ERP"'),
        ),
    ]
