# Generated by Django 4.2.30 on 2026-06-21 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('btp', '0002_clientconversation_clientmessage_documentcategory_and_more'),
        ('websites', '0004_website_domain_media_forms_analytics'),
    ]

    operations = [
        migrations.CreateModel(
            name='BTPClientAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name='Société')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='N° devis ou facture')),
                ('status', models.CharField(choices=[('new', 'Nouvelle'), ('processing', 'En cours'), ('granted', 'Accès accordé'), ('refused', 'Refusée')], default='new', max_length=20, verbose_name='Statut')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Demande d'accès client",
                'verbose_name_plural': "Demandes d'accès client",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BTPEmergencyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('emergency_type', models.CharField(choices=[('electricite', 'Panne électrique'), ('fuite_eau', "Fuite d'eau"), ('chauffage', 'Chauffage en panne'), ('serrure', 'Porte / serrure'), ('degat_batiment', 'Dégât bâtiment'), ('autre', 'Autre urgence')], default='autre', max_length=25, verbose_name='Type urgence')),
                ('address', models.CharField(max_length=300, verbose_name='Adresse')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('description', models.TextField(verbose_name='Description')),
                ('wants_callback', models.BooleanField(default=True, verbose_name='Rappel urgent souhaité')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='websites/btp/emergency/', verbose_name='Photo')),
                ('status', models.CharField(choices=[('new', 'Nouvelle'), ('assigned', 'Assignée'), ('in_progress', 'En cours'), ('resolved', 'Résolue'), ('closed', 'Fermée')], default='new', max_length=20, verbose_name='Statut')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Urgence BTP',
                'verbose_name_plural': 'Urgences BTP',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BTPPortfolioProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=210, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('work_type', models.CharField(choices=[('electricite', 'Électricité'), ('plomberie', 'Plomberie'), ('chauffage', 'Chauffage'), ('peinture', 'Peinture'), ('maconnerie', 'Maçonnerie'), ('menuiserie', 'Menuiserie'), ('isolation', 'Isolation'), ('toiture', 'Toiture'), ('revetement', 'Revêtement sol'), ('salle_bain', 'Salle de bain'), ('cuisine', 'Cuisine'), ('renovation', 'Rénovation complète'), ('extension', 'Extension'), ('autre', 'Autre')], default='autre', max_length=20, verbose_name='Type de travaux')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('before_image', models.ImageField(blank=True, null=True, upload_to='websites/btp/portfolio/before/', verbose_name='Photo avant')),
                ('after_image', models.ImageField(blank=True, null=True, upload_to='websites/btp/portfolio/after/', verbose_name='Photo après')),
                ('customer_name', models.CharField(blank=True, max_length=100, verbose_name='Nom client (optionnel)')),
                ('customer_review', models.TextField(blank=True, verbose_name='Avis client')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Date réalisation')),
                ('is_featured', models.BooleanField(default=False, verbose_name='En vedette')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Réalisation BTP',
                'verbose_name_plural': 'Réalisations BTP',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BTPWebsiteReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('customer_city', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('work_type', models.CharField(blank=True, choices=[('electricite', 'Électricité'), ('plomberie', 'Plomberie'), ('chauffage', 'Chauffage'), ('peinture', 'Peinture'), ('maconnerie', 'Maçonnerie'), ('menuiserie', 'Menuiserie'), ('isolation', 'Isolation'), ('toiture', 'Toiture'), ('revetement', 'Revêtement sol'), ('salle_bain', 'Salle de bain'), ('cuisine', 'Cuisine'), ('renovation', 'Rénovation complète'), ('extension', 'Extension'), ('autre', 'Autre')], max_length=20, verbose_name='Type de travaux')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Note /5')),
                ('comment', models.TextField(verbose_name='Témoignage')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Avis client BTP',
                'verbose_name_plural': 'Avis clients BTP',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='websiteanalyticsevent',
            new_name='websites_we_website_cfc02f_idx',
            old_name='websites_we_website_evtype_created_idx',
        ),
        migrations.RenameIndex(
            model_name='websiteanalyticsevent',
            new_name='websites_we_website_b08fe4_idx',
            old_name='websites_we_website_path_idx',
        ),
        migrations.AlterField(
            model_name='websiteanalyticsevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='websitedomain',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='websiteform',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='websiteformfield',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='websiteformsubmission',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='websitemedia',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='btpwebsitereview',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='websites.btpportfolioproject', verbose_name='Réalisation liée'),
        ),
        migrations.AddField(
            model_name='btpwebsitereview',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='btp_reviews', to='websites.website'),
        ),
        migrations.AddField(
            model_name='btpportfolioproject',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='btp_portfolio_projects', to='websites.website'),
        ),
        migrations.AddField(
            model_name='btpemergencyrequest',
            name='guided_quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_requests', to='btp.guidedquoterequest', verbose_name='Demande guidée liée'),
        ),
        migrations.AddField(
            model_name='btpemergencyrequest',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_requests', to='websites.website'),
        ),
        migrations.AddField(
            model_name='btpclientaccessrequest',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_access_requests', to='websites.website'),
        ),
    ]
