# Generated by Django 4.2.30 on 2026-06-22 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0005_btp_portfolio_review_emergency'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteSectionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(db_index=True, help_text='Code langue ISO 639-1 : fr, en, es, de, it, nl, pt', max_length=5, verbose_name='Langue')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Titre')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Sous-titre')),
                ('content', models.TextField(blank=True, verbose_name='Contenu')),
                ('button_text', models.CharField(blank=True, max_length=100, verbose_name='Texte bouton')),
                ('button_url', models.CharField(blank=True, max_length=300, verbose_name='URL bouton')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='websites.websitesection')),
            ],
            options={
                'verbose_name': 'Traduction section',
                'verbose_name_plural': 'Traductions sections',
                'unique_together': {('section', 'language')},
            },
        ),
        migrations.CreateModel(
            name='WebsitePageTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(db_index=True, help_text='Code langue ISO 639-1 : fr, en, es, de, it, nl, pt', max_length=5, verbose_name='Langue')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(max_length=200, verbose_name='Slug')),
                ('content', models.TextField(blank=True, verbose_name='Contenu')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Meta titre')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta description')),
                ('meta_keywords', models.CharField(blank=True, max_length=300, verbose_name='Meta keywords')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='websites.websitepage')),
            ],
            options={
                'verbose_name': 'Traduction page',
                'verbose_name_plural': 'Traductions pages',
                'ordering': ['page', 'language'],
                'unique_together': {('page', 'language')},
            },
        ),
        migrations.CreateModel(
            name='WebsiteMenuItemTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(db_index=True, help_text='Code langue ISO 639-1 : fr, en, es, de, it, nl, pt', max_length=5, verbose_name='Langue')),
                ('label', models.CharField(max_length=100, verbose_name='Libelle')),
                ('url', models.CharField(blank=True, max_length=300, verbose_name='URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='websites.websitemenuitem')),
            ],
            options={
                'verbose_name': 'Traduction element menu',
                'verbose_name_plural': 'Traductions elements menu',
                'unique_together': {('menu_item', 'language')},
            },
        ),
        migrations.CreateModel(
            name='ProductTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(db_index=True, help_text='Code langue ISO 639-1 : fr, en, es, de, it, nl, pt', max_length=5, verbose_name='Langue')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('slug', models.SlugField(max_length=200, verbose_name='Slug')),
                ('short_description', models.TextField(blank=True, verbose_name='Description courte')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Meta titre')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='websites.storeproduct')),
            ],
            options={
                'verbose_name': 'Traduction produit',
                'verbose_name_plural': 'Traductions produits',
                'unique_together': {('product', 'language')},
            },
        ),
        migrations.CreateModel(
            name='BlogPostTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(db_index=True, help_text='Code langue ISO 639-1 : fr, en, es, de, it, nl, pt', max_length=5, verbose_name='Langue')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(max_length=200, verbose_name='Slug')),
                ('excerpt', models.TextField(blank=True, verbose_name='Resume')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Meta titre')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='websites.blogpost')),
            ],
            options={
                'verbose_name': 'Traduction article',
                'verbose_name_plural': 'Traductions articles',
                'unique_together': {('post', 'language')},
            },
        ),
    ]
