# Generated by Django 4.2.30 on 2026-06-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0006_websitesectiontranslation_websitepagetranslation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeorder',
            name='stripe_payment_intent',
            field=models.CharField(blank=True, max_length=200, verbose_name='Stripe Payment Intent'),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='Stripe Session ID'),
        ),
        migrations.AddField(
            model_name='storeorderitem',
            name='selected_size',
            field=models.CharField(blank=True, max_length=10, verbose_name='Taille choisie'),
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='available_sizes',
            field=models.JSONField(blank=True, default=list, help_text='Ex: ["XS","S","M","L","XL","XXL"]', verbose_name='Tailles disponibles'),
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Populaire'),
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='model_3d_file',
            field=models.FileField(blank=True, null=True, upload_to='websites/store/products/3d/', verbose_name='Modele 3D (.glb)'),
        ),
        migrations.AlterField(
            model_name='storeorder',
            name='status',
            field=models.CharField(choices=[('checkout_started', 'Checkout démarré'), ('pending', 'En attente'), ('confirmed', 'Confirmée'), ('preparing', 'En préparation'), ('shipped', 'Expédiée'), ('delivered', 'Livrée'), ('cancelled', 'Annulée'), ('refunded', 'Remboursée'), ('payment_failed', 'Paiement échoué')], default='pending', max_length=20, verbose_name='Statut'),
        ),
    ]
