# Generated by Django 4.2.30 on 2026-06-22 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_notification_related_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('websites', '0007_storeorder_stripe_payment_intent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Email client')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('clicks', models.PositiveIntegerField(default=0, verbose_name='Clics')),
                ('signups', models.PositiveIntegerField(default=0, verbose_name='Inscriptions')),
                ('orders', models.PositiveIntegerField(default=0, verbose_name='Commandes')),
                ('total_commission', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Commission totale')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_codes', to='core.company')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliate_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Code affilié',
                'verbose_name_plural': 'Codes affiliés',
            },
        ),
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('initial_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant initial')),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant restant')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Devise')),
                ('status', models.CharField(choices=[('active', 'Active'), ('used', 'Utilisée'), ('partial', 'Partiellement utilisée'), ('expired', 'Expirée'), ('cancelled', 'Annulée')], default='active', max_length=12, verbose_name='Statut')),
                ('purchased_by_email', models.EmailField(blank=True, max_length=254, verbose_name='Acheteur email')),
                ('assigned_to_email', models.EmailField(blank=True, max_length=254, verbose_name='Destinataire email')),
                ('expires_at', models.DateField(blank=True, null=True, verbose_name='Expiration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_cards', to='core.company')),
                ('purchased_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_gift_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carte cadeau',
                'verbose_name_plural': 'Cartes cadeaux',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Email client')),
                ('points_balance', models.IntegerField(default=0, verbose_name='Solde de points')),
                ('lifetime_points', models.IntegerField(default=0, verbose_name='Points cumulés vie')),
                ('tier', models.CharField(choices=[('classic', 'Classic'), ('silver', 'Silver'), ('gold', 'Gold'), ('black', 'Black')], default='classic', max_length=10, verbose_name='Niveau')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_accounts', to='core.company')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compte fidélité',
                'verbose_name_plural': 'Comptes fidélité',
                'unique_together': {('company', 'customer_email')},
            },
        ),
        migrations.CreateModel(
            name='SiecleCustomerToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True, verbose_name='Token')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='siecle_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token client SIÈCLE',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(verbose_name='Points (+ gain / − utilisation)')),
                ('transaction_type', models.CharField(choices=[('gain', 'Gain'), ('utilisation', 'Utilisation'), ('ajustement', 'Ajustement'), ('annulation', 'Annulation'), ('bonus', 'Bonus'), ('parrainage', 'Parrainage')], max_length=15, verbose_name='Type')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='Raison')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_transactions', to='core.company')),
                ('loyalty_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='websites.loyaltyaccount')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_transactions', to='websites.storeorder')),
            ],
            options={
                'verbose_name': 'Transaction fidélité',
                'verbose_name_plural': 'Transactions fidélité',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GiftCardRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='Email client')),
                ('amount_used', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant utilisé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_card_redemptions', to='core.company')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_card_redemptions', to=settings.AUTH_USER_MODEL)),
                ('gift_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='websites.giftcard')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_card_redemptions', to='websites.storeorder')),
            ],
            options={
                'verbose_name': 'Utilisation carte cadeau',
                'verbose_name_plural': 'Utilisations cartes cadeaux',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AffiliateReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referrer_email', models.EmailField(max_length=254, verbose_name='Email parrain')),
                ('referred_email', models.EmailField(max_length=254, verbose_name='Email filleul')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('validated', 'Validé'), ('rejected', 'Refusé'), ('paid', 'Payé'), ('cancelled', 'Annulé')], default='pending', max_length=12, verbose_name='Statut')),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Commission €')),
                ('points_reward', models.IntegerField(default=0, verbose_name='Points parrain')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('affiliate_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='websites.affiliatecode')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_referrals', to='core.company')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliate_referrals', to='websites.storeorder')),
                ('referrer_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parrainage',
                'verbose_name_plural': 'Parrainages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AffiliateProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Programme Parrainage SIÈCLE', max_length=100, verbose_name='Nom')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('reward_type', models.CharField(choices=[('points', 'Points'), ('discount', 'Réduction'), ('both', 'Points + Réduction')], default='points', max_length=10, verbose_name='Type récompense')),
                ('referrer_reward_value', models.DecimalField(decimal_places=2, default=100, max_digits=8, verbose_name='Récompense parrain (pts)')),
                ('referred_reward_value', models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='Réduction filleul (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_program', to='core.company')),
            ],
            options={
                'verbose_name': 'Programme affiliation',
                'verbose_name_plural': 'Programmes affiliation',
            },
        ),
    ]
