# Generated by Django 4.2.30 on 2026-06-22 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_notification_related_names'),
        ('websites', '0009_newslettersubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeproduct',
            name='is_customizable',
            field=models.BooleanField(default=False, verbose_name='Personnalisable (configurateur 3D)'),
        ),
        migrations.CreateModel(
            name='WebOrderLineCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuration_json', models.JSONField(default=dict, verbose_name='Configuration (codes)')),
                ('configuration_labels_json', models.JSONField(default=dict, verbose_name='Configuration (labels)')),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix de base')),
                ('options_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix options')),
                ('final_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix final')),
                ('order_line', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='watch_customization', to='websites.storeorderitem')),
            ],
            options={
                'verbose_name': 'Personnalisation ligne commande',
                'verbose_name_plural': 'Personnalisations lignes commande',
            },
        ),
        migrations.CreateModel(
            name='ProductCustomizationConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuration_json', models.JSONField(default=dict, verbose_name='Configuration (codes)')),
                ('configuration_labels_json', models.JSONField(default=dict, verbose_name='Configuration (labels)')),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix de base')),
                ('options_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix options')),
                ('final_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix final')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='configurator/previews/', verbose_name='Aperçu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_configurations', to='core.company')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='watch_configurations', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_configurations', to='websites.storeproduct')),
            ],
            options={
                'verbose_name': 'Configuration montre',
                'verbose_name_plural': 'Configurations montres',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductCustomizationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('case', 'Boîtier'), ('dial', 'Cadran'), ('hands', 'Aiguilles'), ('strap', 'Bracelet')], max_length=20, verbose_name='Groupe')),
                ('code', models.CharField(max_length=60, verbose_name='Code option')),
                ('label', models.CharField(max_length=120, verbose_name='Libellé')),
                ('color', models.CharField(blank=True, default='#ffffff', max_length=10, verbose_name='Couleur hex')),
                ('material', models.CharField(blank=True, max_length=30, verbose_name='Matériau')),
                ('price_delta', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Supplément (€)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customization_options', to='core.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customization_options', to='websites.storeproduct')),
            ],
            options={
                'verbose_name': 'Option personnalisation',
                'verbose_name_plural': 'Options personnalisation',
                'ordering': ['group', 'sort_order', 'id'],
                'unique_together': {('product', 'group', 'code')},
            },
        ),
    ]
