# Generated by Django 4.2.30 on 2026-06-22 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0004_remove_customer_crm_cust_co_date_idx'),
        ('core', '0006_notification_related_names'),
        ('websites', '0010_storeproduct_is_customizable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreCompleteLook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('style', models.CharField(blank=True, max_length=50, verbose_name='Style')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complete_looks', to='websites.website')),
            ],
            options={
                'verbose_name': 'Look complet',
            },
        ),
        migrations.CreateModel(
            name='StorePremiumPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('pack_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix pack')),
                ('normal_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix normal')),
                ('bonus_points', models.PositiveIntegerField(default=0, verbose_name='Points bonus')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_packs', to='websites.website')),
            ],
            options={
                'verbose_name': 'Pack premium',
            },
        ),
        migrations.CreateModel(
            name='StoreProductDrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('start_at', models.DateTimeField(verbose_name='Début')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin')),
                ('is_private', models.BooleanField(default=False, verbose_name='Privé')),
                ('access_code', models.CharField(blank=True, max_length=50, verbose_name='Code accès')),
                ('minimum_loyalty_tier', models.CharField(blank=True, max_length=20, verbose_name='Niveau min.')),
                ('status', models.CharField(choices=[('upcoming', 'À venir'), ('active', 'Actif'), ('ended', 'Terminé'), ('cancelled', 'Annulé')], default='upcoming', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_drops', to='websites.website')),
            ],
            options={
                'verbose_name': 'Drop produit',
                'ordering': ['-start_at'],
            },
        ),
        migrations.AddField(
            model_name='websitedomain',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='website_domains', to='core.company', verbose_name='Entreprise'),
        ),
        migrations.AddField(
            model_name='websitedomain',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_domains', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='websitedomain',
            name='expected_a_record',
            field=models.CharField(blank=True, max_length=45, verbose_name='IP attendue (A)'),
        ),
        migrations.AddField(
            model_name='websitedomain',
            name='force_https',
            field=models.BooleanField(default=True, verbose_name='Forcer HTTPS'),
        ),
        migrations.AddField(
            model_name='websitedomain',
            name='full_domain',
            field=models.CharField(blank=True, editable=False, max_length=253, verbose_name='Domaine complet'),
        ),
        migrations.AddField(
            model_name='websitedomain',
            name='is_active_flag',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AddField(
            model_name='websitedomain',
            name='redirect_to_primary',
            field=models.BooleanField(default=False, verbose_name='Rediriger vers domaine principal'),
        ),
        migrations.AddField(
            model_name='websitedomain',
            name='redirect_www',
            field=models.BooleanField(default=False, verbose_name='Rediriger www → racine'),
        ),
        migrations.AddField(
            model_name='websitedomain',
            name='ssl_issued_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='SSL émis le'),
        ),
        migrations.AddField(
            model_name='websitedomain',
            name='target_type',
            field=models.CharField(choices=[('website', 'Site web / vitrine'), ('shop', 'Boutique en ligne'), ('client_portal', 'Portail client'), ('erp', 'Orion ERP'), ('landing_page', 'Landing page'), ('blog', 'Blog')], default='website', max_length=20, verbose_name='Cible'),
        ),
        migrations.AddField(
            model_name='websitedomain',
            name='verification_status',
            field=models.CharField(choices=[('not_started', 'Non démarré'), ('pending', 'En cours'), ('verified', 'Vérifié'), ('failed', 'Échec')], default='not_started', max_length=20, verbose_name='Statut vérification'),
        ),
        migrations.AlterField(
            model_name='websitedomain',
            name='domain_type',
            field=models.CharField(choices=[('root', 'Domaine racine'), ('subdomain', 'Sous-domaine'), ('www', 'Sous-domaine www'), ('test', 'Domaine de test'), ('temporary', 'Domaine temporaire Orion')], default='subdomain', max_length=20, verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='StyleIdentityResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=100)),
                ('identity', models.CharField(choices=[('minimal', 'Minimal'), ('nuit', 'Nuit'), ('signature', 'Signature'), ('urbain', 'Urbain'), ('elegance', 'Élégance'), ('audace', 'Audace')], max_length=20, verbose_name='Identité')),
                ('quiz_answers', models.JSONField(default=dict, verbose_name='Réponses')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.customer')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_results', to='websites.website')),
            ],
            options={
                'verbose_name': 'Résultat quiz identité',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreProductDropItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_available', models.PositiveIntegerField(default=0, verbose_name='Qté disponible')),
                ('quantity_sold', models.PositiveIntegerField(default=0, verbose_name='Qté vendue')),
                ('is_preorder', models.BooleanField(default=False, verbose_name='Précommande')),
                ('drop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drop_items', to='websites.storeproductdrop')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.storeproduct')),
            ],
        ),
        migrations.CreateModel(
            name='StorePremiumPackItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pack_items', to='websites.storepremiumpack')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.storeproduct')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='StoreCompleteLookItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='Catégorie')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('look', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='look_items', to='websites.storecompletelook')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.storeproduct')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='SavedWatchConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Nom de la config')),
                ('configuration_json', models.JSONField(default=dict, verbose_name='Configuration')),
                ('configuration_labels_json', models.JSONField(default=dict, verbose_name='Labels')),
                ('final_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix final')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='watches/saved/', verbose_name='Aperçu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_watches', to='crm.customer')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='websites.storeproduct')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_watch_configs', to='websites.website')),
            ],
            options={
                'verbose_name': 'Config montre sauvegardée',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Titre')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='products/videos/', verbose_name='Vidéo')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='products/video_thumbs/', verbose_name='Miniature')),
                ('video_type', models.CharField(choices=[('matiere', 'Matière'), ('porte', 'Porté'), ('details', 'Détails'), ('3d', '3D'), ('fabrication', 'Fabrication')], max_length=20, verbose_name='Type')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='websites.storeproduct')),
            ],
            options={
                'verbose_name': 'Vidéo produit',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('mission_type', models.CharField(choices=[('create_account', 'Créer un compte'), ('first_order', 'Première commande'), ('share_affiliate', 'Partager lien affilié'), ('validated_review', 'Avis produit validé'), ('birthday', 'Anniversaire'), ('order_three_universes', 'Commander 3 univers'), ('complete_identity', "Compléter l'identité SIÈCLE"), ('upload_community', 'Poster un look communauté')], max_length=50, verbose_name='Type')),
                ('points_reward', models.PositiveIntegerField(default=0, verbose_name='Points offerts')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_missions', to='core.company')),
            ],
            options={
                'verbose_name': 'Mission fidélité',
                'ordering': ['points_reward'],
            },
        ),
        migrations.CreateModel(
            name='DomainRedirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_path', models.CharField(default='/', help_text='Ex: / pour tout le domaine, /ancienne-page pour une page spécifique', max_length=500, verbose_name='Chemin source')),
                ('target_url', models.CharField(help_text='Ex: https://nouveaudomaine.fr ou /nouvelle-page', max_length=500, verbose_name='URL cible')),
                ('redirect_type', models.CharField(choices=[('301', 'Redirection permanente (301)'), ('302', 'Redirection temporaire (302)')], default='301', max_length=3, verbose_name='Type')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('hit_count', models.PositiveIntegerField(default=0, verbose_name='Utilisations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_redirects', to='core.company', verbose_name='Entreprise')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redirects', to='websites.websitedomain', verbose_name='Domaine source')),
            ],
            options={
                'verbose_name': 'Redirection domaine',
                'verbose_name_plural': 'Redirections domaine',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DomainDNSRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('A', 'A — Adresse IPv4'), ('AAAA', 'AAAA — Adresse IPv6'), ('CNAME', 'CNAME — Alias'), ('TXT', 'TXT — Texte'), ('MX', 'MX — Mail'), ('CAA', 'CAA — Autorité certificat')], max_length=10, verbose_name='Type')),
                ('name', models.CharField(help_text='Ex: @, www, _orion-verification', max_length=253, verbose_name='Nom')),
                ('expected_value', models.CharField(max_length=500, verbose_name='Valeur attendue')),
                ('detected_value', models.CharField(blank=True, max_length=500, verbose_name='Valeur détectée')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('valid', 'Valide'), ('invalid', 'Invalide'), ('missing', 'Manquant')], default='pending', max_length=20, verbose_name='Statut')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='Dernier check')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dns_records', to='websites.websitedomain', verbose_name='Domaine')),
            ],
            options={
                'verbose_name': 'Enregistrement DNS',
                'verbose_name_plural': 'Enregistrements DNS',
                'ordering': ['record_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DomainConnectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(blank=True, help_text='Copie pour historique après suppression du domaine', max_length=253, verbose_name='Nom domaine')),
                ('action', models.CharField(choices=[('created', 'Domaine créé'), ('dns_checked', 'DNS vérifié (tentative)'), ('dns_verified', 'DNS validé'), ('dns_failed', 'DNS invalide'), ('ssl_requested', 'SSL demandé'), ('ssl_active', 'SSL actif'), ('ssl_expired', 'SSL expiré'), ('set_primary', 'Défini comme principal'), ('disabled', 'Désactivé'), ('enabled', 'Réactivé'), ('deleted', 'Supprimé'), ('redirect_created', 'Redirection créée'), ('redirect_deleted', 'Redirection supprimée'), ('target_changed', 'Cible modifiée'), ('error', 'Erreur')], max_length=30, verbose_name='Action')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Détails')),
                ('status', models.CharField(choices=[('success', 'Succès'), ('error', 'Erreur'), ('info', 'Info'), ('warning', 'Avertissement')], default='info', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain_logs', to='core.company', verbose_name='Entreprise')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domain_logs', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='websites.websitedomain', verbose_name='Domaine')),
            ],
            options={
                'verbose_name': 'Journal domaine',
                'verbose_name_plural': 'Journal domaines',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerStyleProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_universe', models.CharField(blank=True, max_length=50, verbose_name='Univers préféré')),
                ('clothing_size', models.CharField(blank=True, max_length=10, verbose_name='Taille vêtement')),
                ('fit_preference', models.CharField(blank=True, choices=[('slim', 'Ajusté'), ('regular', 'Normal'), ('oversized', 'Oversize')], max_length=20, verbose_name='Coupe préférée')),
                ('body_type', models.CharField(blank=True, max_length=50, verbose_name='Morphologie')),
                ('skin_type', models.CharField(blank=True, max_length=50, verbose_name='Type de peau')),
                ('skin_tone', models.CharField(blank=True, choices=[('very_light', 'Très claire'), ('light', 'Claire'), ('medium', 'Medium'), ('tan', 'Mate'), ('dark', 'Foncée'), ('very_dark', 'Très foncée')], max_length=20, verbose_name='Carnation')),
                ('beauty_undertone', models.CharField(blank=True, choices=[('cool', 'Froid'), ('neutral', 'Neutre'), ('warm', 'Chaud')], max_length=10, verbose_name='Sous-ton')),
                ('style_identity', models.CharField(blank=True, max_length=50, verbose_name='Identité SIÈCLE')),
                ('favorite_colors', models.JSONField(default=list, verbose_name='Couleurs préférées')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='style_profile', to='crm.customer')),
            ],
            options={
                'verbose_name': 'Profil style client',
            },
        ),
        migrations.CreateModel(
            name='CustomerShadeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skin_tone', models.CharField(blank=True, max_length=20)),
                ('undertone', models.CharField(blank=True, max_length=10)),
                ('finish_pref', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shade_profile', to='crm.customer')),
            ],
            options={
                'verbose_name': 'Profil carnation',
            },
        ),
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=100, verbose_name='Nom affiché')),
                ('image', models.ImageField(blank=True, null=True, upload_to='community/posts/', verbose_name='Image')),
                ('caption', models.TextField(blank=True, verbose_name='Légende')),
                ('universe_tag', models.CharField(blank=True, max_length=20, verbose_name='Univers')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('published', 'Publié'), ('rejected', 'Refusé'), ('archived', 'Archivé')], default='pending', max_length=20, verbose_name='Statut')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='Likes')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Mis en avant')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.customer')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to='websites.website')),
            ],
            options={
                'verbose_name': 'Post communauté',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CloudflareAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_token', models.CharField(help_text='Token API avec permissions DNS Edit sur les zones concernées', max_length=200, verbose_name='Token API Cloudflare')),
                ('account_id', models.CharField(blank=True, max_length=100, verbose_name='ID compte Cloudflare')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email Cloudflare')),
                ('label', models.CharField(blank=True, default='Principal', max_length=100, verbose_name='Libellé')),
                ('is_active', models.BooleanField(default=False, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloudflare_accounts', to='core.company', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': 'Compte Cloudflare',
                'verbose_name_plural': 'Comptes Cloudflare',
            },
        ),
        migrations.CreateModel(
            name='BeautyQuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_answers', models.JSONField(default=dict, verbose_name='Réponses')),
                ('recommended_products', models.JSONField(default=list, verbose_name='Produits recommandés')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.customer')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beauty_quiz_results', to='websites.website')),
            ],
            options={
                'verbose_name': 'Résultat quiz beauté',
            },
        ),
        migrations.CreateModel(
            name='AbandonedCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('cart_json', models.JSONField(default=list, verbose_name='Contenu panier')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('reminded', 'Relancé'), ('recovered', 'Récupéré'), ('expired', 'Expiré')], default='active', max_length=20, verbose_name='Statut')),
                ('last_activity_at', models.DateTimeField(verbose_name='Dernière activité')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.customer')),
                ('recovered_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='websites.storeorder')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abandoned_carts', to='websites.website')),
            ],
            options={
                'verbose_name': 'Panier abandonné',
                'ordering': ['-last_activity_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerMissionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('points_awarded', models.PositiveIntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_progresses', to='crm.customer')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.loyaltymission')),
            ],
            options={
                'verbose_name': 'Progression mission',
                'unique_together': {('customer', 'mission')},
            },
        ),
        migrations.CreateModel(
            name='CustomerBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_type', models.CharField(choices=[('client_signature', 'Client Signature'), ('client_gold', 'Client Gold'), ('client_black', 'Client Black'), ('ambassadeur', 'Ambassadeur SIÈCLE'), ('collectionneur', 'Collectionneur'), ('early_access', 'Early Access'), ('beauty_insider', 'Beauty Insider'), ('watch_creator', 'Watch Creator'), ('style_architect', 'Style Architect')], max_length=50, verbose_name='Type')),
                ('label', models.CharField(max_length=100, verbose_name='Label')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_badges', to='core.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='crm.customer')),
            ],
            options={
                'verbose_name': 'Badge client',
                'unique_together': {('customer', 'badge_type')},
            },
        ),
    ]
