# Generated by Django 4.2.30 on 2026-06-22 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_notification_related_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('websites', '0006_websitesectiontranslation_websitepagetranslation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('native_name', models.CharField(max_length=100, verbose_name='Nom natif')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_default', models.BooleanField(default=False, verbose_name='Par defaut')),
                ('is_rtl', models.BooleanField(default=False, verbose_name='Droite a gauche')),
                ('flag_icon', models.CharField(blank=True, help_text='Emoji drapeau, ex : 🇫🇷', max_length=10, verbose_name='Icone drapeau')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Langue',
                'verbose_name_plural': 'Langues',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteLanguageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_language_switcher', models.BooleanField(default=True, verbose_name='Afficher selecteur de langue')),
                ('use_language_prefix_urls', models.BooleanField(default=False, verbose_name='URLs avec prefixe langue (/fr/, /en/)')),
                ('auto_redirect_by_browser', models.BooleanField(default=False, verbose_name='Redirection auto selon navigateur')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_websites', to='translations.language', verbose_name='Langue par defaut')),
                ('enabled_languages', models.ManyToManyField(blank=True, related_name='enabled_for_websites', to='translations.language', verbose_name='Langues activees')),
                ('website', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='language_settings', to='websites.website', verbose_name='Site web')),
            ],
            options={
                'verbose_name': 'Parametres langue site web',
                'verbose_name_plural': 'Parametres langue sites web',
            },
        ),
        migrations.CreateModel(
            name='CompanyLanguageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_users_to_change_language', models.BooleanField(default=True, verbose_name='Permettre aux utilisateurs de changer la langue')),
                ('auto_detect_browser_language', models.BooleanField(default=False, verbose_name='Detection auto langue navigateur')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='language_settings', to='core.company', verbose_name='Entreprise')),
                ('default_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_companies', to='translations.language', verbose_name='Langue par defaut')),
                ('enabled_languages', models.ManyToManyField(blank=True, related_name='enabled_for_companies', to='translations.language', verbose_name='Langues activees')),
            ],
            options={
                'verbose_name': 'Parametres langue entreprise',
                'verbose_name_plural': 'Parametres langue entreprises',
            },
        ),
        migrations.CreateModel(
            name='UserLanguagePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Entreprise')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translations.language', verbose_name='Langue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_preferences', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Preference langue utilisateur',
                'verbose_name_plural': 'Preferences langue utilisateurs',
                'unique_together': {('user', 'company')},
            },
        ),
        migrations.CreateModel(
            name='InterfaceTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, verbose_name='Cle')),
                ('source_text', models.TextField(verbose_name='Texte source')),
                ('translated_text', models.TextField(verbose_name='Traduction')),
                ('context', models.CharField(blank=True, max_length=200, verbose_name='Contexte')),
                ('module', models.CharField(blank=True, help_text='Ex: crm, sales, btp, dashboard', max_length=100, verbose_name='Module')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verifiee')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Entreprise')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translations.language', verbose_name='Langue')),
            ],
            options={
                'verbose_name': 'Traduction interface',
                'verbose_name_plural': 'Traductions interface',
                'ordering': ['module', 'key'],
                'unique_together': {('company', 'key', 'language')},
            },
        ),
    ]
