# Generated by Django 4.2.30 on 2026-06-23 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0004_remove_customer_crm_cust_co_date_idx'),
        ('core', '0006_notification_related_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_key', models.CharField(blank=True, max_length=40)),
                ('title', models.CharField(max_length=180)),
                ('incident_type', models.CharField(choices=[('site_incident', 'Incident chantier'), ('customer_return', 'Retour client'), ('defective_product', 'Produit défectueux'), ('invoice_error', 'Erreur facture'), ('delivery_delay', 'Retard livraison'), ('complaint', 'Réclamation'), ('non_conformity', 'Non-conformité'), ('other', 'Autre')], max_length=80)),
                ('severity', models.CharField(choices=[('critical', 'Critique'), ('high', 'Élevée'), ('normal', 'Normale'), ('low', 'Faible')], default='normal', max_length=30)),
                ('status', models.CharField(choices=[('open', 'Ouverte'), ('in_progress', 'En cours'), ('resolved', 'Résolue'), ('closed', 'Clôturée')], default='open', max_length=40)),
                ('description', models.TextField(blank=True)),
                ('cause', models.TextField(blank=True)),
                ('corrective_action', models.TextField(blank=True)),
                ('due_at', models.DateField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=80)),
                ('related_object_id', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_quality_incidents', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_incidents', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quality_incidents', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_incidents', to='crm.customer')),
            ],
            options={
                'verbose_name': 'Incident qualité',
                'verbose_name_plural': 'Incidents qualité',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QualityIncidentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='quality_incidents.qualityincident')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commentaire incident',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='qualityincident',
            index=models.Index(fields=['company', 'status', 'severity'], name='quality_inc_company_1b03ce_idx'),
        ),
    ]
