# Generated by Django 4.2.30 on 2026-06-27 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_notification_related_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrionAIConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Nouvelle conversation', max_length=220)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archivée'), ('deleted', 'Supprimée')], default='active', max_length=40)),
                ('context_module', models.CharField(blank=True, help_text='Exemple : orders, products, shop_settings, system_health', max_length=80)),
                ('brand_key', models.CharField(blank=True, max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to='core.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='OrionAIMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('system', 'Système'), ('user', 'Utilisateur'), ('assistant', 'Assistant'), ('tool', 'Outil')], max_length=40)),
                ('content', models.TextField(blank=True)),
                ('provider', models.CharField(blank=True, max_length=40)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('tool_name', models.CharField(blank=True, max_length=120)),
                ('tool_call_id', models.CharField(blank=True, max_length=180)),
                ('token_input', models.PositiveIntegerField(default=0)),
                ('token_output', models.PositiveIntegerField(default=0)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='orion_ai.orionaiconversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrionAIToolCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('planned', 'Planifié'), ('running', 'En cours'), ('success', 'Succès'), ('failed', 'Échec'), ('blocked', 'Bloqué')], default='planned', max_length=40)),
                ('arguments', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('is_write_action', models.BooleanField(default=False)),
                ('is_dangerous_action', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_calls', to='orion_ai.orionaiconversation')),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_calls', to='orion_ai.orionaimessage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrionAISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_global', models.BooleanField(default=False)),
                ('ai_enabled', models.BooleanField(default=True)),
                ('default_provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('local', 'Local (Ollama)'), ('disabled', 'Désactivé')], default='openai', max_length=40)),
                ('default_model', models.CharField(default='gpt-4.1-mini', max_length=120)),
                ('temperature', models.DecimalField(decimal_places=2, default=0.2, max_digits=4)),
                ('max_input_chars', models.PositiveIntegerField(default=20000)),
                ('max_history_messages', models.PositiveIntegerField(default=20)),
                ('allow_tools', models.BooleanField(default=True)),
                ('allow_erp_read_tools', models.BooleanField(default=True)),
                ('allow_erp_write_tools', models.BooleanField(default=False)),
                ('allow_dangerous_actions', models.BooleanField(default=False)),
                ('require_confirmation_for_write_actions', models.BooleanField(default=True)),
                ('log_conversations', models.BooleanField(default=True)),
                ('log_tool_calls', models.BooleanField(default=True)),
                ('redact_sensitive_data', models.BooleanField(default=True)),
                ('ai_name', models.CharField(default='Assistant Orion', max_length=120)),
                ('system_prompt_extra', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_settings', to='core.company')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paramètres IA Orion',
                'verbose_name_plural': 'Paramètres IA Orion',
            },
        ),
        migrations.CreateModel(
            name='OrionAIProposedAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('description', models.TextField(blank=True)),
                ('action_code', models.CharField(max_length=120)),
                ('arguments', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('executed', 'Exécutée'), ('cancelled', 'Annulée'), ('failed', 'Échec')], default='pending', max_length=40)),
                ('is_write_action', models.BooleanField(default=True)),
                ('is_dangerous_action', models.BooleanField(default=False)),
                ('requires_confirmation', models.BooleanField(default=True)),
                ('created_by_ai', models.BooleanField(default=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_ai_actions', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_actions', to='orion_ai.orionaiconversation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrionAIAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('chat_message', 'Message IA'), ('tool_call', 'Appel outil'), ('action_proposed', 'Action proposée'), ('action_confirmed', 'Action confirmée'), ('action_executed', 'Action exécutée'), ('action_blocked', 'Action bloquée'), ('safety_block', 'Blocage sécurité'), ('settings_changed', 'Paramètres modifiés')], max_length=80)),
                ('title', models.CharField(max_length=220)),
                ('description', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrionAIMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_key', models.CharField(blank=True, max_length=40)),
                ('scope', models.CharField(choices=[('global', 'Global'), ('company', 'Entreprise'), ('user', 'Utilisateur'), ('brand', 'Marque')], max_length=40)),
                ('key', models.CharField(max_length=120)),
                ('value', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_sensitive', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ai_memories', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scope', 'key'],
                'unique_together': {('company', 'user', 'brand_key', 'scope', 'key')},
            },
        ),
    ]
