# Generated by Django 4.2.30 on 2026-06-23 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_notification_related_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('trigger_type', models.CharField(choices=[('invoice_overdue', 'Facture en retard'), ('stock_low', 'Stock faible'), ('new_customer', 'Nouveau client'), ('new_order', 'Nouvelle commande'), ('order_paid', 'Commande payée'), ('quote_not_followed', 'Devis sans suite'), ('domain_error', 'Erreur domaine'), ('backup_failed', 'Sauvegarde échouée'), ('employee_missing_timesheet', 'Pointage manquant'), ('project_starts_tomorrow', 'Chantier démarre demain'), ('cart_abandoned', 'Panier abandonné'), ('scheduled', 'Planifié (CRON)'), ('manual', 'Déclenchement manuel')], max_length=100)),
                ('conditions', models.JSONField(blank=True, default=list)),
                ('actions', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('run_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_automation_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Règle d'automatisation",
                'verbose_name_plural': "Règles d'automatisation",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('success', 'Succès'), ('failed', 'Échoué'), ('skipped', 'Ignoré')], default='pending', max_length=30)),
                ('trigger_payload', models.JSONField(blank=True, default=dict)),
                ('result_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_runs', to='core.company')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='smart_automations.automationrule')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_automation_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exécution automatisation',
                'verbose_name_plural': 'Exécutions automatisations',
                'ordering': ['-started_at'],
            },
        ),
    ]
