# Generated by Django 4.2.30 on 2026-06-23 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_notification_related_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('code', models.CharField(max_length=100)),
                ('object_type', models.CharField(choices=[('quote', 'Devis'), ('invoice', 'Facture'), ('purchase_order', 'Commande achat'), ('leave_request', 'Congé'), ('expense_report', 'Note de frais'), ('refund', 'Remboursement'), ('website_publish', 'Publication site'), ('customer_review', 'Avis client'), ('portal_signup', 'Inscription portail'), ('document', 'Document'), ('custom', 'Personnalisé')], max_length=80)),
                ('steps', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_templates', to='core.company')),
            ],
            options={
                'verbose_name': 'Modèle de workflow',
                'verbose_name_plural': 'Modèles de workflow',
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(max_length=80)),
                ('object_id', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('cancelled', 'Annulé')], default='pending', max_length=30)),
                ('current_step_index', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_instances', to='core.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflow_instances', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow_center.workflowtemplate')),
            ],
            options={
                'verbose_name': 'Instance workflow',
                'verbose_name_plural': 'Instances workflow',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approve', 'Approuver'), ('reject', 'Rejeter'), ('comment', 'Commenter'), ('cancel', 'Annuler')], max_length=40)),
                ('step_index', models.PositiveIntegerField(default=0)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='workflow_center.workflowinstance')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Action workflow',
                'verbose_name_plural': 'Actions workflow',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['company', 'status'], name='workflow_ce_company_ad225d_idx'),
        ),
    ]
