# Generated by Django 4.2.30 on 2026-06-23 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0004_remove_customer_crm_cust_co_date_idx'),
        ('hr', '0004_employee_user_related_name'),
        ('core', '0006_notification_related_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('event_type', models.CharField(choices=[('employee_shift', 'Vacation salarié'), ('site_visit', 'Visite chantier'), ('customer_appointment', 'RDV client'), ('intervention', 'Intervention'), ('leave', 'Congé'), ('training', 'Formation'), ('delivery', 'Livraison'), ('meeting', 'Réunion'), ('other', 'Autre')], max_length=80)),
                ('project_id', models.CharField(blank=True, max_length=80)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('planned', 'Planifié'), ('confirmed', 'Confirmé'), ('in_progress', 'En cours'), ('done', 'Terminé'), ('cancelled', 'Annulé')], default='planned', max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_events', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_planning_events', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_events', to='crm.customer')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_events', to='hr.employee')),
            ],
            options={
                'verbose_name': 'Événement planning',
                'verbose_name_plural': 'Événements planning',
                'ordering': ['start_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanningConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conflict_type', models.CharField(choices=[('double_booking', 'Double réservation'), ('overload', 'Surcharge'), ('leave_overlap', 'Chevauchement congé'), ('other', 'Autre')], max_length=80)),
                ('message', models.TextField()),
                ('severity', models.CharField(default='normal', max_length=30)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_conflicts', to='core.company')),
                ('conflicting_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conflicted_by', to='smart_planning.planningevent')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='smart_planning.planningevent')),
            ],
            options={
                'verbose_name': 'Conflit planning',
                'verbose_name_plural': 'Conflits planning',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='planningevent',
            index=models.Index(fields=['company', 'start_at', 'end_at'], name='smart_plann_company_4135aa_idx'),
        ),
        migrations.AddIndex(
            model_name='planningevent',
            index=models.Index(fields=['company', 'employee', 'start_at'], name='smart_plann_company_54544c_idx'),
        ),
    ]
