# Generated by Django 4.2.30 on 2026-06-23 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_notification_related_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_key', models.CharField(blank=True, max_length=40)),
                ('insight_type', models.CharField(choices=[('opportunity', 'Opportunité'), ('risk', 'Risque'), ('trend', 'Tendance'), ('anomaly', 'Anomalie'), ('recommendation', 'Recommandation')], max_length=40)),
                ('title', models.CharField(max_length=180)),
                ('message', models.TextField()),
                ('source_module', models.CharField(blank=True, max_length=80)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('score', models.FloatField(default=0.0)),
                ('is_read', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_insights', to='core.company')),
            ],
            options={
                'verbose_name': 'Insight analytique',
                'verbose_name_plural': 'Insights analytiques',
                'ordering': ['-score', '-created_at'],
                'indexes': [models.Index(fields=['company', 'insight_type', 'is_dismissed'], name='predictive__company_711237_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_key', models.CharField(blank=True, max_length=40)),
                ('forecast_type', models.CharField(choices=[('revenue', "Chiffre d'affaires"), ('cash_flow', 'Trésorerie'), ('sales_volume', 'Volume ventes'), ('churn_risk', 'Risque churn'), ('inventory_demand', 'Demande stock'), ('project_delay', 'Retard projet'), ('employee_load', 'Charge salarié'), ('custom', 'Personnalisé')], max_length=80)),
                ('period', models.CharField(max_length=20)),
                ('value', models.DecimalField(decimal_places=4, max_digits=18)),
                ('lower_bound', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('upper_bound', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('confidence', models.FloatField(default=0.8)),
                ('model_version', models.CharField(default='v1', max_length=40)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_forecasts', to='core.company')),
            ],
            options={
                'verbose_name': 'Prévision analytique',
                'verbose_name_plural': 'Prévisions analytiques',
                'ordering': ['-computed_at'],
                'indexes': [models.Index(fields=['company', 'forecast_type', 'period'], name='predictive__company_664fa9_idx')],
                'unique_together': {('company', 'forecast_type', 'period', 'brand_key')},
            },
        ),
    ]
