# Generated by Django 4.2.30 on 2026-06-22 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_notification_related_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateSaaSSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_mode_enabled', models.BooleanField(default=True)),
                ('public_signup_enabled', models.BooleanField(default=False)),
                ('default_language', models.CharField(default='fr', max_length=10)),
                ('default_timezone', models.CharField(default='Europe/Paris', max_length=50)),
                ('default_currency', models.CharField(default='EUR', max_length=3)),
                ('allow_company_database_creation', models.BooleanField(default=True)),
                ('allow_domain_management', models.BooleanField(default=True)),
                ('allow_module_management', models.BooleanField(default=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres SaaS privé',
            },
        ),
        migrations.CreateModel(
            name='CompanyBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_type', models.CharField(choices=[('full', 'Complète'), ('database', 'Base de données'), ('media', 'Médias'), ('documents', 'Documents')], default='database', max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'En cours'), ('success', 'Réussie'), ('error', 'Erreur')], default='pending', max_length=20)),
                ('size', models.BigIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_backups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sauvegarde entreprise',
                'verbose_name_plural': 'Sauvegardes entreprise',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_code', models.CharField(max_length=50)),
                ('module_name', models.CharField(max_length=100)),
                ('is_enabled', models.BooleanField(default=False)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('settings_json', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='core.company')),
                ('enabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enabled_modules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Module entreprise',
                'verbose_name_plural': 'Modules entreprise',
                'ordering': ['module_code'],
                'unique_together': {('company', 'module_code')},
            },
        ),
    ]
