# Generated by Django 4.2.16 on 2026-06-18 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyé'), ('confirmed', 'Confirmé'), ('received', 'Reçu'), ('partial', 'Partiellement reçu'), ('cancelled', 'Annulé')], default='draft', max_length=20)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('expected_delivery', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('total_ht', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='core.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commande achat',
                'verbose_name_plural': 'Commandes achat',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_type', models.CharField(choices=[('individual', 'Particulier'), ('company', 'Société')], default='company', max_length=20)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(max_length=200, verbose_name='Nom / Raison sociale')),
                ('contact_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('country', models.CharField(default='France', max_length=100)),
                ('siret', models.CharField(blank=True, max_length=14)),
                ('vat_number', models.CharField(blank=True, max_length=20)),
                ('payment_terms', models.PositiveIntegerField(default=30)),
                ('lead_time_days', models.PositiveIntegerField(default=7)),
                ('discount_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='core.company')),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=30)),
                ('supplier_ref', models.CharField(blank=True, max_length=50, verbose_name='Référence fournisseur')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('paid', 'Payée'), ('overdue', 'En retard'), ('disputed', 'Contestée')], default='pending', max_length=20)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('total_ht', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_tva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_invoices', to='core.company')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchases.purchaseorder')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='purchases.supplier')),
            ],
            options={
                'verbose_name': 'Facture fournisseur',
                'verbose_name_plural': 'Factures fournisseurs',
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='purchases.supplier'),
        ),
    ]
