# Generated by Django 4.2.30 on 2026-06-19 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPortalAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('crm_customer_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID client CRM')),
                ('can_upload', models.BooleanField(default=True, verbose_name='Peut uploader des documents')),
                ('can_message', models.BooleanField(default=True, verbose_name='Peut envoyer des messages')),
                ('can_request_changes', models.BooleanField(default=True, verbose_name='Peut demander des modifications')),
                ('can_report_reservations', models.BooleanField(default=True, verbose_name='Peut signaler des réserves')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_from_guided_quote', models.BooleanField(default=False, verbose_name='Créé depuis demande guidée')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_accounts', to='core.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portal_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compte portail client',
                'verbose_name_plural': 'Comptes portail client',
            },
        ),
    ]
