# Generated by Django 4.2.30 on 2026-06-23 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_notification_related_names'),
        ('portals', '0002_clientportalaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientportalaccount',
            name='created_from_signup',
            field=models.BooleanField(default=False, verbose_name='Créé depuis inscription libre'),
        ),
        migrations.AddField(
            model_name='clientportalaccount',
            name='is_approved',
            field=models.BooleanField(default=True, verbose_name='Approuvé'),
        ),
        migrations.AddField(
            model_name='clientportalaccount',
            name='is_email_verified',
            field=models.BooleanField(default=False, verbose_name='Email vérifié'),
        ),
        migrations.CreateModel(
            name='ClientPortalSignupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name="Nom de l'entreprise")),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('password_hash', models.CharField(max_length=256, verbose_name='Mot de passe (hashé)')),
                ('status', models.CharField(choices=[('pending_email_verification', 'En attente de vérification email'), ('pending_approval', 'En attente de validation'), ('approved', 'Approuvé'), ('rejected', 'Refusé'), ('converted', 'Converti en compte'), ('expired', 'Expiré')], db_index=True, default='pending_email_verification', max_length=30, verbose_name='Statut')),
                ('email_verified', models.BooleanField(default=False, verbose_name='Email vérifié')),
                ('email_verification_token', models.CharField(blank=True, max_length=64, unique=True, verbose_name='Token de vérification')),
                ('email_verification_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Email de vérification envoyé le')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Validé le')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='Refusé le')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Raison du refus')),
                ('linked_customer_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID client CRM')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mise à jour le')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_signups', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signup_requests', to='core.company', verbose_name='Entreprise')),
                ('linked_portal_account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signup_request', to='portals.clientportalaccount', verbose_name='Compte portail créé')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_signups', to=settings.AUTH_USER_MODEL, verbose_name='Refusé par')),
            ],
            options={
                'verbose_name': "Demande d'inscription client",
                'verbose_name_plural': "Demandes d'inscription client",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientPortalSignupAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Adresse IP')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
            ],
            options={
                'verbose_name': "Tentative d'inscription",
                'verbose_name_plural': "Tentatives d'inscription",
                'indexes': [models.Index(fields=['ip_address', 'created_at'], name='signup_attempt_ip_idx'), models.Index(fields=['email', 'created_at'], name='signup_attempt_email_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClientPortalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_client_registration', models.BooleanField(default=True, verbose_name='Autoriser les inscriptions clients')),
                ('registration_requires_approval', models.BooleanField(default=True, verbose_name='Validation admin requise')),
                ('registration_requires_email_verification', models.BooleanField(default=True, verbose_name='Vérification email obligatoire')),
                ('allow_unknown_clients', models.BooleanField(default=True, verbose_name='Autoriser les emails inconnus du CRM')),
                ('default_registered_client_status', models.CharField(default='pending', max_length=20, verbose_name='Statut par défaut')),
                ('notify_admin_on_registration', models.BooleanField(default=True, verbose_name='Notifier les admins à chaque inscription')),
                ('registration_intro_text', models.TextField(blank=True, default='', verbose_name="Texte d'introduction inscription")),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portal_settings', to='core.company', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': 'Paramètres portail client',
                'verbose_name_plural': 'Paramètres portail client',
            },
        ),
        migrations.CreateModel(
            name='ClientPortalActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('signup_created', 'Inscription créée'), ('signup_email_verified', 'Email vérifié'), ('signup_approved', 'Inscription approuvée'), ('signup_rejected', 'Inscription refusée'), ('portal_account_created', 'Compte portail créé'), ('client_logged_in', 'Connexion client')], db_index=True, max_length=50, verbose_name='Action')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_activities', to='core.company', verbose_name='Entreprise')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_activities_performed', to=settings.AUTH_USER_MODEL)),
                ('signup_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='portals.clientportalsignuprequest')),
            ],
            options={
                'verbose_name': 'Activité portail client',
                'verbose_name_plural': 'Activités portail client',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='clientportalsignuprequest',
            index=models.Index(fields=['company', 'status', '-created_at'], name='signup_company_status_idx'),
        ),
        migrations.AddIndex(
            model_name='clientportalsignuprequest',
            index=models.Index(fields=['email', 'company'], name='signup_email_company_idx'),
        ),
    ]
