# Generated by Django 4.2.30 on 2026-06-23 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_notification_related_names'),
        ('ecommerce', '0002_carrier_cart_couponcode_customerstoreaccount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='brand_key',
            field=models.CharField(choices=[('siecle', 'SIÈCLE'), ('lunea', 'LUNEA')], default='siecle', max_length=20),
        ),
        migrations.AddField(
            model_name='weborder',
            name='brand_key',
            field=models.CharField(default='siecle', max_length=20),
        ),
        migrations.CreateModel(
            name='CustomerBrandProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_key', models.CharField(choices=[('siecle', 'SIÈCLE'), ('lunea', 'LUNEA')], default='siecle', max_length=20)),
                ('preferred_theme', models.CharField(choices=[('siecle-noir-champagne', 'Noir Champagne'), ('siecle-bordeaux-nuit', 'Bordeaux Nuit'), ('siecle-ivoire-luxe', 'Ivoire Luxe'), ('siecle-rouge-signature', 'Rouge Signature'), ('lunea-cream-rose', 'Crème Rosé'), ('lunea-rose-gold', 'Rose Gold'), ('lunea-lunar-black', 'Lunaire Noir'), ('lunea-red-velvet', 'Rouge Velours'), ('lunea-champagne-light', 'Champagne Clair')], default='siecle-noir-champagne', max_length=60)),
                ('preferred_language', models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('es', 'Español')], default='fr', max_length=10)),
                ('animations_enabled', models.BooleanField(default=True)),
                ('display_density', models.CharField(choices=[('comfortable', 'Confortable'), ('compact', 'Compact')], default='comfortable', max_length=20)),
                ('marketing_optin', models.BooleanField(default=False)),
                ('newsletter_optin', models.BooleanField(default=False)),
                ('loyalty_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_brand_profiles', to='core.company')),
                ('store_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_profiles', to='ecommerce.customerstoreaccount')),
            ],
            options={
                'verbose_name': 'Profil marque client',
                'verbose_name_plural': 'Profils marque clients',
                'unique_together': {('company', 'store_account', 'brand_key')},
            },
        ),
    ]
