# Generated by Django 4.2.30 on 2026-06-26 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_notification_related_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_key', models.CharField(blank=True, max_length=40)),
                ('project_id', models.CharField(max_length=80)),
                ('project_name', models.CharField(blank=True, max_length=180)),
                ('log_type', models.CharField(choices=[('daily_report', 'Rapport journalier'), ('incident', 'Incident'), ('delivery', 'Livraison matériaux'), ('inspection', 'Inspection'), ('milestone', 'Jalon'), ('weather_stop', 'Arrêt météo'), ('visit', 'Visite chantier'), ('photo_report', 'Rapport photo'), ('safety', 'Sécurité'), ('other', 'Autre')], max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('photos', models.JSONField(blank=True, default=list)),
                ('documents', models.JSONField(blank=True, default=list)),
                ('workers_count', models.PositiveIntegerField(default=0)),
                ('weather', models.CharField(choices=[('sunny', 'Ensoleillé'), ('cloudy', 'Nuageux'), ('rainy', 'Pluvieux'), ('windy', 'Venteux'), ('stormy', 'Orageux'), ('snowy', 'Neigeux'), ('hot', 'Très chaud'), ('unknown', 'Inconnu')], default='unknown', max_length=30)),
                ('temperature_celsius', models.IntegerField(blank=True, null=True)),
                ('gps_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('gps_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('location_label', models.CharField(blank=True, max_length=255)),
                ('progress_percent', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('logged_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='btp_site_logs', to='core.company')),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='btp_site_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal chantier',
                'verbose_name_plural': 'Journaux chantier',
                'ordering': ['-logged_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteLogIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('safety_accident', 'Accident sécurité'), ('material_damage', 'Dommage matériel'), ('delay', 'Retard'), ('quality_issue', 'Problème qualité'), ('theft', 'Vol'), ('other', 'Autre')], max_length=80)),
                ('severity', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Élevé'), ('critical', 'Critique')], default='medium', max_length=30)),
                ('description', models.TextField()),
                ('corrective_action', models.TextField(blank=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='btp_site_incidents', to='core.company')),
                ('site_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='btp_smart_site_log.sitelog')),
            ],
            options={
                'verbose_name': 'Incident chantier',
                'verbose_name_plural': 'Incidents chantier',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='sitelog',
            index=models.Index(fields=['company', 'project_id', 'logged_at'], name='btp_smart_s_company_9cab68_idx'),
        ),
        migrations.AddIndex(
            model_name='sitelog',
            index=models.Index(fields=['company', 'log_type', 'logged_at'], name='btp_smart_s_company_75e14e_idx'),
        ),
    ]
